### ISSUE TITLE
Specific aircraft at certain airports. -help wanted

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#103]
Hello everyone.
I'm looking for an information, if there is how I restrict certain aircraft at certain airports?

I ask this in order that I am creating the "Domodedovo International Airport" (UUDD) and some Russian airline companies\* and me a problem arose if I add arrival and departure of ACA UUDD airport, they will use all kinds of aircraft in fleet and that's basically unlikely, an A320 for example would never do such a route.
- Do not have much knowledge about russia in general, I am using online databases to capture the fleets of companies (http://www.airfleets.net) and wikipedia to see larger companies.

Thanks all.

**Comment by zlsa** [comment]
This isn't currently possible; short of changing the way the aircraft selection works, you could just create a new airline `aca-russia` that does not have any A320s.

**Comment by MaicomMR** [comment]
Thanks for you answer.
I have more one question, can i make an thematic airport? for example, KJFK year 2000? But for this i will need create airlines ICAO2000.

I want this to see and control 727s, 737-200s, DC-8, DC-10, et, old planes :P

https://www.youtube.com/watch?v=qGpckXx56DU

**Comment by zlsa** [comment]
I don't see any potential issues with that, so go ahead.

**Comment by tedrek** [comment]
A method for restricting the aircraft which a given operator flies at a given airport was added in #292.  Further documentation is available from #305 once merged.  I believe this can now be closed.
