### ISSUE TITLE
Select traffic loads

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#108]
<h4>A way to dictate the traffic load</h4>

I like to be challenged. If I load the game and there are only a few planes I  will reload it until there is as close to a full board as possible. I already use the speed control to increase the pace of the game so that really doesn't address it. Sometimes I have to load twenty or more times to get a heavy load. Not a big deal, I enjoy the game enough to do it. But if it's relatively easy to implement it would be nice.

So, would it be possible to dictate the initial load (e.g. lite, med, heavy, insane, 9/11 terrorist attack type traffic, etc.)?

**Comment by zlsa** [comment]
It is now, thanks to @tedrek: #120
