### ISSUE TITLE
Flight strips are out of view with extremely heavy loads

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#109]
<h4>Ability to see more flight progress strips</h4>

Because I push the limits of the game I have, at times, had more strips than can be shown on my display (23 @ KMSP on my display). Obviously, if I can't the strips I'm unable to quickly identify its status or give it commands. This leads to forgotten or unheard taxi requests and wayward paths for approaching craft. I've tried selecting strips using the arrow keys but that is based on an order other than the order shown (most recently commanded?). Zooming in and out helps to a degree but requires clicking each and every craft and in a scenario such as I've described that's difficult and inefficient. 

So, I'm requesting the ability to see all flight strips regardless of the quantity. Perhaps something as "simple" as a scroll bar?

**Comment by tedrek** [comment]
On Ubuntu/Chromium43 I get a scroll bar on the strips when they grow larger than the visible display.

What are you playing on that it isn't making the progress strip area scrollable on overflow?

**Comment by Maverick283** [comment]
I too have a scroll bar. 

I guess this issue can be closed @zlsa ?
