### ISSUE TITLE
More realistic phraseology.

### ISSUE THREAD

**Issue by theorician** [zlsa/atc#11]
Wow, this is nice! Great work so far.

As a suggestion though, can you work on the phraseology a bit? For example, on the one hand you do things that are lifelike (clearing for an altitude after departure before a take-off clearance) and then on the other hand you have an aircraft read back 'climb 5000 after takeoff, roger', which is incorrect and dangerous phraseology. Also, 'roger' is only a term that ATC is supposed to use - not the pilots. 

Just small nitpicks, but great work!

**Comment by zlsa** [comment]
I looked up phraseology and filled in the bits I couldn't easily find. Is there a definitive FAA guide on phraseology?

Also, in many places, I had the pilot readback their commands to help out new users.

**Comment by theorician** [comment]
Yep, ICAO has standardised the phraseology! 

I can help you if you like with a bunch of these, but there's a seemingly decent summary here:

http://www.skybrary.aero/bookshelf/books/115.pdf

For example, it lists this, which was my point in my OP:

```
TAKE OFF AND DEPARTURE
‘Take-off’ shall only be used when issuing a clearance to take-off.
 - Do not use phrases such as ‘prior to take-off’ or ‘after take-off’.
 - If the controller uses ‘after departure’ or ‘follow’, this is NOT a clearance to take-off.
```

The document is probably a bit dense to read, but as I said, I can help you out a bit with it if you like :)

**Comment by zlsa** [comment]
Thanks for the link.

I've been flying in flight sims for a long time now and I always had trouble with phraseology (as I suspect many student pilots do as well).

**Comment by theorician** [comment]
Oh, most definitely. It does become second nature after even a week or two of flying regularly though, like all the rest of it :)

**Comment by zlsa** [comment]
In that specific example, would the proper reply be "speedbird 1234, climb six zero after departure"?

**Comment by pcrumm** [comment]
Generally, "after departure" would be omitted as it's clear from the context, but that particular reply wouldn't be incorrect (unlike anything with the phrase "take-off" in it).

**Comment by theorician** [comment]
Yep that's correct - except your altitude ;) I'd definitely leave 'after departure' in. Understanding things from context is hard for people that lack context :)

Your altitude is either in feet ("six thousand feet" or "five five zero zero feet") or as a flight level ("flight level six zero"). 

The transition from feet to FL is usually around the 5000-6000 feet mark, so your example managed to be a bit tricky, too. (The transition level is either published as a standard or, more usually, in the ATIS.) 

Technically, more correct would be 'Speedbird 123, after departure climb flight level eight zero', i.e. the after departure being before the clearance.

**Comment by sixeyeco** [comment]
anything that reduces the time they take to read back would be awesome. they get so backlogged that I sometimes miss taxiing awaiting aircraft. i'd love to just hear "Speedbird 123, roger".

**Comment by clawoflight** [comment]
@sixeyeco I'd prefer realism over brevity in this case. Or, this could be made an option? Would increase the complexity though...

**Comment by Maverick283** [comment]
#189 #222 Handle this issue...

@zlsa can this be closed? (Trying to clean up a bit here)

**Comment by zlsa** [comment]
Not a problem @Maverick283.
