### ISSUE TITLE
Two additional zoom levels

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#110]
<h4>Useful for extremely tight vectoring on approach. </h4>

Current zoom levels are good but greater zoom levels would be great!

**Comment by tedrek** [comment]
Is this an issue with seeing the aircraft precise position, or is it due to the aircraft infoboxes overlapping and hiding the aircraft themselves?

**Comment by sixeyeco** [comment]
Haven't been able to play for a while. Love the progression! I'll close this. No longer an issue.
