### ISSUE TITLE
Airport URL-load

### ISSUE THREAD

**Issue by AlexMcArrow** [zlsa/atc#111]
Add load `airport.json` by url.
Airport-url can store in `Localstorage`.
This makes it possible to upload airport without code changes.

Upd:
#113 Example - add for load in `modules.js`

Sorry for bad english.

**Comment by avdg** [comment]
Hmm, it might be better to expose the data from the javascript code itself in a usefull way.
Adding localstorage generally doesn't guarantee the code is using that data live unless additional code is added.

But this issue (should actually be a separate issue) does me think somehow hore about adding a manifest for offline usage of the app like this: http://www.html5rocks.com/en/tutorials/appcache/beginner/

**Comment by AlexMcArrow** [comment]
Store only url to file, and load file by url on init.

**Comment by erikquinn** [comment]
Closing along with #113.
