### ISSUE TITLE
Far from Tower Controller

### ISSUE THREAD

**Issue by akymakr** [zlsa/atc#128]
**We are just a Tower Controller, right?**
I have to clear an attitude, move the aircraft from the ground and the sky, and also clear some aircraft to land or takeoff? If this is a small airport ... OK but ... this is JFK, SFO and MSP! "Hire" someone to handle those OK? We just wanted to clear somebody to takeoff or land. Or we just want to line up some aircraft and then pass it to the Tower.

**Too many aircraft and they come from anywhere and low**
If I am the tower controller, I am gonna kill the guy who is handling the approach. You just can't let an aircraft coming from anywhere, without lining them up and pass it to the Tower in 50 miles away from the airport (also we can't tell them to "contact departure 125.7" or something). Can you just lower them down and create some fix that the aircraft should be born at?

**Command suggestions**
Go around, they don't understand. (abort)
Hold at XXXXX (waypoint) at YYY radial, 10 mile legs, left hand turns, they don't understand.

**Other suggestions and issue**
Well, the waypoint is lacking of many airports, not enough to provide SID or STAR. Also the coordinates is not accurate. We can't "Cross DUMBA at 3000 or above, cleared ILS 28R approach". DUMBA is just too far away from the airport.

Eh ... provide SID and STAR (not so urgent)?
Also a controller selection for DC, GND, TWR, DEP, APP? (I think not only me want this one)

Some callsign used normal alphabet but not the NATO one.

I could help to handle those JSON if you don't mind :)

**Comment by harp71** [comment]
Second that ...

And there has to be a "mission, target, goal" (call it what you want) for departing flights

**Comment by glangford** [comment]
@akymakr @harp71 try the new version of KSFO and post any comments. Aircraft now arrive with fixes set; see ksfo.json. 

Departures now have a goal (all airports).

**Comment by harp71** [comment]
Oh, the departure goal is represented by the blue marker on the outer circle? That´´s better :)
I´m used to (from other ATC sims) having a departure goal before taking of, so you can choose the runway accordingly. And the goal is usually not a area but a fix-point.
But its fine that way for me :)
Finally there is sense to departures.
Now we need SIDs :))

**Comment by Maverick283** [comment]
@harp71 SIDs have already been mentioned earlier, yet STARs seemed to be more important for the moment. The guys programming all this can always do only so much ;)

**Comment by harp71** [comment]
i´m gratefull no doubt. I wish i could contribute more than suggestions ...

2015-10-23 15:29 GMT+02:00 Maverick notifications@github.com:

**Comment by glangford** [comment]
@harp71  @Maverick283  STARs are now implemented for a couple of airports (KSFO, KLAX and ENGM) and are automatically assigned. I'm not sure it makes sense to have a "STAR" command to enter, as I originally suggested in #147. Note also that the STARs can be seen for arriving aircraft by simply clicking on each one to see the future path, or entering "*" to select all.

For SIDs - I have been manually assigning them (FIX a b c d) before takeoff. 

Does it make sense to
- add a SID command that is really a synonym for multiple fixes
- define the SIDs in each airport json
- perhaps paint the available SIDS on the canvas with a command

(No promises implementing it just yet, just wondering out loud what it would look like)

**Comment by Maverick283** [comment]
@glangford I think SIDs in general would make sense. 

Whenever you select an aircraft that is on the ground, you could then get paint the available SIDs on the canvas. Since there are some SIDs that only work on one runway of two parallel runways, you could either only paint one SID (of one runway that is active to the departure point close to the area of departure) or have the user define first which runway is to use for each aircraft and then paint all SIDs available onto the canvas (though this might be difficult to explain to a user).

Another option would be (and I wanted to gather some opinions on that somewhere else) to add a autocomplete function. There you could type "SID", hit space and cycle through all SIDs using some keys, displaying all the SIDs on the canvas.
