### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by joallard** [zlsa/atc#13]
I've been playing on my Macbook Air for a few hours, and the fan has been going like crazy since I've opened the game. The battery is taking a big dip either. I'm running Firefox Aurora 36. Is it just me or could this game benefit from a few well-placed perf optimizations?

**Comment by zlsa** [comment]
I've never even attempted to optimize it. I'll work on it.

**Comment by joallard** [comment]
Good job. I've tried profiling a little, but wasn't nearly proficient enough with the architecture to see an obivous fix. [`canvas_update_post()`](https://github.com/zlsa/atc/blob/gh-pages/assets/scripts/canvas.js#L434) came up.

**Comment by zlsa** [comment]
That's where the entire radar view is drawn. There's no view culling yet. The current bottleneck is drawing the text for each airplane; if I have to, I'll move the text drawing to the DOM, but that's a pretty major change.

**Comment by zlsa** [comment]
I've vastly reduced redrawing in version 2.1.4; could you test again?

**Comment by jvt** [comment]
@joallard What year is your MBA? I'm also playing on an Air and didn't notice any performance-related issues in the prior versions.

**Comment by joallard** [comment]
2.1.4: CPU seems to have more breathing space. I think the regular speed has gotten slower though. Might be unrelated.

@jvt Late 2013.

**Comment by zlsa** [comment]
@joallard, aircraft speed shouldn't change; I just redraw the canvas once every 20 frames or so. They might jump visibly when on higher speed settings, though.

**Comment by joallard** [comment]
It may very well just be my perception, caveat emptor, but it feels to me a little more jittery and slowish.

**Comment by glangford** [comment]
A significant portion of the time to draw each aircraft - 60-80% using `console.time()` - is drawing the trailing position dots, not drawing the aircraft itself. This is because `canvas_draw_aircraft()` saves and restores context and recreates a custom `fillStyle` and a filled arc - for every single trailing dot for every visible aircraft. This is very slow. I will send a pull request with an idea for a faster method which is visually similar.

**Comment by glangford** [comment]
The first picture is the existing aircraft trail, the second is a test of a much faster method (rectangles and fixed opacity).
<img width="346" alt="current trails" src="https://cloud.githubusercontent.com/assets/3035114/9170224/0cb7b996-3f2f-11e5-9f48-d2d4dc59debb.png">
<img width="457" alt="fast trails fixed opacity" src="https://cloud.githubusercontent.com/assets/3035114/9170225/1299cef8-3f2f-11e5-8425-b43224d68a66.png">

**Comment by glangford** [comment]
And here is a picture of the fast method with variable opacity. Which is the best?
(EDIT: This can be drawn in 1/5 of the time compared to the current method)
<img width="617" alt="fast trails variable opacity" src="https://cloud.githubusercontent.com/assets/3035114/9172466/caaa9466-3f41-11e5-9073-d2b667570629.png">

**Comment by joallard** [comment]
@glangford Nice. This last render looks really good!

**Comment by glangford** [comment]
@joallard , @zlsa - With changes #131, #141, #149, #150 I can run now for an extended period without excessive heating or fan use (older Macbook Pro). If there are no objections, I propose this issue can be closed.

**Comment by joallard** [comment]
I'm clocking in at 1.5% CPU usage. Good job.
