### ISSUE TITLE
Draw projected aircraft path when selected

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#132]
One way to help plan aircraft movements is to see where an aircraft will go in future, based on the ATC commands that have been entered.

For example, in following multiple fixes:

![waypoints](https://cloud.githubusercontent.com/assets/3035114/9279590/890a7a60-4286-11e5-8be5-1c78253b06a9.png)

Or following a heading and landing (the track is brighter when ILS lock is expected to happen):

![landing2](https://cloud.githubusercontent.com/assets/3035114/9279606/9be53c1a-4286-11e5-8247-2a9b286f0da6.png)

These are screenshots from a running prototype. Appreciate any comments or suggestions.

**Comment by zlsa** [comment]
This is awesome.
