### ISSUE TITLE
Defining radar scope vs. control scope

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#134]
Currently the radar scope is twice the airport ctr_radius or 160 km.  Altitude is ground level to infinity within that distance.  The current control scope is the same distance, with 10,000' being the maximum altitude assignable.

I was thinking of changing the control scope to be the ctr_radius laterally and 0-10,000' vertically.  Aircraft outside of the controlled airspace would not respond to radio commands or show a flight strip, and would be visually displayed in a subdued manner.  All relevant scoring would occur at the control boundary instead of the current lateral 'radar' boundary.  An altitude of 11,000' would be assignable as an implied hand-off to the controller of the airspace above.

I had been thinking hand-offs should be implicit, as they are currently.  Making them explicit doesn't feel fun.

Thoughts? Does this feel right for this game?

**Comment by glangford** [comment]
To make this work I think the spawn rates, positions and tracks for new aircraft would have to be retuned for each airport. For SFO for example, it is currently necessary to issue commands to distant aircraft for things like popping up randomly in the path of a takeoff runway. Also, traffic separation is currently not guaranteed outside of the control boundary, and giving new vectors very early helps a lot. But if there was some greater order imposed (i.e. tighter enroute/area control spawn policy into each airport) then this new approach makes a lot of sense.

**Comment by tedrek** [comment]
I absolutely agree, spawning would need to be tuned.  Likely departure would also need work to keep them from being vectored into an arrival.
