### ISSUE TITLE
Balancing arrival/departure rates for realism and fun

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#156]
The current arrival and departure rates seem to be inconsistent between different airports.  This issue is trying to develop a set of guidelines for arrival and departure rates in the future, and a proposal to rebalance arrival and departure rates of existing airports to meet the needs of the community.

Currently difficulty scales with the aircraft rates, these have been historically chosen by which airport is played and more recently can be adjusted with the rate command.  Each airport is assigned a difficulty level, however that is not exposed to the player at this time.  Following is a table of the current airports with their operations in aircraft/hour.

| Airport | Difficulty | Arrivals | Departures | Contributor |
| --- | --- | --- | --- | --- |
| kjfk | hard | 12 | 30 | psycho202 |
| sbgl | hard | 13 | 7 | MaicomMR |
| ebbr | hard | 25 | 30 | stijnsanders |
| eddh | medium | 25 | 30 | larsen0815 |
| ksfo | hard | 36 | 20 | zlsa & glangford |
| eham | hard | 36 | 40 | Sander Ufkes |
| sbgr | hard | 39 | 40 | MaicomMR |
| kdbg | hard | 49 | 30 | zlsa |
| uudd | hard | 51 | 20 | MaicomMR |
| kmsp | hard | 55 | 30 | Joe Turgeon |
| ksra | medium | 60 | 30 | zlsa |

There are a couple things of note:
- ebbr and eddh have identical arrivals (copy and paste in the .json) yet differing difficulties.
- kjfk is not complete and should be disregarded
- kdbg and kmsp have identical arrivals with a couple of frequency changes.

From the above it appears the playable range in terms of operations is considered to be 20/hour to 90/hour.  Arrivals are preferred over departures.  The number of operations isn't as significant as the airport to some players as evidenced by new airports with identical arrivals to existing airports.

The proposal which I would start off with would be:
- Model airports based on real-life 80% capacity (approximately)
- Rate airports on a scale of 1-5 for difficulty:
  *\* 1 = 0-20 arrivals
  *\* 2 = 20-35 arrivals
  *\* 3 = 36-50 arrivals
  *\* 4 = 51-70 arrivals
  *\* 5 = 71+ arrivals
- Expose the difficulty rating beside each airport as 1-5 aircraft icons (✈)
- Prefer departures as equal or less than arrivals
- Keep the rate command to allow players to tune a given airport to their preference (hopefully expose it through the GUI at some point)

Thoughts?

**Comment by zlsa** [comment]
That all sounds great. The difficulty value was originally intended to be added after a bit of playtesting, since pure frequency isn't always a very good measure.

**Comment by glangford** [comment]
For the traffic levels at the airports which have been updated, we have different choices for sure: KSFO at 36/20 is slightly below average real traffic and 56% capacity. With the new KJFK levels in #144 with timing variation, 40/35 is right at average traffic but 88% capacity. Consistent with those numbers, KSFO is on the easy side and KJFK is more difficult.

Maybe each airport could have two built in difficulty levels - beginner and advanced. You learn the airport layout, traffic patterns, which runways work for the wind, etc. with beginner. The current KSFO would be an example. Then advanced mode effectively has a “rate” command automatically applied.
