### ISSUE TITLE
Collision on landing fills screen with messages, deducts ~5000 pts

### ISSUE THREAD

**Issue by joallard** [zlsa/atc#170]
I think I set two planes to land face to face on the same airstrip. Needless to say, -5000pts is a little heavy for a penalty.

**Comment by tedrek** [comment]
I tried to duplicate the bug but couldn't get two aircraft to collide on landing, I did manage to get two aircraft to hit each other more than once though.

Looks like there is an issue with hits not changing the aircraft state properly, perhaps to do with runway tracking.  I'll try to look at it in the next couple of days if somebody else doesn't get to it.

**Comment by glangford** [comment]
I also tried to duplicate the bug but was unsuccessful.

> Looks like there is an issue with hits not changing the aircraft state properly...

I looked through the code with that thought in mind. Here is a pathological case to consider; _3_ aircraft in close proximity, _all below 1000'_. Call them `this`, `other1` and `other2`.
- In `updateWarning()`, `this` and `other1` are landing face to face on the same airstrip and a warning is generated. `this.warning` is now true.
- Going through the `for` loop a second time, `this` and `other2` are close, but not satisfying a warning. `this.warning` now is set to false; see the annotated code below.
- the next time an update occurs, `this.warning` is reset to true for `this` and `other1`, and the negative score is repeated

``` js
          // Check for the same runway, headings differing by more
          // than 30 degrees and under about 6 miles
          if ((this.requested.runway != null) &&
              (airport.getRunway(other.requested.runway) ===
               airport.getRunway(this.requested.runway)) &&
              (abs(angle_offset(this.heading, other.heading)) > 0.5236) &&
              (distance < 10))
          {
            if (!this.warning) {
              ui_log(true, this.getCallsign()
                     + " appears on a collision course with " + other.getCallsign()
                     + " on the same runway");
              prop.game.score.warning += 1;
              this.warning = true;
            }
            warning = true;
          } else {
            this.warning = false;  // <---- warning is cleared  ******
          }
```

Not sure this is the cause, but it could be one path through the code causing the warning state to flip flop, and trigger cascading warnings.

EDIT: Here is a link to the code of interest
https://github.com/zlsa/atc/blob/gh-pages/assets/scripts/aircraft.js#L1178

**Comment by tedrek** [comment]
Nice work, so here is a test case which shows the issue:
- Line up two aircraft on parallel runways for takeoff (`xx1 w 36l c 1`, `xx2 w 36r c 1`)
- Line up a third aircraft at the opposite end of one runway (`xx3 w 18r c 1`)
- Once all are lined up order all to takeoff (`xx1 to`, `xx2 to`, `xx3 to`)

I don't have time for a fix right now, so don't assign aircraft to opposite ends of the same runway for now :smile:.

@glangford, I don't see a quick way of fixing this.  Counting warnings/notices generated would fix this specific flip-flop but would mask new warnings during the violation.  I think to properly fix it will require keeping state for each pair of aircraft and checking on that, the plus side is it will cut the number of warning checks required in half.

**Comment by glangford** [comment]
> I don't see a quick way of fixing this. Counting warnings/notices generated would fix this specific flip-flop but would mask new warnings during the violation. I think to properly fix it will require keeping state for each pair of aircraft and checking on that, the plus side is it will cut the number of warning checks required in half.

At first glance I don't see how to quickly fix this either. It does seem like a major pain to keep state for each pair of aircraft, hopefully we can find something simpler - even if it means some warnings are masked.

One thought might be to assign an expiry timestamp to each warning - so if aircraft A has a warning issued with aircraft B, it will persist for some number of game ticks. That gives the opportunity for the situation to be rectified. (It would also have the side effect of masking additional warnings during this period). If it is not rectified, it gets reported again with repeated penalty. If it is rectified, any new warnings that are present at that time will be reported.

I'm not suggesting this is a perfect solution, but just thinking out loud to find a way to prevent the -5000 points issue while also trying to lead the user to repairing a situation.

**Comment by joallard** [comment]
What if instead of tracking `this.warning` as a boolean, we made it an array with other aircrafts?

``` coffee
# Instead of
this.warning = false

if isCollidingWith(other)
  if !this.warning
    this.warning = true
else
  this.warning = false

# Consider
this.warnings = []

if isCollidingWith(other)
  if !this.warnings.include(other)
    this.warnings.push(other)
else
  this.warning.remove(other)

# Or object form
this.warnings = {}

if isCollidingWith(other)
  if !this.warnings[other.callsign]
    this.warnings[other.callsign] = true
else
  delete this.warnings[other.callsign]
```

**Comment by glangford** [comment]
> What if instead of tracking this.warning as a boolean, we made it an array with other aircrafts?

Sure that is possible, but given that the vast majority of aircraft will not be in conflict with others, and should be relatively infrequent, I was thinking of less complexity.

**Comment by joallard** [comment]
Correct me if I'm wrong, but most aircraft will never enter the warnings collection.

**Comment by glangford** [comment]
> Correct me if I'm wrong, but most aircraft will never enter the warnings collection.

Absolutely true, sorry for not being clear - I should have said I was thinking of less _code_ complexity, given that most aircraft will never have warnings. So the extra code does not really deliver a better user experience.

**Comment by tedrek** [comment]
I've got a fix to the pathological case as #173.  It's still got the issue of masking other warnings but as you've pointed out that should be quite rare.  In fact the only real draw back in game terms at the moment is not alerting to another runway collision and the associated scoring event.

The  thought I had for keeping state between aircraft pairs was that the current system calculates both the A->B warnings and B->A.  I think all checks could update both aircraft at the same time while halving the number of checks required.  The specific reason I had for keeping some state was in the case of simultaneous parallel departures which are allowed so long as headings after departure differ by at least 20 degrees and separation is increasing.

**Comment by glangford** [comment]
@joallard can this issue be closed now?

**Comment by joallard** [comment]
Probably seeing there's been a fix, I haven't played since
