### ISSUE TITLE
Proposal to stop spawning new aircraft. 

### ISSUE THREAD

**Issue by nielsvdweide** [zlsa/atc#172]
I don't know if someone could implement this in the current game, but i would like to propose a button which temporarily stops the spawning of all aircraft, so you can keep up with all the aircraft coming up on the radar. My experience in some airports is that too many aircraft spawn and i can't keep up with the huge amount of traffic coming in.

I would like to propose a button which currently stops spawning of aircraft. Let me know if this can be implemented :) 

Regards, Niels

**Comment by tedrek** [comment]
It can be done, but I don't know when.  In the mean time you can reduce the rate of aircraft spawning using the rate command.  For example typing `rate 0.5` would make aircraft spawn at half of the normal rate, you could go down to something like `rate 0.1` to really cut down.  To go back to the normal rate type `rate 1`.  You can also make more aircraft spawn by using numbers large than 1.  I'm not sure what would happen if you used 0, it probably won't work correctly.

I'm currently doing some work on balancing airport spawn rates and associated difficulties, I would be very interested to know which airports you find to have the right number of aircraft spawning and which ones have too many.

**Comment by nielsvdweide** [comment]
Thank you for the quick response. I didn't know about the rate command so thank you very much for that.  I don't know much about HTML5 or even scripting, but i am known in the world of aviation and also communications with air traffic control. I am a pilot so i tend to know some stuff. 

Anyway, i really enjoy playing this game. It is so addictive and a really good memory and multi-task trainer! The only airport I think has got a good balance is SBGL. Sometimes, i play EHAM but after a while the departures build up and there isn't a way to get them down quickly. I tend to play at twice the speed instead of normal speed. 

Another thing I was thinking of was to have two sorts of screens to the right. One for departures and one for arrivals. Now arrivals and departures are kind of mixed up... It would make more sense if they were separate. 

Regards
