### ISSUE TITLE
Select all airplanes.

### ISSUE THREAD

**Issue by nielsvdweide** [zlsa/atc#175]
I would like to implement a way to select all airplanes. This way you can see what every airplane is doing and if they are going to cross each other. I came across this when i type in a letter some airplanes will be selected including a picture of where they are heading and going. I would like to add a command which shows the path of all airplanes! We could use the word "all" to highlight all airplanes.

<img width="800" alt="schermafbeelding 2015-09-10 om 14 09 53" src="https://cloud.githubusercontent.com/assets/14002770/9845616/9894e11a-5acc-11e5-9fda-669e39320e61.png">

As you can see, 3 airplanes are selected, but i would like to see a new function where you can select all airplanes!

I would like to have some thoughts about this! Let me know

**Comment by Maverick283** [comment]
As STARs and thus routes are about to be implemented, a line following the whole path of the route each airplane takes would be a great help in figuring out where each aircraft is going, as STARs are assigned by the system rather then the user.

**Comment by nielsvdweide** [comment]
Any programmers that can implement this?

<img width="1911" alt="schermafbeelding 2015-09-16 om 15 23 10" src="https://cloud.githubusercontent.com/assets/14002770/9905843/a521b022-5c87-11e5-83e9-a1bfa375841a.png">

As you can see now all airplanes have been selected :)

**Comment by glangford** [comment]
> Any programmers that can implement this?

@nielsvdweide - I like the idea, I hope to have some time to look into it.

**Comment by glangford** [comment]
How do you feel about a small change to this feature? Instead of the word "all" as a distinct command, how about typing asterisk ("*"), without having to press return/enter? This is very easy to implement, and selects all airplanes with less typing.

**Comment by glangford** [comment]
> As STARs and thus routes are about to be implemented, a line following the whole path of the route each airplane takes would be a great help...

@Maverick283 - good idea. Note that this could be useful even before STARs are implemented, since a series of fixes can be assigned today by providing multiple fixes in one FIX command. Can you open a separate issue to track this?

**Comment by nielsvdweide** [comment]
@glangford You could use any command! It doesn't really matter what it is! Typing "/ " for instance does the same and is easy to reach on the keyboard too! I think that it's important to pick a command which is easy accessible on the keyboard. 

What do you mean with: "Note that this could be useful even before STARs are implemented, since a series of fixes can be assigned today by providing multiple fixes in one FIX command. Can you open a separate issue to track this?"

**Comment by glangford** [comment]
> What do you mean with: "Note that this could be useful even before STARs are implemented, since a series of fixes can be assigned today by providing multiple fixes in one FIX command. Can you open a separate issue to track this?"

I was responding to the comment made by @Maverick283 requesting a line following the whole path of the route. Today you could type

**BAW123 FIX a b c d e**

So the future track line could reflect the scheduled fixes.

**Comment by nielsvdweide** [comment]
Ah thank you! Maybe we could even implement this in the screen at the right hand side. Now it only says the fix where the aircraft is currently navigating to. Maybe with a smaller text we can add the entire clearance/route?

Btw, are you currently working on this?

**Comment by glangford** [comment]
This shows how it could look:
![extended track](https://cloud.githubusercontent.com/assets/3035114/9916412/33a45294-5c8a-11e5-8210-7854700d875c.png)

**Comment by nielsvdweide** [comment]
@glangford Very very good! The solid red lane is a specific time length right? Do you know in what time the airplane travels the solid line in all game speeds?

**Comment by glangford** [comment]
> Btw, are you currently working on this?

I have submitted a change to implement "select all airplanes" and am working on extending the display of the future track.

> The solid red lane is a specific time length right? Do you know in what time the airplane travels the solid line in all game speeds?

The solid red line is a specific time length, which is the same time period for all aircraft. If one plane is travelling faster, the solid portion will be longer. If you speed up the game, the solid portion doesn't change, time is just accelerated.

I will test this combined with the "select all" aircraft change to make sure it works ok.

**Comment by nielsvdweide** [comment]
Great work! I know about the specific time length and that they're equal to all aircraft! I would like to know how long the line is. For instance at speed x1 the line means 1 minute and at speeds x5 the line means 15 seconds. Something like that! 

I would love to see this implemented :)

**Comment by glangford** [comment]
> I would like to know how long the line is. For instance at speed x1 the line means 1 minute and at speeds x5 the line means 15 seconds. Something like that!

Hmmm... good question! The solid line represents 60 "ticks" but I'm not sure what that represents in real time (I don't know that part of the software).

**Comment by nielsvdweide** [comment]
Ah okay! Thank you for explaining! Does your submission need approval from zlsa before being implemented? :)

**Comment by nielsvdweide** [comment]
I've seen you are implementing this when you type in an Asterix. So you have to hold shift and 8 to type this. I think it is better to change it to for example: / 

Much easier accessible on the keyboard

**Comment by glangford** [comment]
> Does your submission need approval from zlsa before being implemented? :)

Yes, all submissions must be approved. Asterisk is the wildcard character often used in matching, so my vote is to use that  even though you have to hold shift. (It's still shorter than "all".  :-) Here is what the two features combined look like at the moment; note that overlapping dashed lines look a bit different:

![combined all aircraft and fix tracks](https://cloud.githubusercontent.com/assets/3035114/9917116/e1cb9064-5c8d-11e5-8d4a-2a43a08f14d9.png)

**Comment by nielsvdweide** [comment]
Ah i see where you are going! Thank you! Is there a way i can test this myself? :)

**Comment by glangford** [comment]
> Is there a way i can test this myself? :)

Not yet, hopefully coming soon!

**Comment by nielsvdweide** [comment]
Cool! Thanks :) Are there any other things you are working on right now?

**Comment by tedrek** [comment]
@nielsvdweide, how would you like to see the projected paths for all aircraft all the time as opposed to just when there is a \* in the command box?

**Comment by nielsvdweide** [comment]
@Tedrek what do you exactly mean with that? @Glangford made a fix for this and he shows a red dotted line instead of a solid one and I'm quite happy with that.

**Comment by tedrek** [comment]
@nielsvdweide, there are three different possibilities which we are talking about for the paths.

The existing one which shows the path for the 'current' plane.
The `*` one which temporarily shows the path for all planes.
And the third one where all planes show their path all the time, this is the option I was asking about.

Probably the best way for the third way to work and what I'm suggesting, is to have a place where you can choose from a couple of options for the projected paths.  I'm thinking specifically 'none' which doesn't draw them at any time, 'selected' which is the current way it is done, and 'always' which draws the paths irregardless of what you have typed.

@glangford, I have an initial implementation in my branch t-options-dialog.  It's not complete, for example it needs styling so you can read the drop down menu.  I've been feeling it's time for an options dialog so players can easily tweak the game options.  The only option I have in there currently is a selection for the above options, a natural next one is a slider for the length of the projected path.

I like the fix path option, is it just drawing a straight line between fixes or is it doing a simulation like the current path?

As to the question of how long the paths are, they are 5 minutes long.  The game ticks are in decimal seconds, the future tracks are projected for 60 steps at 5 second intervals (`prop.game.delta`).  2x and 5x simply make game time pass that much faster and therefore the paths are 2.5 minutes and 1 minute long in real time.

@zlsa, do you have any issue with me putting up testing branches on my server so we can get easy feedback prior to merge?

**Comment by nielsvdweide** [comment]
@tedrek Thank you for your explanation.

> The existing one which shows the path for the 'current' plane.
> The `*` one which temporarily shows the path for all planes.
> And the third one where all planes show their path all the time, this is the option I was asking about.

I love the effort you put in to this. Personally, implementing this feature rocks but adding new features that will even upgrade this would be awesome. This drop-down menu including different options regarding aircraft drawings will add a great value to the game. 

> The only option I have in there currently is a selection for the above options, a natural next one is a slider for the length of the projected path.

For the lengt of the projected path; Currently it is 60 game-ticks which sometimes works for me, but sometimes you need a longer line to vector them to the approach perfectly. I would say we need an option for 60 (standard), 120 and maybe 200? I don't know what it would look like regarding these figures as i'm not a programmer.

**Comment by glangford** [comment]
> I have an initial implementation in my branch t-options-dialog. It's not complete, for example it needs styling so you can read the drop down menu. I've been feeling it's time for an options dialog so players can easily tweak the game options. The only option I have in there currently is a selection for the above options, a natural next one is a slider for the length of the projected path.

@tedrek - the option dialog idea is brilliant. Not sure what different things should go in there, but I had a quick look at t-options-dialog and it looks great. For me - in terms of variable settings, I probably would not change the length of the projected path.

> I like the fix path option, is it just drawing a straight line between fixes or is it doing a simulation like the current path?

It is an extension to the projected track. The projected track would be drawn in two steps (1) solid line representing 60 ticks (2) dashed line connecting the fixes that are scheduled after 60 ticks. Part (2) is done with just a line between fixes, no simulation. 

The logic behind two different lines is so that the solid line can be used as a measuring stick of sorts.
Also, if multiple aircraft are selected, I have set the compositing mode on the canvas so that overlapping dashed lines appear different. So you can see at a glance the sections with heavier future traffic. 
- For the \* command itself - see the pull request or the development branch "select-all"
- For the extension to the track suggested by @Maverick283, the development branch "future-track-fixes" ~~will be up shortly~~ is up.

**Comment by Maverick283** [comment]
@glangford Thanks for opening and taking care of that, I have not had time to respond yet!

**Comment by glangford** [comment]
Everything is up live now, check it out.

ps. @nielsvdweide - I know you are not the first pilot in this video.   :wink:

https://youtu.be/MroI44p4npA
