### ISSUE TITLE
[SLOVED] GitHub Fail to sync

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#180]
Hi everyone,
sorry about my noob question, but I have a little trouble with github pull request, I call the pull request and receive this messages.
![fail01](https://cloud.githubusercontent.com/assets/12571488/10006627/2787e854-6095-11e5-8c25-bfb1b4759c4d.png)
![fail02](https://cloud.githubusercontent.com/assets/12571488/10006628/278b19b6-6095-11e5-95f9-707a3806e9ad.png)

Someone who happening?
Sorry my bad english.

**Comment by zlsa** [comment]
I have no idea - I don't use the Windows client. However, it looks like you're trying to push directly to my repository, which isn't possible - you'll have to make a pull request, modify your copy, then push that to your repository, _then_ open a PR back to mine.
