### ISSUE TITLE
Suggestion ILS locked color

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#182]
Hi all, today I play and see a little problem on the colors of the "ILS Locked" with the airplanes ready to departure, for the two are blue I sometimes confounded the lockados with ready to leave. I thought I'd suggest a different color for the lockados, created an example with green.

Now - ![sbgr_ils_color2](https://cloud.githubusercontent.com/assets/12571488/10009728/8721b278-60b7-11e5-9be8-b48a8a8d1224.png)

Suggested - ![sbgr_ils_color](https://cloud.githubusercontent.com/assets/12571488/10009717/6822ad82-60b7-11e5-9fbf-804be24ae85d.png)

I try see and change the css with colors, but i not found the title for ils. :(

**Comment by Maverick283** [comment]
I think that's a great idea!

Before everyone goes out color smashing now, a word of warning though: Keep in mind there are color blind people, or people with a color deficiency out there. While this suggestions still looks to me (I do have a color deficiency) it might already be hard for someone else to tell which one is green and which one is red, or even which one is green and which one is blue.

Just something to keep in mind when playing with colors, unfortunately most programmers don't have that in mind (No offense though, I mean why would they, its hard to comprehend what we see and what we don't).

**Comment by vfrico** [comment]
And, how about adding an option and put the text in italics or bold instead of changing the color?
