### ISSUE TITLE
New airport: EDDN

### ISSUE THREAD

**Issue by nielsvdweide** [zlsa/atc#184]
Currently, I'm busy with adding a new airport: eddn. (nurnberg) It's a single-runway airport in germany! I've added most of the fixes for the airport now and i'm still busy with tweaking departures and arrivals (any tips on this?) I would also like to implement SIDS and fixes for the places where departures need to go. (As the departure destinations are quite sketchy i think)

<img width="1913" alt="schermafbeelding 2015-09-22 om 16 49 08" src="https://cloud.githubusercontent.com/assets/14002770/10022137/91aaed24-614b-11e5-98c1-2d0fe0206e52.png">

For the moment, this is how it looks like. I am going to delete some of the way-points as it is quite busy around the airport, but i thought it's better to add all of them first and then delete those which i don't need.

If anyone can think of something, please let me know! :)

**Comment by MaicomMR** [comment]
Hey @nielsvdweide how do you make the waypoints coordinates? I'm looking for a more pratice and precise method.

**Comment by tedrek** [comment]
If you are using real world waypoints/fixes, you can use the latitude and longitude directly.  Make sure to set the reference coordinates on the airport.

**Comment by nielsvdweide** [comment]
@MaicomMR 

For coordinate data the code takes three formats:
Decimal degrees - 'N47.112388112'
Decimal minutes - 'N38d38.109808'
Decimal seconds - 'N58d27m12.138'
You can also use the degree symbol instead of d, or a single quote instead of m or a space instead of either. I did it this way precisely because opennav showed degree/minute/seconds but another source I was using was decimal degrees.

This is the way I do it:

> "AKANU":  ["N49d03m03.00",  "E010d39m29.16"],
>     "BAMAS":  ["N49d52m47.82",  "E011d02m44.99"],
>     "ERETO":  ["N49d55m51.60",  "E011d24m29.57"],

**Comment by MaicomMR** [comment]
Wow, that will greatly facilitate my life in the future will retrace weypoints the SBGL and SBGR, 
thanks @tedrek and @nielsvdweide

**Comment by nielsvdweide** [comment]
It only works when you have the entire airport layout in coordinates: so the center of the radius as well as all the runways! I'm currently working on a little fix of EHAM @MaicomMR

**Comment by tedrek** [comment]
It should work with a mix of offsets and co-ordinates (in any of the formats).  The only requirement is that a 'position' is defined for the airport itself to denote the center of the radar scope.  I don't suggest making anything new with mixing things, but you can certainly update existing ones in stages.

**Comment by nielsvdweide** [comment]
My bad! Only a center position for the radar is needed!

**Comment by tedrek** [comment]
@nielsvdweide, are you still working on this?  Could you use any assistance?
