### ISSUE TITLE
Reworked Airports SBGL and SBGR:

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#188]
Hi everyone,
I'm reworking SBGL and SBGR(Which I had created a few months ago), now I'm using the coordinates system to place(and replace) the waypoints, I'm taking the coordinates on aviation charts and virtual aviation charts, see the results bellow:

SBGL:
![sbgl](https://cloud.githubusercontent.com/assets/12571488/10064942/e7de8b88-6254-11e5-9fc9-97f7dd2093e6.jpg)

SBGR:
![sbgr](https://cloud.githubusercontent.com/assets/12571488/10064943/e7e360d6-6254-11e5-821a-36caa534ec4b.jpg)

SBGL Arrival entraces:
![sbgl-arrivals](https://cloud.githubusercontent.com/assets/12571488/10064952/0b37c644-6255-11e5-8de4-48ca6450c2a5.gif)

SBGR Arrival entraces (comming soon):

A special thanks to @tedrek and @nielsvdweide about teach me how to use real coordinates to position airport, runways and waypoints.

All feedback are welcome.

**Comment by tedrek** [comment]
That's a cool animation showing the STARs, looking forward to seeing them :smile:

**Comment by tedrek** [comment]
These updates appear to have taken place in #192, #223, and #236.
