### ISSUE TITLE
Better starting and landing clearances

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#189]
When an aircraft is given takeoff clearance, a simple "Callsign, cleared for takeoff" is in the radio box. 

Different countries, different phraseology, but all takeoff and landing clearances should include:
- Callsign (e.g. "United 123,")
- Wind information (e.g. "Wind 80 degrees, 5 knots.")
- Runway (e.g. "Runway 32R")
- Clearance (e.g. "Cleared for takeoff" or "Cleared to land)

Any reasons why this is not implemented? Should it be implemented?

**Comment by zlsa** [comment]
No, and yes. I just didn't add it because I had forgotten about it...
