### ISSUE TITLE
Allow takeoffs to be aborted.

### ISSUE THREAD

**Issue by zlsa** [zlsa/atc#19]

**Comment by stijnsanders** [comment]
does that mean making waiting planes taxi back to the apron?

**Comment by zlsa** [comment]
It will allow an aircraft that's taking off to be aborted; it will taxi back to the apron and act like a brand-new departure.

**Comment by stijnsanders** [comment]
is that the bit about "v1" and "v2"?

**Comment by zlsa** [comment]
In real life, there are three major V speeds:
- V1: above this, you are committed to takeoff and cannot abort any longer.
- Vr: Lift the nose up ("rotate")
- V2: Minimum takeoff speed with one failed engine

I'll just calculate V1 as `aircraft.speed.landing*0.75` or similar.

**Comment by sixeyeco** [comment]
oh! could the "v status" replace knots on tag on takeoff? then we could see if it's too late to abort! once a craft hits, say..1000 ft then the knots would replace v staus.

**Comment by Maverick283** [comment]
Takeoffs can be aborted, yet I do like the V status. Opened a new issue (#268) for this and I think this one can be closed now, @zlsa
