### ISSUE TITLE
Bug in canvas_draw_aircraft

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#195]
The following code in `canvas_draw_aircraft()` refers to w and h, both of which are undefined:

``` js
var t = crange(0, distance2d(
      [clamp(-w, km(aircraft.position[0]), w), clamp(-h, -km(aircraft.position[1]), h)],
      [          km(aircraft.position[0]),               -km(aircraft.position[1])    ]), 30,
                  0, 50);
```

As a result, t appears to always be zero.
1. Can this code simply be deleted, or is there some higher purpose? I can't tell what it was trying to achieve.
2. This was found by static analysis (jshint). Is there any interest in using jshint and/or strict mode in the project? It flagged a number of other potential problems in a test conversion of canvas.js.

**Comment by zlsa** [comment]
1. I have no idea what `t` is for. (`crange` is a linear interpolation function that clamps the output). It looks like it might be an offset for when the aircraft is close to an edge, but I'm not sure.
2. Absolutely. I wrote this when I was much less experienced with JavaScript and before I had even heard of JSHint.

**Comment by glangford** [comment]
Thanks @zlsa - I will submit some changes isolated to canvas.js at first, with local use of jshint only. We can evaluate the configuration settings and decide if it is appropriate to deploy further.

(p.s. I tried jslint as well. It is 'more opinionated' about coding style and it does not appear to be a good fit for the project. That said, I am a novice with both tools so definitely appreciate any other opinions.)
