### ISSUE TITLE
Bug when zooming in using Chrome

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#198]
When one zooms in (not the ingame zoom, but the "Alt" + Mousewheel kind of zoom) everything becomes bigger as it is supposed to, but then on resetting the zoom to 0%, the canvas on which the scope is drawn appears smaller then it usually is, with a border with background only on the bottom and the right hand side.

![untitled-2](https://cloud.githubusercontent.com/assets/12700191/10268008/55512dc0-6aab-11e5-86da-e6307dcf60c4.jpg)

**Comment by glangford** [comment]
Confirmed on Chrome, only when on a retina display. @Maverick283 are you seeing this on a high resolution display?

**Comment by zlsa** [comment]
I'm not seeing this in Chrome 45.0.2454 on Linux, non-Retina. It looks like canvas_resize isn't being called for some reason.

**Comment by glangford** [comment]
More testing - I see it only on Retina on both Chrome and Safari. It's a bug in `canvas_adjust_hidpi()`.

**Comment by glangford** [comment]
Try resizing very small, then big, several times - that seems to be the trigger, not zoom.
