### ISSUE TITLE
Adding Istanbul Atatürk Airport (LTBA)

### ISSUE THREAD

**Issue by gitsalty** [zlsa/atc#206]
This airport sounds very interesting especially since there are plans for a new parallel runway (currently 3 runways). Also one of the heaviest traffic movements in the world. I would also love to pull request and add but I'm new to this.

**Comment by gitsalty** [comment]
Also I created THY, and NAX files also I just created LTBA where am I able to pull request cause I'm not able to.

**Comment by zlsa** [comment]
To open a pull request, you have to fork this repository (the Fork button in the top right), then push to your copy as usual. From your repository, you can then open a pull request back to this one.

**Comment by gitsalty** [comment]
Got it thanks!
