### ISSUE TITLE
Question airports

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#212]
In the airport file: what is the "angle" for in arrivals an why hasn´t the first array one?

  "arrivals": [
    {
      "heading":   180,
      "airlines":  [
        ["ual", 4],
        ["baw", 3],
        ["cessna", 1]
      ],
      "frequency": [4, 6],
      "altitude":  [7000, 9000]
    },
    {
      "angle":     90,
      "heading":   135,
      "airlines":  [
        ["ual", 2],
        ["baw", 5],
        ["cessna", 1]
      ],
      "frequency": [2, 4],
      "altitude":  [6000, 8000]
    },

**Comment by glangford** [comment]
@harp71 For arrivals "radial" and "heading" should be used to describe where the aircraft is created, and what initial heading it has. "angle" is not used in arrivals.
