### ISSUE TITLE
AWSOOOOOMMMMEEEEEE!!!

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#214]
Well the development in the last 6 month made it really fun to play an contribute. Working on a refined EDDM ... coming soon

**Comment by engeplabs** [comment]
Are issues like this one legal? :see_no_evil:

**Comment by harp71** [comment]
Sue me!

**Comment by engeplabs** [comment]
@harp71 I am sorry! :smile: But see: now they won't fix that this game is awesome! :wink:
