### ISSUE TITLE
Terrain, collisions and restricted areas

### ISSUE THREAD

**Issue by culebron** [zlsa/atc#219]
I'd like to see this in the simulator, and here are some tests that I've done. I'm not ready to commit code, but here are some thoughts and sample data and code.

The most interesting airport in terms of terrain, I think is Galeon, Rio de Janeiro (SBGR). It has mountains at north and south, near the coast. Also glideslope to runway 10 is between two hills.

I made some elevation levels rounded to 1000 feet:

![selection_008](https://cloud.githubusercontent.com/assets/119675/10965196/20779b4e-83cd-11e5-8812-7f77af354434.png)

Then simplified geometries, removed too small features and made convex hulls for each feature.

![selection_006](https://cloud.githubusercontent.com/assets/119675/10965213/4715152e-83cd-11e5-93a4-c4f54665a383.png)

Here's a sample of input GeoJSON and resulting terrain files.
https://dl.dropboxusercontent.com/u/6721960/2015/11-05-gig/gig-sample.zip

The idea is to simply check if an aircraft is inside one of the polygons and inside its height range.

To reduce calculations there should be optimizations:
1. The final file is split into levels (305-610m = 1000-2000ft), and we only check one level, in which the aircraft is now. Each level has small number of polygons.
   
   {(0, 305.0): 40,
    (305.2, 610.0): 84,
    (610.2, 915.0): 58,
    (915.2, 1220.0): 28,
    (1220.2, 1525.0): 14,
    (1525.2, 1830.0): 5}
2. Every polygon has bounding box, which we initially check. If ac is out of it, we skip the polygon.
3. Every polygon has a convex hull, which is another polygon, much simpler geometrically (e.g. 300pt polygon reduces to only 13pt)

So, we only have to run the expensive point-in-poly calculation if an aircraft happens to be close to a feature. Though at the lowest level (0-305m) there's one big terrain polygon, which we might need to split to avoid having a big convex hull that matches too many aircrafts.

And finally the biggest optimization is this: calculate ranges to features on current level and track the flown distance to see if the plane may have reached it. If it has flown less than that range, then it just can't be inside that polygon.

Algorithm:
1. When an ac enters some level, we calculate its distance to every polygon and save them as a dictionary.
2. Every turn we substract the flown distance from the saved range for each of them.
3. As soon as one distance becomes 0 or negative, re-calculate the range to that feature again.

(Not sure if it should be calculated for each feature or only if the ac is inside bbox & convex hull. Bbox check is also quite fast, and we avoid the expensive range calculation. Probably the best way is to use bbox and use range when ac is inside bbox, and use convex hull only if the ac has covered the distance, and is inside the bbox.)
## Drawing

No idea right now. Terrain is not usually shown on real ATC screens. It may be added for playability, but also could be just shown as restricted areas, and the polys used only for collision detection.

Any thoughts?

**Comment by glangford** [comment]
Some aspects to consider:
- Terrain is not usually shown on real ATC screens, as you point out
- SIDs and STARs are defined with terrain in mind
- A detailed terrain model would add to the startup time when downloaded

I don't have the charts for SBGR, but I wonder if as a starting point it makes sense to first:
- update SBGR arrivals to use STAR fixes (using KSFO, KLAX, ENGM as examples)
- update departure directions to match SIDs (and add any additional fixes as required)
- evaluate the game play, then perhaps adding any restricted areas
  ?

**Comment by culebron** [comment]
I thought of both restricted areas and SID/STARs. They're not implemented yet, right? I mean you can't just say "callsign use STAR 4"?
- For the sake of pure ATC, they are bigger priority.
  - Now, what should a pilot do if he's directed to restricted area?
  - If a plane flies along a restricted area obrder and is ordered to turn into it? Just check the flight path and say "negative"?
  - What should happen if a plane comes into a restricted area?
- For funnier gameplay (or stupid/drone mode), actually crashing planes is a good joy :)

I'll check how commands work and will try playing with restrictions code.

**Comment by glangford** [comment]
> I thought of both restricted areas and SID/STARs. They're not implemented yet, right? I mean you can't just say "callsign use STAR 4"?

The idea (for now) is that STARs are assigned automatically - this is implemented for some airports, but not all yet. As they come into the control area, they can be held, rerouted, or vectored for arrival.

I will add a SID command to minimize the typing for departures.

**Comment by culebron** [comment]
Here's the approach chart. While in Madrid or Barcelona airport there are big sectors of restricted areas, here there are none except for some for military areas/airports, and mountains Corcovado and Pedra Branca that stick out.
![selection_031](https://cloud.githubusercontent.com/assets/119675/11018252/07e15116-85e3-11e5-992e-e3097ca485b0.png)

**Comment by culebron** [comment]
To start with something rather simple, I created branch restricted-areas in my repo. It can display restricted areas on canvas, but no there's no detection or prevention yet.

The big area in the picture is the entire Moscow city, which is a restricted area (it's officially allowed to fly above 8000m, but this almost never happens).
![selection_017](https://cloud.githubusercontent.com/assets/119675/11084168/d08a3d26-8859-11e5-97d1-9fac02a0a3c7.png)

**Comment by MaicomMR** [comment]
Wow, sounds good, but maybe a more transparent color can be more confortable to play. :+1:

**Comment by glangford** [comment]
Very cool! :zap: :exclamation: 

I don't have time to look at your branch yet, but thinking ahead a little to collision detection - I get the feeling that you might know as much or more about it than I do :wink: , but some thoughts:
- if the regions can be expressed as polygons, there is a very simple approach for 2D point-in-poly hit testing here, which could be combined with an altitude test: http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html
- we probably don't need to model all of the areas; the bottom left circular area for example would probably never be encountered in actual game play (?)

I do agree with @MaicomMR that a more transparent color would be better. Maybe a non white border as well?

**Comment by glangford** [comment]
One additional consideration - we would probably want to perform new collision detection in the projected paths code, which does the flight physics into the future (`canvas_draw_future_track`). So when you select say `n` aircraft on the screen, `60 * n` physics updates are drawn every refresh. So fast hit testing is nice - if only because it doesn't make laptop fans go wild. :hotsprings:

**Comment by culebron** [comment]
@glangford I thought of it, and as I mentioned, there is a simple algorithm that allows skipping all the unnecessary calculations. Just calculate the range (distance between the a/c and the area) and collect the travelled distance every notch. Untill the plane flew that distance, there's no reason to bother.

Also, this range can be calculated to convex hull of area, which reduces the amount for some areas.

**Comment by zlsa** [comment]
I think it's fine to just check once each in-game second.

**Comment by culebron** [comment]
Initial version of restricted areas detection: when there are many aircrafts in area, it tests about one combo per second (aircraft*area combination for point-in-poly and distance to poly).

![selection_040](https://cloud.githubusercontent.com/assets/119675/11162607/00c72b2e-8acc-11e5-98f5-4bf73ad45c76.png)

No indication yet, just raise warning.

**Comment by culebron** [comment]
@zlsa BTW, I can't find the future position in the `aircraft.js` code. It is present only in `canvas.js`, where it creates a `twin` (seach this word there) and runs 60 seconds ahead for it. But this object is not stored, nor available in `aircraft.js`

**Comment by culebron** [comment]
finalized the restricted areas in #240

**Comment by glangford** [comment]
> @zlsa BTW, I can't find the future position in the aircraft.js code. It is present only in canvas.js, where it creates a twin (seach this word there) and runs 60 seconds ahead for it. But this object is not stored, nor available in aircraft.js

That's right - the future position is only implemented in the canvas code in `canvas_draw_future_track` as a clone/twin of an aircraft, with physics run into the future. This was done so that the physics code could be reused without being copied. The future locations are stored and the twin is discarded after the track line is drawn. There was no need to store it at the time.

**Comment by culebron** [comment]
@glangford Ok, then, it needs some work. I had difficulties making position checks rarer than every cycle. Future track should not be calculated that frequently for every aircraft, that's just too expensive, IMO. So we need a caller or an event, to be triggered every second or 2, to listen to it. Right now I need to hack with `updateWarning` and `updatePhysics` function. Would be great if someone took care of this.

**Comment by culebron** [comment]
See #250 with collision detection code.

**Comment by culebron** [comment]
To anyone interested in this, the work on this part is done in #251. I think, restricted areas can be switched to GeoJSON, but for now, restricted areas and terrain are working as suggested.

See http://culebron.github.io/atc/ to test it.

**Comment by culebron** [comment]
This is done :)
