### ISSUE TITLE
[Feature Request] Dynamic Weather Patterns

### ISSUE THREAD

**Issue by space-is-hard** [zlsa/atc#221]
This is a separate request from #68

I'd like to see bands of rain that move slowly across the radar screen that cause the player to lose points (or even lose an aircraft) if they direct an aircraft into medium or heavy storm areas.

Ideally it would look something like [this](https://www.ll.mit.edu/mission/aviation/wxatmintegration/images/udss-slide1.jpg) or [this](http://www.google.com/imgres?imgurl=http://www.ainonline.com/sites/default/files/uploads/skyradard3.jpg&imgrefurl=http://www.ainonline.com/aviation-news/aviation-international-news/2012-06-01/ads-b-weather-traffic-services-available-now-skyradar-receivers&h=526&w=768&tbnid=psFw-XuOyrNmBM:&docid=VWSWSgpOsp56_M&ei=v1I7VoXrFMqRmQGEmYCABQ&tbm=isch&ved=0CGIQMyg7MDtqFQoTCMXGgJur-cgCFcpIJgodhAwAUA), where the medium and heavy storms are denoted as a different color than light or regular rain so that the player knows what they can safely pass through and what to avoid.

One potential issue to overcome is that an aircraft could enter radar range in the middle of a storm, causing them to lose points/lose an aircraft without being able to avoid it. Either incoming aircraft would have to direct themselves away from storms (potentially difficult to implement), or they would have to enter radar range above the storm (assuming the storms have a ceiling) and the player would have to find a clear spot to descend.

**Comment by nielsvdweide** [comment]
I think this will make it way too hard to play this game (as we have to do everything right now... from approach, descends to clearances)

**Comment by space-is-hard** [comment]
It could certainly be a toggleable difficulty setting

**Comment by Maverick283** [comment]
I think this would be an amazing idea! 

As @nielsvdweide pointed out it might be quite difficult, but could be one of the options that have been talked about....

Having different "levels" of bad weather, displayed by different shades of a color (keep in mind the color blind though), where more and more points would be subtracted for each plane flying through sounds good.

**Comment by nielsvdweide** [comment]
After thinking about this, this could actually be pretty cool! But as I pointed out it will be quite hard work if we have to do all bits of air traffic. It would be a good idea to make it an option you can toggle on and off.

**Comment by Maverick283** [comment]
@glangford What do you think? Would be quite a chunk of work, could it be worth it?

**Comment by glangford** [comment]
I definitely like the idea in principle, but agree it would take some work. On the software side of the world we often speak of "T shirt sizing" of features before they are well understood - i.e. is it a small, medium or large in terms of effort. I would call this one a Large. :smile:

**Comment by Maverick283** [comment]
I agree, but i think from the programming side it is somewhat similar if not even almost identically to [#219](https://github.com/zlsa/atc/issues/219), where areas on the canvas give minus points when aircrafts enter this area... Except that weather is moving...

**Comment by glangford** [comment]
@Maverick283 I am with you. #219 is also a Large.

**Comment by harp71** [comment]
Maybe off topic here, but how about starting with changing wind conditions,
e.g. random selection between a number of possible wind directions

2015-11-09 17:20 GMT+01:00 Glenn Langford notifications@github.com:

**Comment by Maverick283** [comment]
@Harp71 Well that would be similar to #169 which I think would be great too! 

But I think we should stick to that idea here, as I believe it can be done hand in hand with #219
 Most of the code should be the same as the principle is the same.  

The programmers need to decide though if this is practical and if  they want to spend the time :)

**Comment by harp71** [comment]
And it should be an option. I don´t know if i want to play with weather
ever.

2015-11-09 18:53 GMT+01:00 Maverick notifications@github.com:

**Comment by erikquinn** [comment]
I think dynamic wind (#68) is the only weather feature that will be added any time remotely soon. One day this can be revisited in more detail, but it's simply too far off at this stage.

Closing.
