### ISSUE TITLE
Render standard instrument departure sequences on the canvas

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#228]
I think most people will not be familiar with standard airport departure schemes, so a rendering on screen is needed. Here is an example of what it might look like for KSFO for example. I am using the departure colour with very little "ink" so it isn't a pain to look at.

![ksfo sids](https://cloud.githubusercontent.com/assets/3035114/11045811/bc3e4f00-86f7-11e5-9540-bc5472700251.png)
#224
#227

**Comment by harp71** [comment]
Nice
Am 09.11.2015 21:41 schrieb "Glenn Langford" notifications@github.com:

**Comment by culebron** [comment]
Looks cool!

**Comment by nielsvdweide** [comment]
Looks very cool! 

The only thing i can think of the screen will get very crowded so you might want to add a toggle for this option? (if possible?)

**Comment by glangford** [comment]
> The only thing i can think of the screen will get very crowded so you might want to add a toggle for this option? (if possible?)

I agree, but I will start with no toggle option to start and let's see if it gets crowded.

**Comment by Maverick283** [comment]
With #227 in mind: only SIDs for the active runway should be displayed...

**Comment by glangford** [comment]
> With #227 in mind: only SIDs for the active runway should be displayed...

It's a fine idea in principle, but not possible at the moment. There is no notion in the game of an "active" runway; aircraft can be taxiing (or not) to one or more runways. Also, the SIDs as currently recorded are not attached to runways.

**Comment by Maverick283** [comment]
I opened a new issue ( #230 ) in which I suggest a active runway feature. I think this might be helpful and fun in the future, but is definitely something that can wait!

**Comment by glangford** [comment]
> I opened a new issue ( #230 ) in which I suggest a active runway feature.

Good thought, it's always good to create an issue for these items that we can't implement right away. Thanks for writing it up @Maverick283 .

**Comment by glangford** [comment]
Will close this now, issue #235 covers show/hide capability.
