### ISSUE TITLE
Active Runway

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#230]
In real life, the ATC determines the active runway(s) based upon the winds current at the airport.

When introducing variable winds, I'd suggest an input where the user can specify the active runway. 

Once the SIDs and so on got going and are all figured out, I believe it'd be an advantage to bind SIDs to runways. Then, whenever the active runway is chosen, only the necessary information could be drawn on the canvas, like the SIDs for the runway.

Also the aircraft could taxi to the active runways when selected by the user, and the user will get in trouble when he forgets officially changing it as the departing traffic would stand on the wrong side.

**Comment by zlsa** [comment]
At the moment, you can instruct an aircraft to `taxi 21L` if so desired.

**Comment by Maverick283** [comment]
Correct, but when not specifying where the aircraft is supposed to taxi to, it will taxi to some runway. This behaviour could be changed so it would taxi to the active runway. This would save a lot of typing.

**Comment by zlsa** [comment]
The active runway is already determined internally by the wind IIRC.

**Comment by Maverick283** [comment]
Yeah.... Usually the ATCs decision ;)

**Comment by erikquinn** [comment]
Covered by #658. Closing.
