### ISSUE TITLE
[Feature Request] SID show/hide button

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#235]
Hi all, I have been thinking about a SID button to enable or disable the dashed lines and names of SID, take a look on example.

SHOW: ![Alt Text](http://i.imgur.com/lqahRpk.png)
HIDE: ![Alt Text](http://i.imgur.com/cEDYdDz.png)

**Comment by zlsa** [comment]
I think it should be one of the buttons in the bottom row. Any ideas for a smaller icon? Maybe just "SID" or maybe an arrow or something?

**Comment by culebron** [comment]
Probably should look like an aircraft taking off icon which is used in airports.
![download](https://cloud.githubusercontent.com/assets/119675/11109593/e9a9a084-8913-11e5-8ea9-d22df5ce09fa.png)

**Comment by MaicomMR** [comment]
Here is a new test:
On bottom bar [test icon 1]: ![Alt Text](http://i.imgur.com/vny3G7Q.png)

icon[icon 1]: ![Alt Text](http://i.imgur.com/KkXH4VX.png)

On bottom bar [test icon 2]: ![Alt Text](http://i.imgur.com/6t1IQfO.png)

icon[icon 2]: ![Alt Text](http://i.imgur.com/liI4AWx.png)

**Comment by glangford** [comment]
The airplane taking off icon looks great @MaicomMR and @culebron - another possibility would be to create a button image for a group of settings (like a gear icon). @tedrek was experimenting with that idea.

That could contain additional things in the future like Variable wind (on/off), and any other options. eg.
https://commons.wikimedia.org/wiki/Category:Black_gear_icons

I like the look of the airplane taking off the best, but I'm not sure which is better long term.

**Comment by culebron** [comment]
If you ask my opinion, I would put this button on the left, and next to it I'd put all actions/switches that are related to ATC activities, and may be needed often. I guess ATC may quite often want to switch between clean view and "cluttered".

What's important is that these switches should be easy to switch back and forth without irreversible or expensive consequences. (E.g. change airport is irreversible.) STARs will come too, and should also be near SID toggle.

Other buttons are meta-game functions (change airport), actions that don't happen often but still need to be visible and easy accessible: multiple airports are what attracts a newcomer.

**Comment by culebron** [comment]
In #240 I added both buttons to toggle SIDs and restricted areas. Check that out :) Open that branch and see how it works. The canvas are redrawn not immediately, and this gives it a special analog device feeling. :)

![selection_046](https://cloud.githubusercontent.com/assets/119675/11166237/a71b2a80-8b4d-11e5-977d-afeae65849a3.png)
![selection_047](https://cloud.githubusercontent.com/assets/119675/11166238/aa709b84-8b4d-11e5-9dd5-eb16d5c8c8d3.png)
![selection_048](https://cloud.githubusercontent.com/assets/119675/11166240/abd9f72c-8b4d-11e5-8f5a-7ee73a3912dc.png)

**Comment by culebron** [comment]
This can be closed now.
