### ISSUE TITLE
Discussing playability priorities

### ISSUE THREAD

**Issue by culebron** [zlsa/atc#239]
Dear fellow developers, I see there are discussions on what improvements to do. Here are my 2 cents on this. **TL/DR:** features that should be developed first are those that improve playability and sharing. Details like true airspeed, aircraft modelling or auto-intercept runways, are good to have, but don't improve enjoyment notably for a non-expert.

Suggestions:
- better approaches
- save the state in browser local storage (json.stringify aircrafts every 5 seconds) and allow resuming play after return.
- share saved data (I guess, get the saved state from local storage and encode in a URL over bit.ly)
- missions: e.g. handle approaches over half an hour. Infinite amount feels futile to play against.
  - share mission results

**Comment by Maverick283** [comment]
I do miss a mission mode... There a multiple possible scenarios I can think off right now, like a big amount of aircrafts due to the closing of another airport, or a air force one inbound with all its escort planes in formation and so on....

**Comment by erikquinn** [comment]
> better approaches

Covered by #59.

> save the state in browser local storage (json.stringify aircrafts every 5 seconds) and allow resuming play after return.

Covered by #283.

> share saved data (I guess, get the saved state from local storage and encode in a URL over bit.ly)

Added to #283.

> missions: e.g. handle approaches over half an hour. Infinite amount feels futile to play against.

Covered by #306.

> share mission results

Added to #306.

---

Closing.
