### ISSUE TITLE
Add ability to tab thru plates, easing keyboard-only play

### ISSUE THREAD

**Issue by ahensley** [zlsa/atc#24]
Excellent, excellent work! I've long wanted a better alternative to ATC games out there.

One thing they all seem to lack is keyboard-only friendly controls. Yes, you can type out the callsign, and the highlighting is very nice, but I feel a nice option would be to allow users to tab through the aircraft on the approach/departure plates. Possibly even highlight the nameplate on the radar to match, if visible.

**Comment by garcg** [comment]
I've just created a pull request for this: https://github.com/zlsa/atc/pull/25

**Comment by zlsa** [comment]
Fixed with #25. Thanks @garcg.
