### ISSUE TITLE
Wiki expansion

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#255]
This program is starting to get bigger and bigger, with more and more functions that are being added by more and more people.

The wiki only covers a short explanation of the functions, but doesn't explain in detail why certain things happen. 

A more detailed wiki will not only help developers, but especially those who do not know much about programming to understand certain functions and thus better contribute to the project.

I was thinking about a wiki page for example for the arrival pattern, where one can read about the (cool) timing that is going on in the background. Most users probably don't even know that planes do not just come in randomly.

Once the wiki is expanded, a link to it should be provided from the UI, and it should be kept up to date.

**Comment by glangford** [comment]
I updated the wiki with descriptions of the new commands for now, but I agree that additional pages would be helpful also.
