### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by garcg** [zlsa/atc#26]
I've noticed that the font family defined in the css is [monoOne](https://github.com/madmalik/monoOne), but is neither included in the sources or imported from anywhere. So it fallbacks to the default monospace unless that font is installed in the user's computer, which is unlikely.

This is perhaps one of the reasons for the complains about the text being difficult to read  (in the HN thread, for example). Here is a comparison between the default in my browser (top picture) and with the correct font installed (bottom picture).

![atcfont](https://cloud.githubusercontent.com/assets/4009153/5435065/f66ce032-8456-11e4-9304-05e6ef54636b.png)

In my screen makes quite a difference.

**Comment by zlsa** [comment]
I'll import with `@font-face`.
