### ISSUE TITLE
Another Reality thing: Approach clearances 

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#262]
In this game, whenever a plane gets close to the localizer it is being cleared to land (BAW001 L 28L).

In reality, a plane is cleared to fly the approach, and then later cleared to land.
"Speedbird 001, [distance]nm out of [initial approach fix], fly [heading] until you intercept the localizer for runway [runway], cleared for the [ILS/VOR/RNAV etc.] Approach [runway]". 
Then the landing clearance would be:
"Speedbird 001, wind [degrees],[knots], [runway] cleared to land." 

Both of those are off the top of my head and might need some double checking...

What I'm on about though is that we simply drop one (rather important) clearance and should think about introducing it.

**Comment by culebron** [comment]
I think this is a work for two ATC, approach and tower. If you play this alone, it's just too big a workload.

On landings, I would think of planes themselves going around when there is another plane on the runway.

**Comment by nielsvdweide** [comment]
@Maverick283 You are right about clearing the approach as well as the clearance to land, but as a one man ATC operation it is just too much information and adds a too high workload. Clearance for the approach is normally given by the Approach controller and when the airplane is on it's final track to land they will be switched to Tower. They will then give them the landing clearance! 

No point in adding one of them. I agree it will be more realistic but thing will just get too complicated

**Comment by Maverick283** [comment]
Okay, we got this covered now I guess xD.

I agree that it increases workload, and it is probably not worth the added reality...

Can I close this issue myself and just don't know how or does @zlsa have to do this?

**Comment by glangford** [comment]
You should be able to close any issue that you opened; look at the bottom here for a button called 'close issue' (or something like that):

https://github.com/zlsa/atc/issues/262
