### ISSUE TITLE
V-Speed status during takeoff

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#268]
In #19 there was a suggestion to show the V-Speed status during takeoff.

I think it would be sufficient to show the V1 Speed status only, as in above or below V1. 

This can be done either by coloring the speed display, or by replacing the speed indication by (e.g.) "<v1".

This would then also have to be explained in the tutorial. 

V Speeds in reality are calculated before each flight, using all kinds of variables (weight, runway length, altitude, temperature, humidity, etc....) . This is for simulation purposes not practical. I think something like 0,8*takeoffspeed would be sufficient as calculation (I believe this was suggested in #19 as well).

Any thoughts on this?

**Comment by culebron** [comment]
What does this give to the controller? I would rather implement a realistic v2 and runway distances, as well as pilots checking if rwy length is sufficient.

**Comment by Maverick283** [comment]
It would give a reason why a takeoff may not be aborted. 

That sounds like a good idea, I thought runway length this was already taken care of. In terms of realistic V-Speeds.. I guess a single calculation would bring a rough estimate that is close enough to reality to give a somewhat realistic value:

V2 = takeoffLengthFactor \* takeoffSpeed \* v2Factor 

No further variables would need to be introduced...

**Comment by culebron** [comment]
Aborting takeoffs is reasonable, I'd be happy to see this here. Regarding a display, I think an ATC does not really need it. It matters 15 seconds every several minutes. If you need, just issue a command, and pilots will reply if they can or can't.

I did try increasing disances, and B747 would crash in the end of short runways, but if runway length becomes an issue, we need to run exact checks like projected plane for clearances.

**Comment by erikquinn** [comment]
This seems like a very _minor_ improvement that would not be noticeable to the user nor particularly realistic as a simulation from the perspective of a controller. It can be reopened and kept on the backlog if desired, but I'll close it now to keep focus on other tasks.
