### ISSUE TITLE
Tutorial body text errors when no planes

### ISSUE THREAD

**Issue by voska** [zlsa/atc#27]
The body text of the tutorial won't change when you click next, when there are no planes on the screen
`Uncaught TypeError: Cannot read property 'getCallsign' of undefined`

**Comment by Diastro** [comment]
Out of curiosity when did you hit that (when starting a new game, when getting every plane to land and there wasn't any new plane, playing with a new airport without any airlines assigned to it)?

I'm trying to reproduce this but I can't seem to figure out a way without doing it using the code.

**Comment by voska** [comment]
After landing every plane.

**Comment by engeplabs** [comment]
can be reproduced by aircraft_remove_all()

**Comment by engeplabs** [comment]
@voska What behaviour would you expect when no planes are available and you open the tutorial?
I thought of adding a plane ready for departure at the gates so you can use this one...
