### ISSUE TITLE
Zoom in key

### ISSUE THREAD

**Issue by kaitsu71** [zlsa/atc#275]
Looks like I can zoom out with minus key but plus key does not seem to zoom in. Is there a key for that? Or is there some other way to do zooming without a mouse wheel?

**Comment by nielsvdweide** [comment]
I think Shift + = gives you a zoom in!

**Comment by kaitsu71** [comment]
Doesn't seem to work with Finnish/Swedish keyboard... The reason I ask this is because I am an a business trip and forgot mouse home :)

**Comment by erikquinn** [comment]
Covered by the newer issue, #336.
