### ISSUE TITLE
"Speed" shortcut doesn't appear to work

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#282]
I used to use the speed shortcut all the time. Now when I try it it says "not understand, say again. Speed 200 works, s 200 does not.

**Comment by Fechulo** [comment]
The shortcut for speed was recently changed for 'sp'. You can see the other modifications to the shortcuts and commands here: https://github.com/culebron/atc/commit/bf54373891d7224dd73d16d13ba85e9f4eaf0870

**Comment by avdg** [comment]
How are these shortcuts determined? I can't see the change in that diff.

**Comment by avdg** [comment]
I can confirm the sp command working though, so no debate on that part :-)

**Comment by Maverick283** [comment]
Will update the Wiki right away...

**Comment by Fechulo** [comment]
```
speed: {
  func: 'runSpeed',
  synonyms: ['slow', 'sp']},
```

the word before the colon  is the name of the command, in this case: "speed". The shortcuts are the words inside of synonyms, in this case: "slow" and "sp". This applies to all other commands

**Comment by avdg** [comment]
ah yeah, I've overlooked that apparently even after extensive looking

**Comment by sixeyeco** [comment]
thanks. thanks for all the great effort!
