### ISSUE TITLE
Separation Marker Bug

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#288]
For the last few days I've been trying new things and while testing them, I noticed this. When the aircraft is established on the ILS, the separation marker is turned around. Does anyone know what could be wrong and where the code is?
Thanks!
![bug](https://cloud.githubusercontent.com/assets/13125311/11910997/c9edb81c-a5ff-11e5-954f-131b8b9b938b.PNG)

**Comment by avdg** [comment]
It involves this code https://github.com/zlsa/atc/blob/e4e21a16776ae84aabd8245a28735280639d5f94/assets/scripts/canvas.js#L310

**Comment by Fechulo** [comment]
Thanks! I was missing the + Math.PI, that fixed it.
    var angle = rwy.getAngle(aircraft.requested.runway) + Math.PI;
