### ISSUE TITLE
Location for documentation

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#293]
Hi Folks,

The wiki and the code continue to be out of sync with each other.  One of the challenges I've identified is the documentation isn't part of the pull request and therefore I'm not in a position to keep the wiki and deployed code in tight sync with each other.  This leads to either writing the wiki update and it being ahead of the deployed code or (much more commonly) waiting until after the pull request has been merged and then maybe remembering to update the wiki.

My proposal is to include the technical reference documentation within the main source code.  This would replace the majority of the wiki as it stands now and appropriate links can be placed.  It also means code updates and documentation updates can happen at the same time.

I'm thinking of specifically using jekyll and markdown to get the minimum necessary for a set of web pages under something like zlsa.github.io/atc/documentation/

@zlsa, @glangford, @culebron, and other's, any thoughts/concerns?

**Comment by glangford** [comment]
I think this is a great idea. I haven't used jekyll directly before, but since it is used in Github Pages we know it works.  :)

**Comment by zlsa** [comment]
Sounds great, but I've never used Jekyll so I'm not a good judge of that. @tedrek, do you want direct push access?

**Comment by tedrek** [comment]
Alright :smile:, I'll look into it further and create a pull request.

@zlsa, I don't need push access for this (I or anybody else can test on their own account) which is why I'm proposing this mechanism.  That being said I wouldn't mind push access if you wanted to give it to me in general.  I would use it for pushing bug fixes or merging other peoples work only, not for merging my features as I like having at least one other person think it's a good idea.  The one other place I'd being willing to help is maintaining issues, specifically there are a number which can be closed now.

**Comment by zlsa** [comment]
@tedrek: done.

If @glangford or any other major contributor wants push access too, just ping me.

**Comment by Maverick283** [comment]
I'm definitely not a major contributor to the source code, actually never have pushed anything to this repository. 

I'd be happy to be able to maintain the issues list as well though, as there are many that can be merged, closed or brought back to attention. 

Back to the topic of this issue though:
The wiki as of now looks more like a user wiki, not a programmers wiki. I think it is okay to keep it that way, and welcome the idea of including a wiki for the contributors in the code. As suggested in #255 the wiki in my opinion should be a place for a user to read up on functions and way stuff works, maybe even explain some basic aeronautical procedures.

**Comment by culebron** [comment]
I support the idea. But first we need a doc on how to make this doc on your own. :)

**Comment by tedrek** [comment]
@culebron see [the documentation](http://zlsa.github.io/atc/documentation/README.html).  If it's not clear open an issue (or better yet, make a pull request :wink:).  It should be pretty straightforward but I made it quickly so I'm sure it can be improved.

@Maverick283, I agree the wiki makes more sense as a users's reference.  It should link to the documentation where appropriate.  For example the documentation on airport format is tied quite closely to the code so shouldn't be in the user's wiki.  Similiarly, the actual values for scoring shouldn't be in the wiki but an overview of how scoring works makes sense with a link to any relevant documentation.

@zlsa, thanks for the access :smile:
