### ISSUE TITLE
Points go down almost immediately after starting a new game

### ISSUE THREAD

**Issue by asherdavidson** [zlsa/atc#30]
My points almost always drop to -20 before I've even had a chance to do anything.

Could this be caused by planes that spawn on the edge of the map and then fly off before they can be seen?

**Comment by zlsa** [comment]
If aircraft are flying off the edge of the map, they'll print out "BAW123 leaving radar coverage" or something similar in the lower-left corner. I'm working on logging more score messages; right now it's a little sparse and it's hard to tell why you lost score. (If you want to, you can open a console and type in `prop.game.score` to see what happened.)

**Comment by asherdavidson** [comment]
Yup, I've got 2 failed arrivals. Perhaps you can set the entry angle to be within x degrees of its angle to the airport. That way this can't happen.

**Comment by zlsa** [comment]
I actually have a really arcane arrival format that's very flexible, but if nobody understands it then it may be a good idea to rewrite it.

The current format conceptually works like this:

Draw a circle around the airport, slightly smaller than the smallest edge of the display. This is so the circle is entirely visible.

Take the `direction` angle; draw a dot on the circle at that angle.

Take the `heading` angle and extend a line out in that direction twice as far as the largest edge of the display; the aircraft starts here.

The goal was that you can create scalable semi-realistic layouts (i.e. small cessnas always come from the southwest and fly towards the east), but it had lots of flaws and didn't work well.

**Comment by psycho202** [comment]
A large part for understanding these things is documentation :)
If possible, it would be nice to have a little document explaining the structure of all different json files, like airport, airlines, aircraft, ...

**Comment by zlsa** [comment]
I'm working on it...

Remember, this was just a side project that exploded yesterday; nothing has been documented and it's been so long since I wrote it that I don't remember much either...

**Comment by asherdavidson** [comment]
It might just be easier to have them start at a random distance off the display (so we can't see them spawn), and then you could say the angle is a random number between +-20 of the direct angle to the airport.

**Comment by psycho202** [comment]
I completely understand zlsa =)

**Comment by sixeyeco** [comment]
Just FYI: I also had a failed arrival at the start of a new game. 

prop.game.score
Object {arrival: 0, departure: 0, windy_landing: 0, windy_takeoff: 0, failed_arrival: 1…}

**Comment by Diastro** [comment]
And you can consistently repro this?

The only thing I could see is a failed arrival (see game.js:55 | score -=
prop.game.score.failed_arrival \* 20;). As to why this is happenning im not
sure..

On Sun, Mar 1, 2015 at 5:20 PM, Chris notifications@github.com wrote:

> I'm not sure if this is related (I'm still trying to figure out how to
> view the prop.game.score console thingy).
> 
> I just started a game and before I could issue my first command my score
> went to -20. Any ideas why this happened?
> 
> [image: off_to_a_bad_start]
> https://cloud.githubusercontent.com/assets/179496/6433218/eda1b330-c01d-11e4-884d-db6dac7f4edb.gif
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zlsa/atc/issues/30#issuecomment-76634737.

## 

_David Albertson_
_Senateur du comité étudiant en Génie logiciel_
_Administrateur du STEP, Serveurs télématiques_
_École Polytechnique de Montréal_

**Comment by sixeyeco** [comment]
@Diastro: Nope. Since it occurred at the very start of the game (prior to making any inputs) I can't imagine how I could repro it. In fact, I can't even see the failed arrival. Can you tell (from the screenshot) which craft failed to arrive?

Anyway, I'd be happy to help in any way I can.

[Apparently I deleted the screenshot from my original reply, so I'll repost it here] 
![off_to_a_bad_start](https://cloud.githubusercontent.com/assets/179496/6470147/6b291536-c196-11e4-98f3-92ec9a0db3ed.gif)
