### ISSUE TITLE
Implement conflict refinements

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#301]
PR #294 had a number of items discussed as improvements to the existing conflict code.  This is a tracking issue so the results don't get lost.

Items to be implemented
- [x] Improved parallel approach separation (see also #261)
- [x] Passing/Diverging separation
- [x] 1 minute departure grace period to establish diverging separation.
- [ ] Handling of conflicts between intersecting runways
- [ ] Longitudinal conflict rules for same runway

**Comment by erikquinn** [comment]
Remaining two would be addressed by #426.
