### ISSUE TITLE
Odd Callsign

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#310]
![image](https://cloud.githubusercontent.com/assets/5103735/12066610/a5c6b7d2-afb8-11e5-9cd4-766c3a7d6a9e.png)

Callsign during a run at KSFO was "FASTGA561EZ"... should just be coming up as "N561EZ". Seems like maybe "FASTGA" was entered into an incorrect property in fastga.json, or the wrong property is being looked up in airlines.js??... I didn't really look, but wanted to throw this up here so it doesn't get forgotten about.

Edit: type Embraer 135

**Comment by tedrek** [comment]
I had a brain fart when parsing airlines.  Should be fixed now.  Thanks for the report :smile:
