### ISSUE TITLE
[Feature Request] Variable wind

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#325]
It would add some realism if the wind could vary a bit. Not in the sense of necessitating a runway change necessarily, just that it has shifts and swells of direction and speed. I'm not sure how this is best implemented... what about based on a few levels of Math.random() values, like this:
- Net change from 0h0m->1h0m:   _[(Math.random() = 0.8513) x 2 - 1 = **+0.7026**] x 18kts = **+13kt**_
- Net change from 0h0m->0h30m:   _[(Math.random() = 0.6912) x 2 - 1 = **+0.3824**] x 9kts = **+3kt**_
- Net change from 0h0m->0h10m:   _[(Math.random() = 0.2860) x 2 - 1 = **-0.4280**] x 3kts = **-1kt**_
- Wind @ (t): uhhhhhhhhhhhhhhhh???? 

This way, the changes would be random, but with a clear overarching trend. Somebody more well-versed may have a more intelligent solution, utilizing some of the functions from util.js that I still can't quite figure out what they do. If so, bring on the suggestions!

**Comment by erikquinn** [comment]
WHOOPS this is a duplicate of _multiple_ other issues already reported. Sorry! Closing as duplicate, and going to one of the others to pick up the topic again.

**Comment by harp71** [comment]
@erikquinn  One comment non the less it´s closed: I used to play ATC at http://www.atc-sim.com/. They have variable winds. All it did for me was that i hit F5 to reload the page at the beginning of the game, until i had got suitable wind-directions for my runways :)
What i was thinking about was: Airports don´t have real random winds, in fact they are often build with that in mind location-wise. They mostly have slight variances in direction and strength. 
Why not handle it like this in the airports json:

``` javascript
  "wind": {
    "angle": [[250, 280], [70, 105]],
    "speed": [5, 20] 
  },
```

So winds between 5 and 20 knots from 250 to 280 degrees OR 70 to 105 degrees

**Comment by erikquinn** [comment]
@harp71 yeah something like that is what i'm looking for. I wouldn't want "random" winds, but figured that random() could be used to induce "slight variances in direction and strength" that would be different each time you played. What you've written for the airport json is ideal, but for me the question is how to implement the logic that actually sets the wind based on those figures; I can't really come up with a simple way to do it.

PS Let's move this convo to #68. I'm piggybacking my comments onto that issue instead.
