### ISSUE TITLE
How do I select different airports within the sim?

### ISSUE THREAD

**Issue by montypython112** [zlsa/atc#329]
I did it once, but now I seem stuck with KJFK and there doesn't seem to be anything I can do about it.

**Comment by erikquinn** [comment]
![image](https://cloud.githubusercontent.com/assets/5103735/12189484/27bf465e-b58c-11e5-8ea5-913ae0524011.png)
@montypython112 You should just be able to click the little switchy-looking button and this dialog will appear where you can scroll and select the airport you want. Is that not working?

**Comment by montypython112** [comment]
It is not, it worked fine earlier, but now I'm getting no response from it

**Comment by erikquinn** [comment]
Was it working earlier today?

**Comment by montypython112** [comment]
Just reloaded the page again and it seems to work now, weird.
