### ISSUE TITLE
Scroll recent commands

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#341]
During game play I repeat a few commands over and over. For instance, at SFO I issue 
<h3><b><i>c 3 f rokme nepic</b></i></h3> to all craft arriving from both the north and the south. This accounts for a high percentage of all traffic. All departing aircraft are given the same speed and altitude. 

Typos of even a single character in the command doubles the time spent issuing these commands. Typing commands is decidedly slower and less accurate than speaking. As such, I suggest that an accommodation be considered. 

Currently, the up and down arrows appear to scroll through aircraft, a marginal benefit. My suggestion would be to map the arrow keys to scroll through recent commands. This would allow players to approach the efficiency of issuing voice commands (an added benefit would be increased enjoyment of the game for slow typers).

**Comment by Fechulo** [comment]
I see what you mean. What I do, is I keep a text document with all the commands that I need for an airport, but I think that a scroll through the previous commands would be much better

**Comment by erikquinn** [comment]
I second this as well. I would much prefer to recall commands than recall aircraft callsigns.

**Comment by tedrek** [comment]
Makes sense to me, :+1:

**Comment by sixeyeco** [comment]
I can't offer to help write code, because well, uhh...I don't know how to write code. :)

But I'd be happy to throw some paragraphs, art and tutorial video together to help with documentation.

<h2>Commands</h2>

Although the tutorial inside the game gives a large amount of information, if you find remembering the commands too complicated, here's a reference. 

<i>Tip: You can combine multiple commands. For example, instead of issuing these three separate commands you can issue a single, longer command. All of these commands are valid: 

> <b>BAW231</b> turn 90
> <b>BAW231</b> climb 20
> <b>BAW231</b> slow 180
> <b>BAW231</b> turn 90 climb 20 slow 180

<i>Note: When issuing several commands at once, a typo will invalidate that portion of the command. For instance, let's assume that you are using the example above but made a typo:</i>

> <i><b>BAW231</b> turn 90 climb 20 </i><b>sloe</b><i> 180</i>

<i>Your flight will turn to 90° and climb to 2,000 feet. But it will not slow to 180 kts. There will be confirmation of the first two correctly formatted commands but the last command (the one that contains the typo) will not be acknowledged. There is no warning displayed that the faulty command was not received. As such, it is good practice to frequently scan the flight strip rack as well as the radar to look for anomalies.</i>

<i>Another time-saving tip is that the up and down arrow keys will scroll through previously used commands. Select a flight and press the up arrow to use the last command. Pressing the up arrow key twice will display the second to last command, and so on. Pressing the down arrow key will display the very first command that you issued during the current session. Similarly, pressing the down arrow key twice will display the second command that you issued, and so on. 

For example, say that at the beginning of the game you issue this command: </i>

![command-line](https://cloud.githubusercontent.com/assets/179496/12469111/f0ea7ec0-bf9d-11e5-98d7-02151bf881fc.gif)

<i>This is a very generic command that could easily be given to every craft that is waiting to taxi. Now, whenever you see a craft waiting to taxi simply select the flight strip (or the craft itself) and press the down arrow key once and then press <b>ENTER</b>. <i>

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
