### ISSUE TITLE
c 9 means climb to 9k yet c 10 means climb to 1k.

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#342]
I could have sworn that I used c 10 to direct departing craft to 10k. Now it only gets them to 1k. If c 9 means 9k why wouldn't c 10 send them to 10k? 

I would debate that 10 as 10k would be more useful than 10 as 1k. If I ever need a craft to descend to 1k I'd be happy to type out 1000. Why the change? Or is this as it should be?

**Comment by erikquinn** [comment]
In all instances of air traffic control and most instances of flight, altitudes are denoted in hundreds of feet, eg 180=18,000="Flight Level 180". Thus, altitude "10" or "010" would be assumed to be 1,000' msl.

I was the one who added the option to enter altitudes in hundreds of feet, but left the legacy format of x1,000 in place for single-digit entries only. eg "c 3"=3,000 , "c 30"=3,000 , "c 100"=10,000 , "c 10"=1,000.

To be honest, I'd prefer to make altitudes ONLY enterable in hundreds of feet (particularly when we add airports whose airspace extends into the flight levels (like D01, Denver TRACON), instead of allowing a hybrid between entering by hundreds-of-ft OR thousands-of-feet. But that is a somewhat significant design decision that should be discussed amongst everyone, so I didn't do so, but maybe this is the time to talk about it... Thoughts on going exclusively to hundreds-of-feet aka flight levels?

**Comment by sixeyeco** [comment]
As I know nothing about flying or directing planes I can't speak as to realism. Whatever is decided is fine by me, but perhaps simply updating the Wiki would do the trick. I am actively promoting the game and this "issue" is not documented.   

![atc-climb](https://cloud.githubusercontent.com/assets/179496/12368809/eee67fdc-bba3-11e5-95ce-f25938a1fff5.png)

Perhaps it could say:

> Information - This command tells the specified plane the altitude, in feet, it should travel to. For example; you can type c 100 to climb to 10,000 feet and d 40 to descend to 4,000 feet. Airplanes will not descend below 1000 feet (unless locked on ILS) or above 10000.  
> <i>Note: the legacy shortcuts for altitudes 1,000 through 9,000 inclusive (c 1 and c 9 respectively) are still valid.</i>

Awesome game Jon, and to all who contribute. I just can't say enough how impressed I am with all the progress.

**Comment by erikquinn** [comment]
Okay, if you aren't bothered by that concept, I'd make a motion to move to expressing all altitudes in hundreds of feet, or written all the way out...

Do any of @tedrek, @zlsa, @harp71, @maverick283, @culebron, or others have thoughts either for or against this? Its just that it would change the way the user enters commands at a fundamental level, and I want to be sure it is agreeable to all. Also it would obviously come with an update to the tutorial and wiki.

**Comment by tedrek** [comment]
Sounds reasonable to me.  Would you want to differentiate between altitude and flight level? (If/when we ever go that high)

**Comment by erikquinn** [comment]
@tedrek that's just it- we wouldn't have to... Entering "180" would be interpreted as 18,000, and we could just add an `if(alt>=airport.startFL) readback = "flight level " + radio_spellOut(alt.substr(0,3));` to the part where the readback is generated for the ui_log.

and `airport.startFL` is optional, but the flight levels start at different altitudes in different countries. FAA uses 18,000msl as the start.

`radio_spellOut()` is similar to the other radio functions, just that it will pronounce a string phonetically in single digits. It isn't in the zlsa repo yet.

So it's naturally set up for that, and congruent with standard practice.

**Comment by Maverick283** [comment]
I was surprised as well when all my departing aircraft all of the sudden stopped climbing at 1.000 feet, and it took me a couple departures to make sure I entered it as I always did until if figured out that the altitude is no to be entered in FL. I welcomed this as it always bugged me to enter it in thousands of feet. 
As a newcomer to aviation I used to have a hard time transforming feet into flight level, as it is just common to take away 3 "0"s rather then two. But once you get used to it it males a lot more sense... 

I think it is a good step towards realism, just needs to be made clear to the user!

**Comment by tedrek** [comment]
@erikquinn, sounds good to me.

**Comment by erikquinn** [comment]
word.

4 out of 4 in favor sounds good enough to me, unless somebody chimes in to the contrary in the next day or two. I'll whip together those changes, as well as the appropriate updates to the tutorial and wiki, and then make a pull request.

^Done. See #344.

**Comment by zlsa** [comment]
I agree with this. The altitude parsing was really bad at first because I tried too hard to limit keystrokes.
