### ISSUE TITLE
Departures should not have any speed restrictions

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#343]
Whenever an aircraft takes off, it goes some odd and very slow speed. It should default to max speed its capable of (except no greater than 250kias while <10k ft).

In reality, it should default to Vy (speed for best rate of climb), buuuuut until we get better performance data for dynamic climb rates, there's no point trying to get that fancy. 

Using the first strategy, this should be a quick fix.

**Comment by harp71** [comment]
As shown in #339 the climb/descend and acceleration/deceleration parameters are still not near reality,  part because the airfcraft data are wrong, part because (i think) the math is wrong somehow. last part (again, i think) does math to linear and not like an aircraft. It should climb faster and accelerate slower (in a nutshell).

The 250 rule however ... somebody here said "it´s the law" ... well, it´s the most broken law in the world then, for departures anyway. There´s an often used ATC phrase "high-speed approved".

**Comment by erikquinn** [comment]
@harp71 I thought at first the math was wrong too... But simply putting an a/c in level flight, climbing/descending a few thousand feet and timing it to find the average number of feet per minute is actually dead-on with the values in that aircraft's json. So I think the math is right, and the sluggish appearance is just from the `aircraft.rate.climb` and `aircraft.rate.descend` values being much too low for low-altitude performance to look even remotely realistic.

As a patch, maybe we could set all the climb/descent rates to sea level values (super high) and add a logarithmic decrease in rate between sea level and the aircraft service ceiling. Then it would climb like 3500 or whatever at sea level, 2600fpm at 3,000ft, 1800fpm at 15,000, 400fpm at FL370, etc. Just spitballing here.

And as for the 10k/250 rule, I'm unfamiliar with it being overridden by ATC almost ever, except in unique emergencies like onboard smoke/fire. But that's FAA anyway; if it truly is as common as you say in some European countries, maybe it's worth creating another property for each aircraft json to make it overrulable in some places, but airports in the US should remain 250kias without any way for the user to overrule it because it wouldn't be done at a place like KSFO. If that's common with eurocontrol though, then heck yeah I say we add it!

**Comment by Maverick283** [comment]
I can only agree that I've never heard "no speed restrictions", neither in the US nor in Germany... 
It's common on platforms like VATSIM or IVAO, because the controllers there get bored and want some action or couldn't manage the traffic properly, but in real life, I've never heard it...

**Comment by erikquinn** [comment]
Well its definitely allowed, and wouldn't surprise me in the least if it was more commonplace somewhere else, I'm just not sure if or where, and if we have airports from those countries that may use it more often

**Comment by tedrek** [comment]
@harp71, @erikquinn, The math as implemented in the game is right for what is modeled.  But the modeled behaviour is, as you have observed, not very realistic so wrong in the sense of matching reality.

I'm all for removing the speed restriction for departures, the simple thing to do would be set speed to 300 when generating the departure.  That would mean target speed is 300KIAS, which is close enough for jets climbing/descending under 20,000 feet (for a quick patch at least).  There is a check for 10k/250KIAS which will keep the speed under control.

If there were going to be exceptions to the 10k/250KIAS rule, they should be by a property of the airport as opposed to the aircraft.  I have been thinking it would make sense at some point to specify that an airport is FAA as opposed to something else.

**Comment by harp71** [comment]
@erikquinn high-speed approved is common for departures

**Comment by erikquinn** [comment]
@harp71 Sounds good, I'll take your word for it. Created #366 for tracking that feature request separately from this one.
