### ISSUE TITLE
Warning & Separation Circles misleading

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#346]
The white warning circles and red separation circles are misleading... They have a radius of 2.5nm, and the separation required is 3.0nm, resulting in a/c generating sep losses when they are still outside of the circle. 

I recommend that we:
- Change the radius from 2.5nm to 3nm
- dim the "warning" from the bright white to barely visible white

Example:
![image](https://cloud.githubusercontent.com/assets/5103735/12449403/08a0f3d0-bf4b-11e5-871a-c5baf330f88e.png)

**Comment by sixeyeco** [comment]
@erikquinn 
I've noticed this too, I just assumed it was a very string warning ;)

On a similar topic, would it be possible to have a faint circle surround any craft whenever it is selected? This would be a big help when I merge two lines of multiple craft for approach by providing further information to set their heading and speed to space them correctly.

**Comment by erikquinn** [comment]
@sixeyeco that's possible, sure, I personally don't think I would like that though. I find that the 5nm range rings provide more than enough information to get a sense of where you're at separation-wise.

**Comment by sixeyeco** [comment]
I see what you mean.
