### ISSUE TITLE
Planes collide outside my airspace due to different speeds

### ISSUE THREAD

**Issue by mxab1** [zlsa/atc#351]
At KSFO, I frequently have two airplanes crash outside my reach, because they seem to spawn at the same altitude with different speeds (see screenshot). They get closer until the separation warnings appear and then collide, and points are deducted. It appears to happen if I slow down a single airplane in a block of arrivals in order to get some space ahead, but I can't tell for sure.

I'm playing the latest version without any modifications.

![image](https://cloud.githubusercontent.com/assets/7746613/12479572/42ce85c6-c03c-11e5-8d49-6a617b290109.png)

**Comment by erikquinn** [comment]
Hmmm, that's not good. For this reason, jets and turboprop/piston aircraft are usually delivered to approach controls at different altitudes... Maybe that's the best way to address this:

Jets : 10,000' 250kts
Turboprop/Piston: 7,000' <=210kts

**Comment by tedrek** [comment]
What's happening here is that the SFO arrival at radial 90 spawns both turbojet and piston aircraft, the piston aircraft have a lower top speed and naturally fly slower.  However the stock arrival should only spawn one aircraft every 10 minutes, it's clearly not doing so here.  @mxab1, are you playing with a higher 'rate' setting than default?

The simple fix is to not spawn piston aircraft in that arrival location.  If the rate command is triggering this behaviour a cap for the rate command may also be advisable so airports can be tested within known limits.

**Comment by mxab1** [comment]
@tedrek, I actually played with a lower rate setting, iirc 0.5 or lower. But I also noticed that when going lower than 0.5 to, say, 0.2, the influx of planes does not seem to reduce accordingly. So maybe there's a problem.
