### ISSUE TITLE
"waiting" on the world to change

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#353]
![image](https://cloud.githubusercontent.com/assets/5103735/12492539/aeade28e-c04e-11e5-987e-8b9106aa87c1.png)

Not to draw parallels to John Mayer with my title :stuck_out_tongue:... but _what on earth_ are all these departures waiting for? Most in the screenshot were taxiied as much as ten minutes ago, and they just never seem to pop up at the runway ready to go.

Getting that taxi time reduced would also help with the strip organization issues brought up in #340.

**Comment by sixeyeco** [comment]
I run into this at least once per session. I restate the entire command to taxi (alt, speed, runway) and they appear. They won't jump the line (they queue up as if they only just received clearance) but it gets the job done. 

I've always assumed that I accidentally assigned it a fix or SID without ever directing it to taxi. But now that I see you're experiencing the same thing I'll look back at some old footage to verify that.

**Comment by tedrek** [comment]
I have never seen aircraft order to taxi which don't end up at the runway.

However, there is an odd timing behavior which you may be running into.  If an aircraft is ordered to taxi to a runway and no aircraft is waiting then it will take 'delay' seconds plus zero to three seconds to arrive on the runway.  At SFO this means an aircraft takes from 2-5 seconds to show up after you issue a wait command.  If there is already an aircraft waiting to show up, then the delay becomes 60 seconds from the time the next aircraft appears.  Could this be the behavior which you are noticing?

This does seem backward to me, having a line of aircraft waiting for the runway should mean they are ready for takeoff much quicker than having to taxi from the apron.

**Comment by erikquinn** [comment]
The issue is probably related to that, it sounds kinda overly-complicated... But not quite even, its much more than 60s. It only happens occasionally, but when they skmrwhow get stuck like this, nobody shows up at the runway ever. 

If it helps, using other runways will still work, until that one gets jammed up too. And they all seem to be getting there, because they will tell you who they're waiting behind.  Maybe it's just a problem with the first guy in line not showing up, but still being ready to go. It's just tough to figure out who is first. I suspect that if I cleared the first in line of the pileup for takeoff, the subsequent ones would continue appearing as normal, but I have yet to verify this; its just my hunch.

**Comment by harp71** [comment]
@erikquinn this might be related to what i found out here #105

**Comment by erikquinn** [comment]
@harp71 oooh definitely-- good catch. that will be very helpful to track down what's causing it.

**Comment by erikquinn** [comment]
Resolved by #400.
