### ISSUE TITLE
On time percentage - reward efficient handling of flights. 

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#355]
I feel it would be a big enhancement to the game to reward the efficient handling of flights. Spinning planes, circuitous routes, ignoring waiting flights is not currently penalized. Players lack incentive not to send a flight around the block. That might change if the game tracked their on time percentage. 

Another enhancement would be to add connections. A controller would think twice about spinning a plane if they have a connection to make. 

These aspects could ultimately be incorporated into scoring and stats features. Since generating stats inherently requires the game to end perhaps missions or scenarios might also be considered? Stats and scores are more meaningful if players face precisely the same workload.

<h2>STATS</h2>

<h3>ON TIME PERCENTAGE</h3>

<b>ARRIVALS</b>

• Assign flights an arrival time (for programming purposes, perhaps a countdown?).
• Once under ILS control (both altitude and speed) the on time status appears on the flight strip.

![on-time](https://cloud.githubusercontent.com/assets/179496/12509553/33077f7c-c0b8-11e5-80ba-b85f5bcf0f9b.gif)

• Stats: Number of on time arrivals and those that weren’t on time.
• On time %.

<b>DEPARTURES</b>

• Assign flights an expected time to clear the radar (again, programmers might use a timer?).
• As flights approach the edge of the radar the on time status appears on the flight strip.
• Stats: Number of on time departures and those that weren’t on time.
• On time %.

<h3>CONNECTIONS PERCENTAGE</h3>

<b>CONNECTIONS</b>

• Assign flights a connection condition that appears on the flight strip.

![connection](https://cloud.githubusercontent.com/assets/179496/12509641/adad6d36-c0b8-11e5-8cc4-f12be9598134.gif)

• Stats: Number of flights that made their connection and those that didn’t.
• Connection %.

<h2>SCORING</h2>

• Missed connections, late arrivals and late departures should incur a penalty.
• Bonus points for perfect play (no penalties, no late arrivals/departures, no missed connections).
• Display all penalties (if any) incurred during the session.
• Display points per minute (or per mission/scenario).

**Comment by Maverick283** [comment]
I like!!!! Gives a new challenge to the whole thing!

**Comment by erikquinn** [comment]
Awww yeah! This is the good stuff. The only one I don't care for is the connections; probably 95% of the airplanes flying to any of our airports in the game would have passengers connecting to another flight, and regardless the controllers wouldn't really know if they do or not, and it isn't even allowable for that to be weighed in when considering which aircraft is to get the delay when the airspace gets congested. They're supposed to be chosen based on what would cause the overall lowest time delay to all aircraft.

I am definitely a fan of the on-time percentage. Maybe when an arrival crosses the boundary, we take the distance to the airport divided by the max speed (250 or best capable), to get the fastest possible time to landing, and add tiers to it:
- x1.3 or less: "early"
- x1.5 or less: "on time"
- x2.5 or less: "late"
- more than x2.5: "very late" (big score deduct)

**Comment by sixeyeco** [comment]
![leaderboard](https://cloud.githubusercontent.com/assets/179496/12521626/8c31c524-c100-11e5-97e5-e93e241a291c.jpg)

I am very excited by the response. I'd love to earn badges based on achievements. Something along the lines of:
<img src="https://cloud.githubusercontent.com/assets/179496/12521293/a6fb21ea-c0fe-11e5-9420-92ac9d4f8702.jpg" width="190" align="right">(click to enlarge)
<img src="https://cloud.githubusercontent.com/assets/179496/12522434/7b2a345a-c105-11e5-9b50-9e3137838406.png" width="440">
@erikquinn: 

> The only one I don't care for is the connections... when considering which aircraft is to get the delay ..they're supposed to be chosen based on what would cause the overall lowest time delay to all aircraft.

That make sense; scratch connections. 

> x1.3 or less: "early"
> x1.5 or less: "on time"
> x2.5 or less: "late"
> more than x2.5: "very late" (big score deduct)

I like the tiers! Particularly because you padded the fastest possible time to land. That accounts for queuing due to traffic and the fact that we're not robots. 

Any thoughts on scoring? How about a per flight multiplier? Flights that arrive and depart very late are multiplied by -100% (0 points). Late flights are multiplied by -80% (2 points). On time flights are worth the normal 10 points. Early flights are worth 150% (20 points).  

A bonus at the end would also help. Only on time flights or better? 200 points. All early flights? 2000 points. There could be other achievements worthy of bonuses as well. Terrain on? you get a bonus (or per flight multiplier). Played the entire game at warp factor two? You get a bonus (or per flight multiplier).     

A structure similar to this would create some real space in scoring, allowing for the cream to rise to the top. Not to be elitist, but it would also ensure that those in the upper echelons truly belong there. 

Any feedback with regard to specific missions? Comparing apples to apples would really dial in this competition thing. I thoroughly enjoy KSFO; a great mix of arrivals and departures, it's quite intense (at least in waves) and the terrain adds a manageable challenge to it all. If about five of the (seemingly) random scenarios were available as presets from the menu then we could avoid asterisks next to the "World's Record" holder's name.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
