### ISSUE TITLE
Splashscreen?

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#357]
Jon Ross started something that has ignited a lot of passion. Even if I only speak for myself it's worth mentioning publicly. As a gesture of thanks I proffer the splashscreen below. 

Thanks Jon!

[See it live on my fork](http://sixeyeco.github.io/atc/)

![splash](https://cloud.githubusercontent.com/assets/179496/12534049/efc29b3e-c1fc-11e5-8fed-3660ddb668ea.gif)

**Comment by harp71** [comment]
merged ;)

**Comment by tedrek** [comment]
I think this would be a really nice touch

**Comment by erikquinn** [comment]
Cool!

Piggybacking on this idea, just as a note-- as the library of airports, aircraft, airlines, etc continues to grow, at some point, we may want to think about initially displaying just the list of airports, and then when the user selects the airport they want, only the necessary airlines and aircraft are loaded to save time loading extra data.

**Comment by sixeyeco** [comment]
@erikquinn Nice. It sure would make sense. Perhaps just prevent the load, open the airport selection dialog by default, set its z-index so that it floats over the splash and then automatically close once an airport has been selected. 

If someone can write that in I feel confident I can tweak the css so that the splash image is out of the way.

I was also looking at the possibility of adding additional credits, to recognize the work you all have put in to this. I'd really like it to pull the data directly from [ZLSA's Github contributor page](https://github.com/zlsa/atc/graphs/contributors) so that the data is always up to date. If that's a good idea then can someone write the code to display the names on the loadscreen in a box and attach it to a css file? I can tweak css and html a little bit, usually enough to get it to look like I want it to.   

![splashscreen-base-layer-with-credits](https://cloud.githubusercontent.com/assets/179496/12563699/6546bab6-c360-11e5-86b1-ad4fd8f44736.jpg)

**Comment by erikquinn** [comment]
I also just had a new idea: when first loading up, we could offer to pick between various global "difficulty" or "realism" settings, so there's like a "beginner mode" that has traffic scaled down, no fancy stuff, etc, and then other various steps until the highest difficulty, where realistic airspeed, wake turbulence violations, and other advanced options are all enabled. It would save me some time from having to click through the option s menu each time I played :)
