### ISSUE TITLE
Tips during load screen

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#367]
I know you all probably rarely notice it since you reload the game all the time, but it actually takes quite some time to load (I counted 27 seconds last time).

This is quite a boring time, and if you don't stay on the tab, the loading is paused...

While reducing the loading time could be one solution but would require huge structural changes, it would probably be smarter to give the user something to do in this time.

I am thinking of useful tipps, that explain all the great features this simulation has, like SIDs, commands and some basic ATC rules. Could that be added to the load screen?

**Comment by erikquinn** [comment]
"Tips & Quips", I love it!

That would be great, and pretty simple to implement.

**Comment by sixeyeco** [comment]
:+1:  That would be awesome! 

Could the tips be a popup that requires a user to close, perhaps a "show tips on startup" kind of thing? Also, start the sim in paused state (just in case they were actively reading a tip) and give some sort of indication that the game is ready. When the user closes the tips window they essentially resume the game to start. 

![tips-on-startup-mock](https://cloud.githubusercontent.com/assets/179496/12654970/71d2e104-c5ab-11e5-8f4e-23e436d9338e.jpg)

**Comment by Maverick283** [comment]
Yeah @sixeyco, I was thinking of like a "start the game" button, as that gives the user time to read it when there are short loading times (like a reload) :D

This is looking good!

**Comment by sixeyeco** [comment]
Maybe have the loader incorporated to turn into the "play" button? 

This one is the same size as above but maybe a much larger version would really be better. Twice as wide, twice as tall? It could have categories, like like you suggested; SIDs, commands and some basic ATC rules.

![splash-loader-with-tips](https://cloud.githubusercontent.com/assets/179496/12662205/940070fc-c5d3-11e5-8ad1-9f9b8e9c2b2f.gif)

**Comment by tedrek** [comment]
#561 completely overhauled the data loading so it should be a few seconds for most people.  Do you @Maverick283  still find the load times to be long enough to possibly justify tips during the load screen?

**Comment by Maverick283** [comment]
@tedrek No, it only takes about a second for me now, even though I'm never sure if really does the full loading process... I got a pretty speedy internet connection, but I'm not sure about others with a slower connection.

With my connection it is probably more confusing to display tips during load.

**Comment by tedrek** [comment]
@Maverick283, right at the moment, not everything is loaded.  But #596 as tested loads all airlines and aircraft for the current airport and does so in a second or two even on my slow machines so I don't think we'll run into slow load times again (except for a bug :grin:)

I am going to close this issue on the belief the underlying issue is fixed.
