### ISSUE TITLE
Fly heading bug

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#368]
When an aircraft is told to fly to certain fixes and you try to change it to fly by heading, it stays on the fix. 

There is not really anything else I can describe here, please check if you get the same issue.

**Comment by erikquinn** [comment]
I just checked, and am not seeing it. I was able to get it to go to the heading in a variety of situations (not yet to the fix, btwn fixes, after fixes, etc).

By "fly by heading" are you referring to the `fh` shortkey? As in `AAL365 fh350`?

**Comment by Maverick283** [comment]
Only "h"... 

Why does it his always only happen to me :D

This time on my laptop though, not the surface ;)

**Comment by Maverick283** [comment]
Okay, this issue is not for the main branch, but needs to go to pull request #365!
