### ISSUE TITLE
Flight strip rack scrolls when upper strips are selected

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#369]
Issue: When there are enough strips that the scroll bar appears click on the top strip. You will see that the list scrolls to the bottom taking the active strip out of view.  

[Video](https://www.youtube.com/watch?v=3GY49Zkx3jg&feature=youtu.be)

I have other issues with the scrolling list that might be solved if this one were addressed.

**Comment by sixeyeco** [comment]
It's driving me nuts because I've edited ksfo to a really heavy workload and the rack keeps defaulting to the bottom. Could someone point me in the right direction? Even some code that would maintain focus on the newest strips would work.

The only thing I've found is on input.js:

```
if(number == 1) {
$("#sidebar").scrollTop(round(match.html.position().top + ($(window).height() / 3)));

```

Is that it?

**Comment by tedrek** [comment]
Yep, thats it.  It's trying to scroll so the currently selected aircraft is within view, however the logic is wrong resulting in most of the time it scrolling to the bottom of the list when selecting an aircraft.

Try this code instead

```
if ((number == 1) &&
    ((match.html.offset().top < 0) ||
     ((match.html.offset().top
       + match.html.height()
       - sidebar.offset().top)
      > sidebar.height())))
{
  sidebar.scrollTop(sidebar.scrollTop()
                    + match.html.offset().top
                    - (sidebar.height() / 2));
}
```

**Comment by sixeyeco** [comment]
<img src="https://cloud.githubusercontent.com/assets/179496/12873378/3511010c-cd70-11e5-97df-7d28ff87b4f5.gif" width="150" align="right">@tedrek Thanks!! This issue has been driving me nuts. When I implemented it on my fork, however I encountered a consequence. The code appears to address the scrolling issue but I am unable to issue commands. Yet, when a command is issued with no flight selected I get "no such aircraft, say again". Because I'm not a code writer I've attached a screenie of my implementation.

**Comment by tedrek** [comment]
I missed a line.  Add `var sidebar = $('#sidebar');` as another line before the if

**Comment by sixeyeco** [comment]
<img src="https://cloud.githubusercontent.com/assets/179496/12874545/a2ed0df0-cd8a-11e5-9838-8f9626884d20.png" width="150" align="right"><img src="https://cloud.githubusercontent.com/assets/179496/12874657/6dadcc86-cd8c-11e5-978d-3d89f6b7a3a3.png" width="150" align="right">@tedrek Thanks for the quick work! Scroll appears to work as hoped, and I again have the ability to issue commands but I ran into an issue. 

A command of `c 1000` removes the flight from the rack, turns the craft approx 170 degrees and immediately displays a message about it leaving radar coverage (even though it hasn't yet). 

Edit: Further testing and I'm very happy. I'm personally not impacted by error reported above. It fixed what I wanted to get fixed. I can't thank you enough!  :+1:

**Comment by tedrek** [comment]
Glad it works for you, I've merged it now.

The error you are seeing with `c 1000` is due to #344 making all altitude entries in hundreds of feet.  The command is clearing the aircraft to 100,000 feet.  Additionally you must have the option 'depart via climb' set to yes which means the aircraft being implicitly handed off to the controller for the airspace above the terminal area as they climb past 10,000 feet.

**Comment by sixeyeco** [comment]
Ah, ty. Great work. I'm such a happy camper now.  I came across it by commanding an arrival with `c 990` instead of `c 99`. Any chance that the altitude for arrivals could be capped at 10k to prevent this? P.s. Let me know when I should close this. :)

**Comment by tedrek** [comment]
With the manual hand-offs being discussed in #358 it should solve the issue for arrivals.  In the meantime, you can set 'Allow departures via climb' to no in the options.
