### ISSUE TITLE
Localizer Intercept Angle

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#375]
As I alluded to briefly in #352, I was "pretty sure" that we weren't handling the approach course interception rules correctly in the code. The applicable paragraph out of the [65](https://www.faa.gov/documentLibrary/media/Order/ATC.pdf) is para 5-9-2, and provides a table indicating the normal intercept angles, 30 degrees most commonly being the applicable offset.

So, in the code, a la line [1637-1647](https://github.com/zlsa/atc/blob/b4b266c4177d7f8ee5f727e70e20b0125d38e3c9/assets/scripts/aircraft.js#L1637-L1647):

```
//plane is on the glide slope
if(this.mode != "landing") {
    this.mode = "landing";
    if (!this.projected &&
        (abs(angle_offset(this.fms.currentWaypoint().heading, angle)) > radians(30)))
        {
            ui_log(true, this.getRadioCallsign() +
                       " landing intercept vector was greater than 30 degrees");
            prop.game.score.violation += 1;
        }
```

We calculate the difference between assigned heading and runway heading, and see if it's over 30. The catch (which I have verified today with a retired controller and trainer at the FAA Academy) that yes indeed, those 30 degrees are based not on the runway's precise magnetic heading, but on its nominal heading.

For example, SFO's 28R & 28L have a magnetic heading of 284, but are called "28" left/right, and it's the "28" part that those headings are based off of. So, even though 250 is 34 degrees offset from runway heading of 284, it is allowable because it is 280 - 30 degrees.

The logic should be changed to compare assigned heading not with the literal `angle` of the runway, but the _nominal_ angle, eg. 280 degrees.

**Comment by siyuanr** [comment]
I concur. Just another example why nominal angle should be used (my beloved `VHHH` again): the [ILS 07R Approach](http://www.ais.gov.hk/HK_AIP/AIP/AD/HK_AD2-91A.pdf) calls for a final turn heading 040 to intercept localizer, but RWY 07R's inbound heading is 073.

(We don't have this problem in `VHHH` in game right now, because we are using an RNAV approach.)
