### ISSUE TITLE
New Airport ZGSZ

### ISSUE THREAD

**Issue by siyuanr** [zlsa/atc#382]
I am trying to create the map for Shenzhen International Airport (ZGSZ) based on `vhhh.json`. However, I somehow cannot get any web browser to load `zgsz.json` in [my fork](siyuanr.github.io/atc/). The game is fully loaded, but the map is not in the selection menu. There is no parsing error according to the Javascript console in Chrome developer tools. Can someone have a look and see what is wrong? 

(The wind speed, arrivals and departures are still copied from VHHH, with the fix names updated.)

**Comment by siyuanr** [comment]
Also, how to flag the airport as "in development"?

**Comment by sixeyeco** [comment]
@siyuanr   As in "San Francisco International Airport &#9983" the unicode at the end of the human-readable name is the "work in progress" flag. `Shenzhen International Airport  &#9983`

As far as it not showing up in the list be sure to add it to the list in airport.js

**Comment by Fechulo** [comment]
It's working for me, try opening it in an incognito window.

**Comment by siyuanr** [comment]
Yep it's up and working now. However a weird JS error pops up. "Cannot read property '0' of undefined" at line 476 in `airport.js`, one that governs the randomness of the arrivals. I will try to update the map with realistic arrivals tonight and see if it changes.

**Comment by siyuanr** [comment]
@Fechulo Where did you get the arrival data for `VHHH` (airlines served, most common STARs taken, frequency of arrival,  etc.)? I need to so the same for `ZGSZ`.

**Comment by Fechulo** [comment]
@siyuanr For the airlines, I looked at FlightAware and checked which ones were the most frequent at VHHH. For the STAR's, I looked at the most common destinations and checked the [flight plans](http://rfinder.asalink.net/free/). From that I can see which STAR's they use. And to be honest, the frequency of the airlines was just a very rough estimate. However if you're looking for more realism, for EGLL I used and app called [FlightScheduler](http://www.mediafire.com/download/kucg69tq5wngk1h/FlightScheduler_1.5.zip), counted the number of arrivals per airline and entered that as the frequency.

**Comment by siyuanr** [comment]
All done! All the waypoints are here, completely drawn from the RNAV charts. Test it [on my fork](https://siyuanr.github.io/atc/)! A few remarks:
- All the charts and manuals can be reviewed at [eAIP China (2015.11.15)](http://www.eaipchina.cn/Version/201513/Html/MaterialVersion.htm).
- SIDs are only for RWY 15 at the moment, as we wait for progress on #324.
- Fixes `CF33` (IF point for RWY33 Approach) and `SZ101` (first point for many SIDs) share the same location; I chose to display `CF33` on top because SIDs can be pre-programmed.
- For the RNAV approaches we are supposed to turn RWY heading after flying by the IF point; however since we haven't been able to chain a `fix` and `heading` command together, I mapped out the ILS beacon locations so that we just can align with those.
- New airlines `CSZ`, `CHH`, `CXA`, `AXM`, as well as the non-South American versions of `KAL` and `CCA` are added for sake of reality.

**Comment by erikquinn** [comment]
@siyuanr I tried it out briefly... looking and working good to me! :) And #324 is wrapping up soon here... I'll have a PR by tonight for it.

**Comment by erikquinn** [comment]
@siyuanr Same question for ZGSG... have you finished, and could it be merged in here?

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
