### ISSUE TITLE
Incremental Turns (eg. 'turn twenty degrees right')

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#389]
In practice, it is of tremendous value to tell an aircraft "AAL123, turn twenty degrees left, vector for sequence" or similar, in order to tweak a heading without necessarily assigning a specific heading by value.

The way this is achieved by the simulation software I'm familiar with is by (when in the context of turns) interpreting _three-digit numbers_ as actual magnetic headings, and interpreting _two-digit numbers_ as a number of degrees to turn in the specified direction.

I'd like to see this implemented, as I am constantly wanting to give 10 degrees right to aim airplanes in the middle of a gap I've built after initially giving a heading that was slightly off the mark.

Any objections? Because this would mean that one could no longer type "t r 30" and have the aircraft turn to heading 030. After all, headings _are_ always specified in three digits, including the leading zero, _but_ I want to ensure that forcing entry of "030" when referencing the heading wouldn't be a significant annoyance.

**Comment by Maverick283** [comment]
I'm in!

**Comment by harp71** [comment]
@erikquinn i never heard a controller tell an aircraft to change heading to a degree from his current heading. And frankly it seems rather imprecise. The commands i heard are "turn left/right heading xxx" or "direct <navpoint>" etc. Regardless, if the degrees have to be 3 digits, it´s ok for me.
