### ISSUE TITLE
Speed Assignment Hidden While on ILS

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#390]
![image](https://cloud.githubusercontent.com/assets/5103735/13012964/80704fea-d17b-11e5-8669-9f8d21ce48ac.png)
![image](https://cloud.githubusercontent.com/assets/5103735/13013058/cc245f1c-d17b-11e5-8a77-0112b9364270.png)

When working a really long final, controllers will usually implement a few speeds in order to achieve the desired amount of compression. Of course, the speed assigned is realistically remembered, and relatable to the datablocks (although it's GS not IAS). But since we have the strip bay display assigned speed for departures shown, it seems appropriate to _SHOW_ the speed for aircraft on the ils as well, in place of the currently existing dash symbol.

**Comment by harp71** [comment]
@erikquinn sure, i never did see that. As it is now it would seem, ILS is controlling the speed to, which it doesn´t. SHOW THE SPEED (angry mob chant) ...

**Comment by erikquinn** [comment]
SHOW THE SPEED! SHOW THE SPEED! SHOW THE SPEED! :fork_and_knife: :fire:

**Comment by engeplabs** [comment]
Haha loving this issue :joy:

So why did we put the dash there in the first place?

**Comment by erikquinn** [comment]
not sure... somebody probably just assumed/simplified it to not being able to control speed for aircraft on the ILS. Once they pass the final approach fix, we cannot control their speed any longer, so it was probably just implemented that there is no speed control on final, and then it was added as a feature, but not added to the strip, so the dash remains. My guess anyway.

**Comment by engeplabs** [comment]
Ok. So we would show the speed until the final aproach fix and the player is able to control it. Then i would suggest that on final we show the bash again or we change the color of the speed number to some grayed out tone. How does that sound?

**Comment by erikquinn** [comment]
@patitoxd The dash is fine by me, as long as they are within the FAF. To simplify it (so we don't have to enter the distances out each FAF is), we can just stop displaying speed and go to the dash upon reaching a 10km (~5nm) final, which is accesible via `offset[1]`.

**Comment by erikquinn** [comment]
Issue resolved via commit 08bdd42 from #451, which has been merged. Closing.
