### ISSUE TITLE
Where to Find Aircraft Specifications?

### ISSUE THREAD

**Issue by siyuanr** [zlsa/atc#391]
I have to create/edit some airlines in the process of making `KORD` at #387. Some aircraft models are missing, most notably `A359` (A350-900 XWB), `B77L` (B777-200LR), and `B789` (B787-900). Where do you guys typically find them?

**Comment by MaicomMR** [comment]
Hey sinyuanr, you can find data from real and useful airplanes on this site: https://doc8643.com/index
But caution with the number of airlines, this can increase the loading time a lot.

**Comment by siyuanr** [comment]
@MaicomMR Advice taken. However I cannot see the models I am looking for on that website. Do you have another resource?

**Comment by MaicomMR** [comment]
@siyuanr Click on "aircraft" to see the full aircrafts list, or use the "doc8643" to search a specific model.

https://doc8643.com/index
https://doc8643.com/aircrafts
