### ISSUE TITLE
Merge aircraft jsons to single file per manufacturer

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#402]
Hello budyes.
I'm think the possibility of merge all aircrafts for a single .json file, I believe that will give a lot of work, but will reduce a significant time of "loading", with this change we can create a lot of more detailed aircrafts to the game without increase the load time.
Unfortunately I do not know much about java programming to try Crair something, I leave here only an idea (I believe that many already have), but here is official and open for discussion.

**Comment by erikquinn** [comment]
Unless I'm mistaken, I dont believe merging json files will improve the performance... it still has to load all the same data, it just doesn't have to jump around between different files, which should be <1% of the clock cycles being used in the load. That said, I have noticed an abnormally long wait for each aircraft to load, which may be a problem with gihub pages servers being slow. Not sure.

I absolutely agree, however, that we can do more to reduce the loading time... I was thinking we ought to do so by _only loading the files we need_. Currently, we just load everything we have. Instead, perhaps we should change the `aircraft_init()` function to be more intelligent, checking the selected airport to see what to load. Then the initial load of the game would be much faster, as it would only load the current airport, any terrain for that airport, and only the aircraft that will arrive or depart from that airport. This would mean that changing airports would force us to "load" again, but that's a trade I would make to be able to load up more quickly.

**Comment by erikquinn** [comment]
^^ Actually, I AM mistaken. 

![image](https://cloud.githubusercontent.com/assets/5103735/13262454/e052e7f0-da32-11e5-93d6-813e53833d86.png)

Apparently, it's actually spending 85.46% of the loading time waiting for the github pages server to start sending the json files.. and that's when it's flying through the load. It's probably way worse when it loads slowly. Thus, we could reduce loading time 100-fold if all the aircraft jsons _were_ merged like @MaicomMR suggests. There are tools for this (like [grunt-minjs](https://www.npmjs.com/package/grunt-minjson)), but having to recompile the minified json every time an update is made to any of the individual jsons would be quite a pain the ass, and arguably not worth it. Maybe that's something that could be done server-side if we do start using something like heroku (with which I have zero experience), and then it would be done automatically and wouldn't be bad at all.

**Comment by MaicomMR** [comment]
I will try to study on grunt-min js & heroku, but I have little knowledge in programming, in fact, I teach history. I'll try to use my spare time to learn more about these programs, my intention was to actually call the members for discussion of this issue.
Very thanks @erikquinn.

**Comment by headphase** [comment]
@erikquinn how about if we combine all aircraft of the same manufacturer into a unified .json?

boeing.json
embraer.json
misc.json

etc...

I think it would be a good compromise of performance and convenience.  Wouldn't be too difficult to  update/add new aircraft that way.

**Comment by MaicomMR** [comment]
@headphase your idea sounds good, we can maybe build the manufacturer list with all aircrafts of all big manufacturer (Boeing, Airbus, Antonov, Douglas, Embraer, Canadair, Lockheed[and create a misc_small, misc_medium, misc_heavy) based on "doc8643.com", with this we not need to add more aircraft.

What do you think guys? I would not know how to create such a group, but to create a basis I am willing to help convert and add all the models that are missing.

**Comment by erikquinn** [comment]
@headphase sounds like a good compromise, though the files could still become hard to navigate. Nonetheless, with such inconsistency on the github pages servers, it's probably a good idea. There's some stuff "down in the depths" that will probably need to be reworked, but I don't think it should be too bad.

**Comment by tedrek** [comment]
@MaicomMR the changes in #561 should remove the need for this change.  Closing.
