### ISSUE TITLE
Yet another bug with speech

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#412]
The callsign of all GermanWings aircraft will always be pronounced as "germanwings 0123", regardless of the actual callsign. Could have something to do with the fact that the callsign contains letters. Any ideas?

**Comment by erikquinn** [comment]
@Fechulo that would definitely mess it up if it has letters in it... I remember it clearly. They can do that though? Put letters in airline callsigns?? If so, I had no idea.

**Comment by Fechulo** [comment]
@erikquinn Yeah, Ryanair and Germanwings and many other airlines do it all the time.

**Comment by erikquinn** [comment]
@Fechulo I see. :smile: I made some updates, it should now be working correctly. You can see #422 and/or http://erikquinn.github.io/atc/b/alphanumericAirlines/ at your leisure to verify that it's working correctly now.
