### ISSUE TITLE
Radar Video Maps

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#423]
"Video Maps" are the actual maps drawn on the screen of a radar scope. They provide guidance with various aspects of traffic flow (provided that you know what each of the lines is actually denoting) that are very helpful with working the real-world traffic. At least in the United States, video maps are eligible deliverables under the Freedom of Information Act (FOIA), and thus, many of them have already been requested and made available to the public. And I know people who have done it, and could even put in requests as needed for other FAA airports that aren't already out there. With some relatively easy data reformatting, these video maps could be drawn in this simulator.

The only question is what kind of lag it would create to have to redraw so many lines each time the screen is moved. For people like me, who are in it for the realism, it would represent a huge step up in realism. Hopefully it can be achieved without significantly affecting performance... I'm not sure, but wanted to put this up here for discussion. Once one is added, then we can really figure out whether or not it is feasible for a web-based simulator.

Video Map Examples:
(i've got a bunch of them)

![image](https://cloud.githubusercontent.com/assets/5103735/14031147/6bbcb498-f1d9-11e5-81a9-1aabb9551ed4.png)
^Detroit TRACON (D21)

![image](https://cloud.githubusercontent.com/assets/5103735/14030877/f4333a06-f1d7-11e5-9fc9-02d09aa4bfe3.png)
^Seattle TRACON (S43)

---

![image](https://cloud.githubusercontent.com/assets/5103735/14030915/299521a0-f1d8-11e5-9898-eb4bdcc4bd99.png)
^New York TRACON (N90) - Kennedy, Newark, Islip _and_ Liberty areas all overlaid

**Comment by erikquinn** [comment]
LIVE DEMO! [erikquinn.github.io/atc/b/rvm-demo](http://erikquinn.github.io/atc/b/rvm-demo)

_SOMEHOW_, it seems that the performance is a total non-issue. I'm not seeing any lag whatsoever, which is quite surprising, and makes me wonder if there's maybe something in the other parts of the canvas drawing code that are taking longer than they should, because this is a LOT to draw (there's 10,702 lines), and it did it without any complaints.

![image](https://cloud.githubusercontent.com/assets/5103735/14960943/eb038f14-105c-11e6-8fae-83af38cbe4ad.png)

**Comment by Fechulo** [comment]
I really like the new 'toggle fixes' button. I'll see if I can find similar radar maps for the european airports,

**Comment by erikquinn** [comment]
@Fechulo that would be legit. It may be tough to get your hands on them, and I'm sure it varies from country to country. I know the UK doesn't even let people _listen_ to live atc, and therefore would probably never share the video maps. But other countries hopefully would. Not sure; but I do know that I can get a lot of US ones, and what I can't get, I can request through FOIA and have within a month or two.

**Comment by Fechulo** [comment]
I doubt I'll be able to find real life video maps, but vatsim (virtual air traffic simulator) usually provides controllers with 'things' similar to these maps.

**Comment by erikquinn** [comment]
gotcha, that makes sense. That's my go-to place for RVMs too, they've got pretty much everything we need.
