### ISSUE TITLE
On-screen Changelog/'patch notes'

### ISSUE THREAD

**Issue by headphase** [zlsa/atc#433]
Just a thought; would it be beneficial to display recently-added features/updates to players somewhere in the UI?  Perhaps after loading is complete, the load screen could pause and generate a "Launch Sim" button and have a text box below it listing recent changes and updates?

The reason I bring this up is because players retain interest much longer when they know the game is being constantly improved, plus this will add polish to the game and also provide a way to train veteran players on new features.  Everyone loves that 'Christmas morning' feeling of loading a game and discovering new updates/patch notes.

**Comment by erikquinn** [comment]
Yeah, that's a really good idea. User 'tips' were suggested in #367 (related to #357), but I think new features would be much more valuable to show users while the game is loading. Personally, I'm not entirely sure how to go about implementing it, but for one am definitely in favor of it!

**Comment by headphase** [comment]
I really like the loading screen at sixeyeco's fork http://sixeyeco.github.io/atc/ and think it could work perfectly with this idea.  Update info/notes could be placed in index.html under the "loading" div (either directly, or have it called from another file).  However I don't know JS so the thing I'm unsure about is how to halt the loading screen so it doesn't jump automatically upon completion.  Having a button appear so the user can manually click to the game screen would be ideal.

**Comment by erikquinn** [comment]
A changelog has since been added for users to review. Closing.
