### ISSUE TITLE
Help updating KJFK

### ISSUE THREAD

**Issue by jpeterson1346** [zlsa/atc#435]
I have updated the airport's SIDS, approaches, traffic, fixes, and some other things but when I go to test them locally, everything loads fine (as far as I know) except I cannot see anything other than range rings on the display. All other airports display fine. 
![kjfk](https://cloud.githubusercontent.com/assets/9057104/14407908/7484ddc4-fea1-11e5-8b06-bf41e33dd9ee.PNG)

**Comment by Fechulo** [comment]
The problem is that the altitude for the STAR's is not being specified. You need to add the altitude just like you did with the PARCH ONE arrival. Also, I don't see any point in keeping the NORTH, SOUTH, WEST and EAST departures, as these were only temporary.

**Comment by jpeterson1346** [comment]
Thank you, I can now continue working on it
