### ISSUE TITLE
Difference between "taxi" and "wait"

### ISSUE THREAD

**Issue by ghost** [zlsa/atc#441]
I have a problem with this two words. If the plane "IB2707" (for example) wants to taxi i should be able to make him taxi to the runway or make him wait before the runway. Because, if there is a plane approaching to land in less than 3nm and i tell to IB2707 to wait, it should wait before the runway.

![](http://lovernhome.us/fsx/007_IAH_Hold_Short_33R.jpg)

But, in the game, there's no difference between taxi and wait. I had many collisions because of this fact. Adding a "Hold and short" command should be fine.

PS: So sorry if my english doesn't explain well what i'm trying to say. I'm improving it day by day.

**Comment by Fechulo** [comment]
@Izeras This is not a new issue, it has been discussed in #350 but no changes have been made yet. Due to the limited amount of active programmers, It might not be fixed any time soon. Thanks for the reminder anyway!

**Comment by ghost** [comment]
@Fechulo okey thanks :)
