### ISSUE TITLE
Possibility to specify glideslope profile

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#449]
While most airports have a glideslope profile of 3 degrees, It can vary from airport to airport. An example of this would be EGLC, where the glideslope profile is a scary 5.5 degrees:

![5 5deg](https://cloud.githubusercontent.com/assets/13125311/14546287/78078dc6-029c-11e6-88d6-6b8570c4347b.PNG)

My idea is that the glideslope profile could be specified in the airport file. I think #426 makes this improvement a bit easier to program, but I wouldn't know. It could look something like this:

![profile](https://cloud.githubusercontent.com/assets/13125311/14546441/4c55bbf2-029d-11e6-8c3a-145eded0ad9a.PNG)

**Comment by erikquinn** [comment]
Are you sure this isn't already possible? I swear I remember seeing somewhere that you could specify it...

**Comment by Fechulo** [comment]
If it is possible, I had absolutely no idea. I'll check

**Comment by erikquinn** [comment]
![screenshot_20160414-193420](https://cloud.githubusercontent.com/assets/5103735/14547937/0c9bddb8-0278-11e6-9f3a-547592d67e5d.png)

Yes indeed! Just add the `glideslope` property (separate from `ils`) with the degrees of the slope. Should work! In theory :wink:

**Comment by Fechulo** [comment]
Wow, I didn't know that feature existed, however it isn't working. The problem is that the aircraft don't capture the ILS: 

![hmmm](https://cloud.githubusercontent.com/assets/13125311/14562766/83beb912-0316-11e6-8ba6-f622832b8d8f.PNG)

**Comment by erikquinn** [comment]
@Fechulo It seems to work for me. :confused: You can see I doubled the gradient of the 28R glideslope, and the 28R guy is twice the height of the 28L guy in the screenshot.

![image](https://cloud.githubusercontent.com/assets/5103735/14564508/71bf251e-02ec-11e6-8eeb-9be7efe54631.png)

![image](https://cloud.githubusercontent.com/assets/5103735/14564585/d0344d54-02ec-11e6-9448-caa47ea77888.png)

**Comment by Fechulo** [comment]
As you can see, I wasn't doing it correctly. It is working perfectly now

![isee](https://cloud.githubusercontent.com/assets/13125311/14565509/60c21032-0323-11e6-975d-03cb4b8cc588.PNG)

**Comment by erikquinn** [comment]
oh okay, gotcha. my bad, my explanation was garbage! Glad to hear it's working :smile:
