### ISSUE TITLE
"loop-dee-loop" of confusion

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#456]
Often, aircraft will be projected to do big loops around fixes they're navigating to, presumably because they are projected to "miss" the fix slightly, and then try to loop back around to cross directly over it like they were trying to. In reality, passing right over the fix is not super important. I'm not sure _how_ the logic works to determine whether you are close enough, but for our purposes it could be as simple as increasing the allowable lateral deviation from the fix's position to consider the aircraft "over it" sufficiently to proceed to the next waypoint.

![image](https://cloud.githubusercontent.com/assets/5103735/14673862/1406cf02-06c6-11e6-94de-64b1225fff3f.png)
In this screenshot, the aircraft ends up slightly east of `ANKER`, and therefore turns hard left to try to reach it.

**Comment by tedrek** [comment]
There is currently an allowable lateral offset from the fix, something like 500m.  The issue is that the prediction code steps the aircraft forward in 5 second increments and so it can easily step past the point where it is close enough to the fix.  Decreasing the increment size would be a quick fix which could give good results.

**Comment by erikquinn** [comment]
Yeah, I actually increased that in #464 (I think it was there) to 1km (~0.5nm), and that seemed to smooth it out. That's a good idea to decrease the step time, that would resolve it, though it's nice to have such foresight into the future... maybe a `vsub(fix, aircraft)[1]` type check could be used to see if they have "passed" the fix, and are within a larger radius as well...

**Comment by tedrek** [comment]
If the number of steps is increased proportionally to the decrease in step time then the length of the track in terms of overall time will stay the same.  The tradeoff is simulating that many more steps overall when drawing the future track.

The other thought I had was that #427 would require calculating a concept of having passed a certain point.  For fly-over waypoints this would probably fix the current problem, for fly-by waypoints the same concept may be applicable.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
