### ISSUE TITLE
Airport scaling and definition needs fixing (KJFK and others)

### ISSUE THREAD

**Issue by z-adams** [zlsa/atc#46]
It seems that approaching aircraft only spawn from the south. The distance varies but the heading does not. There is also a very low volume of them - only about 2 per every 3 departing flights.

**Comment by zlsa** [comment]
KJFK is broken right now (very wrong scale); its scale needs to be fixed.

**Comment by Diastro** [comment]
One thing I realized was that KDBG has pretty long runways (6-7 km runways)/runway separations (added to the fact the the runway position isn't right). The default zoom for the canvas is adapted to display KDBG properly. Hence, regular airport (with real dimensions) look pretty tiny with the default zoom / perspective.

Maybe we should give KDBG more realistic lenght and runwayy separation, then fix the default view/perspective.

For example the current KMSP.json has 8 km runway where in reality it has 3km-ish runway. I think we should fix this to prevent new airport from being displayed the wrong way.

I don't have much time tonight but I can work in this this weekend if no one has.

**Comment by Diastro** [comment]
With the latest fixes I pushed to airports, every airports now uses the correct runway length (in km). Also, I adjusted the default scale to match the real length of runways.

Remaining : Fixing waypoint positions (I only fixed the waypoints of KDBG). I will do the remainning tomorow.

**Comment by Phil57** [comment]
Due to this change, labels are not correctly placed at the end of the runway on KDBG for 36L and 36R.
Other are weird too, but better.

**Comment by glangford** [comment]
KJFK and KSFO should now be accurate. KMSP is still left to do.

**Comment by glangford** [comment]
With #168 which updates KMSP, I think this issue can now be closed.
