### ISSUE TITLE
Airways

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#461]
Adding the ability for aircraft to follow airways while in flight could add a lot, depending on the airspace. Particularly with respect to eventually adding an En Route mode to the simulator, this would be critical to complete before that could happen. Some reworking of the fms would be needed, but if done correctly, the implementation and addition of procedures like SIDs/STARs/IAPs, airways, published holding patterns, hybrid RNAV SIDs (where vectored for part, then cleared direct to join the departure) could be extremely straightforward. The key would be to change the perspective of the fms from waypoint-based to leg-based. Eg, currently, it sees:

`KSFO --> SENZY --> WAMMY --> SEGUL --> CYPRS --> MCKEY --> DAISY --> BENET --> SXC --> AVOLS --> PACIF --> HUBRD --> OCN --> VISTA --> ROBNN --> BONDO --> JLI --> KUMBA --> NICKK --> IPL --> etc`

This route is really a reasonable one, and in reality would be a much longer list of fixes. To clear it up, routes are written in reference to a joining point, a procedure/airway, and an exit point. This is how we would implement legs, and the same route in that notation would be like the below:

`KSFO.OFFSH9.SXC --> SXC.V458.IPL --> etc`

This way, by looking at the LEGS, we can easily edit, move the legs around, add a fix between legs, etc, whereas the same operation on a long list of fixes would be difficult, because you simply wouldn't know where a procedure started or ended.

The point is that airways would be a great addition, and I'm working on throwing something together now. Any feedback or ideas are welcome.

**Comment by Fechulo** [comment]
I've been thinking about for a long time! This would definitely be a great improvement.
