### ISSUE TITLE
Zoom Levels?

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#462]
Just had an idea, as I have to zoom in and out in-game... Why not add controls for a few levels of zoom presets? Like one for airport operations, where you're zoomed all the way into the runways, another for mid-range, another showing the whole airspace, etc... maybe making use of the F1-F4 keys or something?

Yay? Nay? Smart? Stupid? Useful? Useless?

**Comment by Fechulo** [comment]
It's a good idea, but I don't think I'd personally use it. I would be quicker for me to use the mouse wheel and move around the airspace. That said, I'm sure it would would be very useful for other players.

**Comment by engeplabs** [comment]
Maybe it would be a nice way to support mobile devices... though i don't know how it handles on a smartphone atm.

-------- Original message --------

**Comment by erikquinn** [comment]
This is not super important, so I'm just going to close this because it's making my "clutter alarm" go off. :laughing:
