### ISSUE TITLE
Command Cheat Sheet!

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#463]
Particularly as the list of things you can tell aircraft to do grows longer and longer, the need for some sort of quick reference card for commands is growing. It would be great if there could be a compact, mostly transparent box that contains a list of commands & 1-3 word descriptions of what does what.

And lately I've been thinking that maybe the menu should get a "help" section with a question mark as the icon, and have a drop-up style menu. That way there can be a help menu that contains the tutorial, command reference, and maybe a link to the wiki or something. Though, of course, keeping with the existing minimalist theme, it wouldn't look like the screenshot (it's just the drop-up concept), the submenu probably shouldn't come up on hover, only on click, and the drop-up items should be icons only (with tooltips). My thoughts anyway. And as the number of settings grows, this would probably also be a good idea for the settings menu, to separate gameplay settings from scope settings (# of histories, leader lines, ui themes, show/hide video maps / SIDs / STARs / airways / restricted areas), and traffic and/or difficulty settings (though perhaps this would work best through tabs?)...

![image](https://cloud.githubusercontent.com/assets/5103735/14932313/d200ad64-0e39-11e6-8ba0-d2c4fee836a4.png)

Food for thought, but implementing some sort of on-screen command reference would be a great option, particularly for beginners.

**Comment by GlenBush** [comment]
I like this Idea, as I am not a command line guy, I will how ever say that the short cuts they have put into the game are great. I would however like to queek this idea some. 

maybe if you click on the plane you could get a small box with buttons pop up nest to the plane that are common use then you click the commands you wish to issue they all toggle on/off. Then when you have the comands you want all set you click issue. and this will send the commands to the console. for the  " F faith wetor heman wesla " witch i use most the time you could display the out put and have the buttons matter with order they are clicked

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
