### ISSUE TITLE
"Random" Arrival Type is not random

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#473]
You can specify the method used to generate arrivals and departures, from options like `random`, `wave`, `cyclic`, etc. These should be checked, because I at least know that "random" arrivals are not random. They are simply spawned at a perfectly regular interval (that I assume is based on the inverse of the `frequency` parameter).

As an example of this in action, for two arrival paths that are "random", I always get this annoying tie along two routes that I have to resolve. It's cool to have ties like this, but not every time with another pair of wingtip-to-wingtip arrivals, as it just becomes predictable and pretty annoying.

![image](https://cloud.githubusercontent.com/assets/5103735/15025032/f5c3f190-11fc-11e6-8bba-55090810b3ef.png)

**Comment by tedrek** [comment]
I'm not sure which airport that is, but the frequency parameter for Random is probably a single value allowing no variation in timing.

See the documentation regarding the frequency settings for random arrival/departures:

> The random algorithm requires a 'frequency' key which is specified as
> a lower and upper bound in aircraft per hour.  A delay is randomly
> chosen between generating each aircraft which will result in at least
> the lower bound of aircraft per hour and at most the upper bound of
> aircraft per hour.

**Comment by erikquinn** [comment]
@tedrek Ah, I see. That should work to put a little bit of variance in there. Thanks! -EQ
