### ISSUE TITLE
IE & Safari Not Working

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#477]
Imagine my surprise when I noticed that "everybody's favorite browser" is having troubles again... It seems to not be loading airports somehow, which leads to it failing to start the game. :angry: 

It dies on `ui.js:113` when it can't find `prop.airport.airports`, because `prop` does not have a property `airport`. Do the same thing in Chrome or Firefox, and all the airports are there.

![image](https://cloud.githubusercontent.com/assets/5103735/15080487/16e014a2-1384-11e6-9531-74d403312828.png)

![image](https://cloud.githubusercontent.com/assets/5103735/15080537/46915670-1384-11e6-997f-1ccd06cd797a.png)

**Comment by tedrek** [comment]
It would be very useful to specify what version of IE this is affecting.  (I have limited access to IE and rarely touch it)

**Comment by avdg** [comment]
This error can't yet be reduced to a smaller use case. Can't it? Maybe adding conditional console.log (Error.stack) or debugger; statement can help?

**Comment by avdg** [comment]
This bug doesn't occur in edge.

**Comment by avdg** [comment]
In ie 11, this line of code is causing an error:

https://github.com/zlsa/atc/blob/e985d0bc8d2ca678366805cded9038b61c691430/assets/scripts/airport.js#L735

I'm not sure if that is causing a snowball effect or not (making the value undefined), and why ie 11 didn't stop executing.

**Comment by erikquinn** [comment]
This is also the case in Safari.
