### ISSUE TITLE
Restricting ILS signals

### ISSUE THREAD

**Issue by dominiks** [zlsa/atc#48]
It seems very easy to just assign a runway to an aircraft as soon as it enters radar range. I did a quick lookup for range data of ILS systems and it seems they are restricting to a 25° angle left and right within 25nm of the runway.

As far as I understood the source code the current check for an ILS signal is just a 30° check?

**Comment by zlsa** [comment]
Yeah, the current ILS check is just a 30° check. I originally had more restrictive tests but then it's really hard to get aircraft to lock on (as I imagine it is in real life), so I removed them. What do you think about adding more restrictive tests?

**Comment by dominiks** [comment]
I think it would make the biggest impact to just add a range restriction, so aircrafts would have to be within 30 km of the runway to get a ILS lock. How long are the lines that are drawn in front of the runways? Some visual aid would be necessary so players know where they have to guide the aircrafts to, maybe the existing lines can be used as a range hint.

**Comment by zlsa** [comment]
The lines extend from the runways 20km.

**Comment by dominiks** [comment]
You can try to extend them to 40km and use that as the border at which ILS locks are possible. Or use two lines to show the 30° area in which ILS locks are allowed, but that might clutter the view too much.
