### ISSUE TITLE
Standard Terminal Arrival Routes

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#485]
We've got SIDs, and #464 reworked some things to improve upon the fms, and the next logical step is to add STARs with the same format as the SIDs. Should be pretty quick and easy work.

**Comment by Alpi-no** [comment]
`"NERDU 4K": {
      "icao": "NERDU",
      "name": "Nerdu",
      "suffix": {"11":"4K", "29":"4M", "16":"6L", "34":"4N"},
      "rwy": {
        "11": ["NERDU", "WW662", "WW660", "WW658", "WW656", "WW654", "WW653", "WW652", "WW651", "WW650"],
        "29": [],
        "16": ["NERDU", "WW872", "WW896", "WW675", "WW673", "WW672", "WW671", "WW670"],
        "34": []
      },
      "body": [],
      "draw": [["NERDU", "WW662", "WW660", "WW658", "WW656", "WW654", "WW653", "WW652", "WW651", "WW650"], [], ["NERDU","WW872", "WW896", "WW675", "WW673", "WW672", "WW671", "WW670"], []]`
This the Nerdu STAR for LOWW, despite fixes possibly being incorrect, is there any mistake with the format? (http://eaip.austrocontrol.at/lo/150430/Charts/LOWW/LO_AD_2_LOWW_24-5-2-1_en.pdf in case anyone wants to check)

**Comment by erikquinn** [comment]
@jakobeng1303 as I look at the charts, yeah, I suppose that's the only way to do it. There were a few minor things I cleaned up for you. For example, the empty arrays in the draw section should be removed. Also, runways 29 and 34 are empty. If they were not available to a NERDU arrival, the runways _should be omitted altogether_. But I looked up the other charts from the austrian eAIP (thanks for the link!) and it looks like they are valid, so you are probably still working on adding those. Just wanted to give a heads up that they should either be filled in, or removed, and not left empty.

```
"NERDU": {
  "icao": "NERDU",
  "name": "Nerdu",
  "suffix": {"11":"4K", "29":"4M", "16":"6L", "34":"4N"},
  "rwy": {
    "11": ["NERDU", "WW662", "WW660", "WW658", "WW656", "WW654", "WW653", "WW652", "WW651", "WW650"],
    "29": [],
    "16": ["NERDU", "WW872", "WW896", "WW675", "WW673", "WW672", "WW671", "WW670"],
    "34": []
  },
  "body": [],
  "draw": [["NERDU", "WW662", "WW660", "WW658", "WW656", "WW654", "WW653", "WW652", "WW651", "WW650"], ["NERDU","WW872", "WW896", "WW675", "WW673", "WW672", "WW671", "WW670"]]
}
```

**Comment by Alpi-no** [comment]
@erikquinn Thanks for doing that :) ! At the beginning I was planning to add the missing runways as well, but as the current wind situation in game doesn't want me to use these stars, I thought of introducing them later on, when they are usable

**Comment by erikquinn** [comment]
@jakobeng1303 understood. I would still add them though, just so they are around when the wind starts to shift around, or users are given the option to change the wind, etc. It'd be good to just have the STARs all in place already.

**Comment by Alpi-no** [comment]
@erikquinn I just checked the charts and apparently (I  don't know, whether that's common or not!) the same waypoints are used on both sides! Is that a problem? (http://eaip.austrocontrol.at/lo/160331/Charts/LOWW/LO_AD_2_LOWW_24-5-2-2_en.pdf)

**Comment by erikquinn** [comment]
@jakobeng1303 Which waypoints are the same?

**Comment by Alpi-no** [comment]
@erikquinn I should be more awake when doing this :D sorry, none of them are! I just misread 652 and 952

**Comment by Alpi-no** [comment]
I have so far completed the stars for LOWW. Should I add them and someone merges them later on or should I wait until stars are possible?

**Comment by erikquinn** [comment]
Just hang on to them for now. Shouldn't be but a few days' wait from here.
