### ISSUE TITLE
"pr" shortcut for proceed and full proceed command not understood

### ISSUE THREAD

**Issue by anishthecoder** [zlsa/atc#488]
Somewhere in the last few days, this command seems to have stopped working.

**Comment by erikquinn** [comment]
Actually, it was the last few _hours_ when #464 was merged this morning. :smile: The documentation needs to be updated.

The `pr` command was actually removed, as it is to be replaced with the ability to reroute an aircraft entirely. It's unrealistic to just tack a fix on to the end of a flightplan; instead, a reroute would be given if this was needed, and that is the behavior that is now implemented.

You can achieve the same thing through use of the `reroute` (or `rr`) and the `route` commands. 

The `route` command will make an aircraft go along a route you specify, and then go back to what they were doing (you can use this to "insert" a few waypoints between where he is and where he's going next.

The `rr` command will allow you to rewrite the aircraft's entire route. This will remove everything they filed for, and replace it with whatever route you supply.

Note that the routes are formatted with the dot-joining system, with single dots connecting all procedurally-linked points (eg KSFO.OFFSH9.SXC or SGD.V87.MOVER), and all other points that will be simply a fix direct to another fix need to be connected with double-dots (eg HLI..SQS..BERRA..JAN..KJAN).

So simply, if you are just trying to get them to go from FIXAA to FIXBB to FIXCC, you can tell the aircraft `rr FIXAA..FIXBB..FIXCC`, and they will turn direct to FIXAA, and follow that route. It is also capable of airways, SIDs, and (soon) STARs.
