### ISSUE TITLE
Map scale needed

### ISSUE THREAD

**Issue by lumilux** [zlsa/atc#5]
At the end of the tutorial, I am told that "the closest two aircraft can get is 3 miles"... but there's no scale on the map, so I can't get a sense of any distance.

**Comment by popey456963** [comment]
Leading up from this, maybe it might be helpful to make the scale changeable?  Being able to see those planes that are outside the screen would be incredibly helpful.

**Comment by zlsa** [comment]
I show a ring around each of two aircraft when they're closer than about 4km to each other.

**Comment by zlsa** [comment]
@popey456963, issue #10.

**Comment by zlsa** [comment]
I'll also add a scale in the upper-right corner.
