### ISSUE TITLE
STARs: Landing Runway Transitions

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#500]
STARs need to be able to accomodate transitions for landing runways. In the European style, the connection from a STAR to an airport surface is called a "transition" (differs from the FAA usage, where a transition connects a terminal procedure to the en route structure). In the US, however, the same concept is occasionally applied, via a "landing north" / "landing south" type branch, where a STAR _includes_ two paths, of which the aircraft will follow depending on the runway configuration known to be in use (via listening to the ATIS), or the runway they are told to expect by air traffic control.

Example of need for this in European chart:
![image](https://cloud.githubusercontent.com/assets/5103735/15301728/dc95cd98-1b74-11e6-9528-4e6361c79e6f.png)

Example of need for this in USA chart:
![image](https://cloud.githubusercontent.com/assets/5103735/15301828/638579fc-1b75-11e6-8c7f-f06d0ceec658.png)

**Comment by Alpi-no** [comment]
@erikquinn thanks for the in-depth explanation! Would you expect vectors after "landing" north/south or would you be able to line up  straight away?

**Comment by erikquinn** [comment]
Oh yeah, almost 100% of the time they will be vectored, even on something like that. It just allows the airspace engineers make the same STAR equally convenient for each runway configuration. But still, all it does is get them to a nice altitude on a convenient heading (usually plops them on the downwind descending to 6,000 or so), and then they still get vectors onto the final approach course. Of course, there _are_ often ends of STARs that coincide with IAFs of instrument approaches (convenient example: the HAWKZ4 landing north ends at `SONDR`, which is the initial approach fix for the ILS 34L), but in cases any less convenient than this exact example (like landing south, for example), it doesn't make as much sense to use a procedure to link them to the approach course, when you could just vector them to the minimum distance outside the FAF (usually 3nm), and save the flight potentially more than ten unneeded flying miles. I would consider it rude and lazy of the controller to give a straight-connecting clearance to the pilot instead of vectoring to cut the corner, since it is less efficient for no real reason. The more and more I see procedures outside of the US, the more I realize how much more we use manual vectoring than everybody else... it's interesting. I can see the advantage of both ways, but definitely prefer our methodology to be honest.

![image](https://cloud.githubusercontent.com/assets/5103735/15302208/64e1e68a-1b77-11e6-98e9-5c885f890dec.png)

**Comment by Alpi-no** [comment]
@erikquinn I agree, it's very interesting seeing the differences, however I can't agree with vectoring being better 😆 ;) personally I prefer transitions because I can just say direct a fix so you won't fly any useless miles,and if it's busy you don't have to vector = less work for a controller and therefore more safety!

**Comment by erikquinn** [comment]
Oh you're absolutely right, it's less workload without vectors. I kind of like the chaos though, and the pressure to push every airplane in a tiny spacing window to maximize efficiency, and never be 4nm entrail on final, if you could have been 3.5nm... it's like golf, you can always do a teency bit better! :stuck_out_tongue_winking_eye: Obsessing over getting the last ounce of efficiency out of your airspace is very satisfying when you can do it. And (unfortunately for taxpayers like me), the FAA's solution is not to reduce each controller's workload by modernizing the procedures as much as it is to just make all the sectors smaller and smaller, and add more and more controllers. It's not exactly the most cost-effective strategy in the world... haha

**Comment by erikquinn** [comment]
@Fechulo / @jakobeng1303

[quote from #497](https://github.com/zlsa/atc/pull/497#issuecomment-219515846)

> Right now, it's only necessary to clear them for MABOD 4K, since the are already following MIKOV 7W when they enter the airspace. However, if/when we have en route control, we might need to clear the for both, but we'll leave that to future contributors.  
> -@Fechulo

Just for my reference (I'm a little confused).... if the STARs _don't_ connect to a particular runway, why are there such crazy modifiers on the end of the STARs' identifiers? eg `MIKOV7W`? I figured the reason was to track procedure versioning and runway at the same time... so I get why transitions would have some complicated suffixes, but I don't quite understand why STARs would. Am I missing something?

(in the process of updating the documentation, that's why i'm asking)

**Comment by Alpi-no** [comment]
@erikquinn I suppose that's for 2 reasons: 1. as Europe is pretty crowded, fixes might be used more than once eg Mikov might be important for Vienna, but also for Bratislava (some 60 min east of Vienna). 2. I'm not entirely sure, but it might be, that en route control controls right until Mabod and from there Approach takes over and goes them clearance for the transition. 
[LOWWArrivalSTAR02042015.pdf](https://github.com/zlsa/atc/files/268359/LOWWArrivalSTAR02042015.pdf)
When looking at this chart, the american format of STARs in this game might actually work, but I think this is going far beyond your job as "Tower" or "Approach". Thea area you'd have to cover is too big!

**Comment by erikquinn** [comment]
@jakobeng1303 Yeahhh, i'm just going to have to add runway transitions is how it's looking. I can deal with it. lol

That makes some sense if they're differentiating between airports... FAA just uses different SID names, but since you guys use the _fix_ name, it makes sense you'd have to provide that clarification since they will be different procedures, so I get it.

Another question then:

Let'$ $ay I have lot$ of dollar$, and a private plane, and I want to fly myself from schipol to Bratislava via the following route:
`EHAM.ARNEM1R.UL620.OMELO.L620.KOPIT.M748.ABRAX.T135.MIKOV..?????.LZIB`
[route on skyvector](https://skyvector.com/?ll=48.78466940926718,16.62084962168662&chart=301&zoom=6&fpl=%20EHAM%20IVLUT%20ARNEM%20UL620%20OMELO%20L620%20KOPIT%20M748%20ABRAX%20T135%20MIKOV%20LZIB) / [eham charts](http://www2.vlieghinder.nl/knipsels_pmach/pdfs/EHAM.pdf) / [vienna stars](https://github.com/zlsa/atc/files/268359/LOWWArrivalSTAR02042015.pdf) / [vienna transitions](http://charts.vacc-austria.org/LOWW/LOWW_Arrival_RNAV%20Transition%2011_03032016.pdf) / [bratislava charts](http://vacc-slovakia.sk/downloads/charts/LZIB_ALL_in_one.pdf)

I'm at MIKOV, and I want to follow the chart out to TOVKA, which I assume is used for LZIB.
![image](https://cloud.githubusercontent.com/assets/5103735/15326916/4fb16e68-1c15-11e6-9a5c-61d7e9d72cf0.png)
The charts seem to show that I would go `MIKOV -> MIKOV 7W -> TOVKA 2W -> TOVKA`. Is that what the route would be? I'm asking because if there are multiple stars, PLUS a transition, it is really not set up for that at all.

**Comment by Alpi-no** [comment]
The stars are the links between transitions and en route control on a specific airport! You musn't use them like regular airways. I checked the Bratislava's stars and the only one from the west seems to be Koxer1R. You could either go via this one, or the probably more efficient, Berva3R. However, you could use Tovka to depart Bratislava! `ARNE2P.ARNEM.UL620.KOMUR.KOPIT.DIXEP.ABRAX.BNO.BERVA.BERV3R` 
or 
`LUNI1P.EDUPO.UZ738.MISGO.UZ741.GMH.UL603.TESGA.UN858.MASEK.UL604.SULUS.UZ650.NIKUS.UM736.AKOSI.UQ309.DOSEL.UL605.ESEGA.KOXER.FMD` the last one could be more efficient, but simbrief decided to make it a little weird

**Comment by Alpi-no** [comment]
@erikquinn to be fair, after all this I don't believe the US and EU version is too different!

**Comment by erikquinn** [comment]
yeah, seems like it's just in what they call it, and how often they use it.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
