### ISSUE TITLE
help: how to re-sync my gh-pages with zlsa/atc/gh-pages

### ISSUE THREAD

**Issue by ghariman** [zlsa/atc#507]
Hi,

I don't know how to sync my gh-pages so it is the same as zlsa/atc/gh-pages.

Can somebody help please?

Thank you.

**Comment by erikquinn** [comment]
@ghariman getting it set up is actually a relatively lengthy process. I'd love to help, but would you mind if we did so on the zlsa/ATC gitter? It's basically a chat room that's a lot easier to work in for long conversations and will be easier on people's email inboxes. :wink:

I'll be on there and am ready whenever you are. [zlsa gitter](http://gitter.im/zlsa/atc), and no need to set up an account or anything, you can just choose "log in with GitHub".

**Comment by ghariman** [comment]
Erik helped me a lot. Thank you so much.
