### ISSUE TITLE
Clearing to climb via SID tells the aircraft to descend via departure

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#509]
Doing <aircraft> cvs seems to tell the aircraft to **descend** instead of **climb** via the <blah> departure at EBBR. I don't know if this is the same for other airports. It's reproducable at EBBR with version 2.8.1.

Screenshots if required:
http://prntscr.com/b56e7t
http://prntscr.com/b56gbf

**Comment by erikquinn** [comment]
Yeah, that was my mistake... it will be fixed by the merge of #506. :smile:
