### ISSUE TITLE
Is it possible to hide fixes?

### ISSUE THREAD

**Issue by Alpi-no** [zlsa/atc#534]
I don't want the to sound silly, but is it possible to hide fixes? I want some fixes to still work, but I don't have to see them to use them

**Comment by Fechulo** [comment]
You can't hide fixes in-game, however if you add a '_' at the beginning of the name of a fix, the fix will not be drawn.
Example:
original - "WOBUN": ["N52d01m10.00", "W0d43m60.00"],
hidden- "_WOBUN": ["N52d01m10.00", "W0d43m60.00"],

**Comment by Alpi-no** [comment]
ah thanks! That was what I was looking for!
