### ISSUE TITLE
Change SID drawing to be based on runway in use

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#553]
In accordance with discussions on #438, the `draw` sections should be changed to draw SIDs on the scope for the runway in use only.

> That's a good idea. What about taking it one step further, and instead of making the user select the runways to show SIDs from, we either:
> - show available SIDs only valid from the runway the aircraft is currently using, on, or planning to use
> - show available SIDs only valid from the runway best aligned with the wind (`airport_get().runway`)
> 
> And believe it or not, performance would actually IMPROVE from something like this, because the logic and the drawing is fully re-run each frame, so if only drawing a portion of the SIDs (the slowest part, by miles), the game would also end up running more smoothly.

Example of the implementation, from @headphase:

> Here's a thought piggybacking off of @Fechulo 's post...  
> Right now the blue guidelines are defined in one lump under the "draw" section of each SID..  
> Would it be at all possible to move those arrays to a new part of the airport's json file (maybe "guidelines"), so instead of grouping the lines by SID, we group them by _runway_?  
> My thinking is that we could then build a simple panel in the UI with on/off toggle buttons for each runway.  When "13R" is selected for example, the blue lines are displayed for all SIDs departing 13R.  
> Here's how it currently is:  
> ![draw1](https://cloud.githubusercontent.com/assets/6735197/14440140/9a305c40-fffc-11e5-8a59-0e9faa68e015.png)  
> And here's my idea:  
> ![draw2](https://cloud.githubusercontent.com/assets/6735197/14440244/0b606bda-fffd-11e5-8acd-5085c081d953.png)  
> (where all starred fixes are flagged transitions)  
> Is this concept possible?

**Comment by Fechulo** [comment]
@headphase I completely forgot you were working on KBOS, and for the last week or so I've also been working on the same airport! Did you continue to work on it? Since #438 almost all procedures at KBOS have changed; Mine is up-to-date and almost ready to merge.

**Comment by eliuuk** [comment]
I definitely prefer this, but in VIDP (Delhi), most of the SIDS overlap each other, as in the text overlap each other which would almost make this useless. Any chance on preventing text overlap? Additionally, what if an airport is using 2 runways? Amsterdam, for example will sometimes use 36L and 27 for takeoff and 06 for landing.

**Comment by erikquinn** [comment]
The idea would be that if no aircraft are selected, whichever runway the game chose will have its lines shown. If you taxi an aircraft to a different runway, when you select the aircraft, the lines for the runway you assigned will be shown until you deselect them. At least that's the current thinking.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
