### ISSUE TITLE
Game crash when aircraft re-exit the airspace

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#557]
[Here's](https://www.youtube.com/watch?v=_6kfG-tPqrQ) a video!

**Comment by erikquinn** [comment]
Note for later: This is due to the way they are rerouted. It assumes there will always be a SID assigned, and when rerouted, it looks for the SID and can't find it as the first leg in the fms. That will have to be fixed.

**Comment by erikquinn** [comment]
@Fechulo Do you still have this video?

**Comment by Fechulo** [comment]
@erikquinn It looks like I deleted the video at some point, however I don't think this is still happening.

**Comment by erikquinn** [comment]
Okay good. It sounded like something that was fixed. Closing. :)
