### ISSUE TITLE
Review by DonSeawolf

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#558]
I found a [review](https://www.youtube.com/watch?v=mj41IeFuejo) of this game on YouTube, by DonSeawolf. The review is in German but I understood most of it. He had previously reviewed Aerosoft's Global ATC Sim, so he often compares the 2, always bearing in mind that our game is free. The video was made in January 2016, so many of the things he points out have changed.

**Here's a 'short' summary of the review:**
-He first describes the radar screen (fixes, range rings, command bar, etc.)
-He points out that although the most important fixes are present, there are many fixes which are missing, specifically those necessary for transitions:
![fixes](https://cloud.githubusercontent.com/assets/13125311/15808282/b200eff2-2b6b-11e6-94e4-e4bc7220ddf4.PNG)
-He talks about the speech synthesizer not working for him. (possibly fixed now?)
-There are not as many airports as in Aerosoft's Global ATC Sim (A lot of new airports have been added since then)
-He found the tutorial very helpful and easy-to-use.
-Talks through the commands used for departures

The reviewer then proceeds to give his opinion on certain aspects of the game.
**Here's a list of the things he likes about the game:**
-Number of fixes is OK, not too over-crowded (He may not like the new version of EDDM, or LOWW)
-It is 100% free!
-A lot of variety and realism regarding the airlines at EDDM. (Unlike Areosoft's ATC, where traffic is the same regardless of the airport)
-proceed command is pretty cool (replaced by route and reroute)

**Here's a list of the things he does NOT like about the game:**
-Initial altitudes have to be assigned which is not realistic since this is described in the charts (fixed with the 'caf' command)
-The player must give the aircraft clearance and taxi instructions (The role of the player has already been discussed, though not much has changed)
-many fixes are missing at EDDM, which makes it impossible to assign transitions to final approach (like the transitions discussed for LOWW)
-No climb/descent rate indication (I believe that ATC in Germany can give an aircraft the instruction to climb/descend at a specific rate; this isn't common anywhere else)
-altitude is unrealistic (EDDM's elevation is 1487ft, so aircraft on the ground who appear to be at 0ft, would actually be underground; Also affects the altitudes at different points of the ILS)
![elevation](https://cloud.githubusercontent.com/assets/13125311/15808542/95e42d56-2b71-11e6-93ed-384f34a85695.PNG)
-aircraft spawning at 9500ft is very unrealistic (jokes about ATC telling an aircraft to climb to 9370ft)
-Inability to move flight-strips (These have changed lately, moving them around is still not possible)
-WIP tag doesn't have a meaning. EDDM has a WIP tag while EHAM doesn't, and both airports are at a pretty similar state (WIP tag at EDDM has been removed, EHAM remains unchanged)
-Difficulty is unrealistic (According to the game, EDDH has more traffic than EDDM, which isn't realistic)
-Lack of tool-tip for the windsock (unsure if the speed is in kts)
-Player can't see where the aircraft is taxiing.

**Overall impression of the game:**
Despite his complaints, he really enjoys it and definitely recommends it to everyone, as it is great fun and free. Compares it to Aerosoft's Global ATC Sim, and thinks ours is better in many aspects.

**My thoughts:**
Some of the issues he mentions are really small and easy to fix. Some other ones have caught my attention, and encouraged me to think of possible solutions:

Climb/descent rates: We could add 2 new commands - 'rate' and 'sayrate' - These would allow players to control the climb and descent rate of aircraft. Example usage: AAL123 rate 2500 (tells AAL123 to climb at a rate of 2500ft/min; negative rates could be used for descent, e.g., AAL123 rate -2500). The 'sayrate' command could work the same way the 'sayroute' command works.

Unrealistic altitudes: We could add an option to the options menu to chose between simplified and realistic altitudes. Similar to the simplified airspeed, simplified altitude would remain the same, while realistic altitude would take the airport elevation into account.

I have encouraged DonSeawolf to play the new version of the game and check out this GitHub page and take part in discussions. Let me know what you think!

**Comment by Alpi-no** [comment]
I agree with everything mentioned however, I want to add 2 points: 
1. an issue we might have in the future is the "playability" of the game! We don't have any sort of documentation provided, which some airports desperately need, to be able to play it! 
2. I'm not sure whether that would work, but having a sort of GND/TWR sim and an Approach/director sim would be cool to have. You would have the layout of the airport and clear planes to land, taxi, startup, pushback and takeoff

**Comment by Fechulo** [comment]
The possibility to controlling Ground and other facilities has already been discussed in #128 , however no significant changes were made. Lately, some features were added, which could eventually facilitate the implementation of a center controller, e.g. the new route system or the possibility to add airways, though they're still not useful.

**Comment by GlenBush** [comment]
I know nothing of ATC i ran across this game searching for an alternative to learning all the intricate details of air traffic control. If you watch my debug videos I posted on YouTube you will quickly see that I have no clue about the rules other than keep the planes from running into each other. I find this game fun to play at the current state. If you were going to add a new feature to this game I would suggest creating a multiplayer; allowing someone to connect to my running sim to help. this is the only way i see any other features working as one person has their hands full with the departures and arrivals as it is now. I would like myself to off load my departures to another person all ready.

https://www.youtube.com/channel/UCLY9Z3XfJTOF51pJNY6oFxQ

**Comment by DonSeawolf** [comment]
Hello Everyone,

first off all, I'd like to say, that i am honored, that one of the developers watched my video and that you guys care about my opinion. 

For a better understanding of my point of view:
I am a RL air traffic control officer, though I decided that its not what I want to do the rest of my life, so I am now studying "game design".
I worked as an upper airspace controler (center/area control) but I also learned a lot about approach and tower during my training.

What you wrote in the first post pretty much sums it up. 
I do realize, that its difficult to find the balance between simulating real life and having a game thats playable for casual gamers as well.
You did a really good job so far and I would love to contribute to the further development process if you  are interested in my thoughts.

I made an english tutorial as well [https://www.youtube.com/watch?v=NooxbCLsgAQ&feature=youtu.be](url) and I will start work on a new english review of the current build. Maybe we can work out a plan where I and maybe other YouTubers can produce videos that explain and cover all the new stuff when the game was updated.

**Comment by Fechulo** [comment]
It's great to finally have a European real-life controller, since all of the controllers who contribute to the game are American and procedures are very different. We are definitely interested in any suggestions or thoughts you may have and I'm looking forward to the updated English review!

**Comment by GlenBush** [comment]
@DonSeawolf  I liked the English tutorial, I agree the change to the string is needed. I was not aware that the landing clearance was the towers job but if so than that is a minor change in syntax to the string and an easy fix to maintain immersion for people that know about these things.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
