### ISSUE TITLE
Aircraft somehow 'crash' and stay on the radar

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#566]
For some reason, I've just had this aircraft in the simulator that was cleared for takeoff, and for some reason just randomly 'crashed'.

http://prntscr.com/bedekh

The aircraft was climbing, and all of a sudden, it was at 0 feet at 0 knots.

Error console is here: http://prntscr.com/bedfl8

I can also assure you that all of the SIDS have ICAOs!

EDIT: After 7 minutes, for some reason I'm able to clear it for takeoff from it's current position too...

**Comment by erikquinn** [comment]
I'd have a close look at the SID he was using, as it may be that the fms thought there was an altitude and speed to comply with, but they weren't given a value, so it assumed zero... that theory would explain the behavior at least. Strange though.

**Comment by erikquinn** [comment]
@indianbhaji Are you able to reproduce this?

**Comment by eliuuk** [comment]
I can't say, this issue is very rare it seems.

**Comment by erikquinn** [comment]
Closing due to lack of reproducibility. :disappointed:
