### ISSUE TITLE
SID text overlaps

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#576]
Whenever multiple SIDs share the same exit point, the SID name and exit point are written on the canvas at the location of that exit point, causing overlapping text. Logic could be added that would check to see if multiple things are trying to be written to the same location, and then have subsequent items offset above and/or below that position, resulting in a "new line" for each SID that ends at the shared exit point.

![image](https://cloud.githubusercontent.com/assets/5103735/16014857/b2723eb2-3158-11e6-8b51-b9cd682ddaec.png)

**Comment by aldent95** [comment]
Got sick of this when trying to create Auckland International Airport (NZAA) so I went ahead and fixed it. Open to any suggestions to improve the fix.

![sids](https://cloud.githubusercontent.com/assets/8398954/17773489/d6ddff4c-65a2-11e6-858a-f62117c7bb7a.PNG)

**Comment by eliuuk** [comment]
@aldent95 Looks great, I can't think of anything else to improve it though!

**Comment by erikquinn** [comment]
Resolved, thanks to @aldent95's work on #643. Closing.
