### ISSUE TITLE
Routes?

### ISSUE THREAD

**Issue by Alpi-no** [zlsa/atc#589]
I was wondering whether it would be good/useful to have `route`s. 

The difference to "old" routes eg stars is mainly that you don't have transitions and different phrasing. You would clear like `r(r) BALAD3K` or something like that. The general use, I suppose, would be stars that are different to US stars and routes that are more complex or routes in enroute control.
If possible we should add the ability to add more complex procedures to a route, like `hold`, `if (functions)`, `land`, different waypoints (ones you have to overfly, ones you don't), as well as go around procedures (maybe the plane could even call the ATC and tell them!). I think most of them are pretty obvious except for if functions. i think they will be used for altitude checking (holding if not below/above a certain altitude) or activation of go a round procedures if ILS wasn't caught or something like that.

As I don't have the skill to work on this project, I would have to ask someone else to do so!
Is there anyone interested in working on these? 

What do you think about about this, is is possible and worth the work or is there anything to add?

**Comment by tedrek** [comment]
@jakobeng1303, yes it would be good/useful to have routes and it something which is being worked on.

As of right now, there is a `route` command in the game which can be used for giving an aircraft a list of procedures to follow.  It is limited to assigning a sequence of direct to fix, Airway segments, STARs, and SIDs.  No airport has yet implemented airways though.

The implementations of SIDs and STARs include the ability to specify altitudes and speeds along the procedure.  However as controller you don't have the ability to access that functionality, #315 had some relevant discussion.

As we implement the various features they are generally being done in a way that any procedure can make use of them.  Unfortunately we don't have a lot of programmer time working on the game right now so progress will be slow.  I get the impression you don't think of yourself as a coder.  If you have any inclination to program though, I would be happy to review your code and help you learn.  Other useful things can be thinking through how exactly the features should work (for example if the controller tells an aircraft their route is XYZ then is the aircraft also clear to fly all of XYZ or will further clearances be required?)
