### ISSUE TITLE
Speed and altitude changes not applied

### ISSUE THREAD

**Issue by Phil57** [zlsa/atc#60]
When a aircraft has a fix for destination, speed and altitude changes are not applied. Only the stripe is changed. As soon as you type 'abort' or assign a heading, speed and altitude changes are applied.

**Comment by Diastro** [comment]
Would you happen to have exact steps to repro this? I have experienced this
during "longer" games but never been able to repro this on the spot...

Also if you are able to repro can you check the console to see if there are
any js errors.

It would be much appreciated.
Thanks

**Comment by Phil57** [comment]
Example on the Debug Airport:
- F ABOFA (Works great)
- S XXX C XXXX (Only the stripe is updated)
- Abort or H XXX (speed and altitude changes from the previous command are finally applied)

If flying a heading and not a fix, no issue.
I don't see any JS error in the console.

Tested on Chrome 40 and Firefox 35.

It worked as expected yesterday.

**Comment by Diastro** [comment]
Great thanks.

@zlsa i guess this was also affected by the changes we merged yesterday...

**Comment by zlsa** [comment]
Fix in progress.

**Comment by Phil57** [comment]
Looks good, I'll play a bit and come back here if anything is wrong.

**Comment by Diastro** [comment]
Thanks @phil57 @zlsa
