### ISSUE TITLE
Commands are case sensitive

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#620]
It appears that commands are case sensitive;
ie. QTR508 I 16R
= Command not understood

QTR508 FH340
= Command not understood

but...
QTR508 i 16R
= QTR508 cleared ILS 16R approach

QTR508 fh340
= QTR508 fly heading 340 degrees

**Comment by erikquinn** [comment]
I have also noticed that attempting to recall a previously entered command (via the PgUp key) will re-enter it in upper case, which also means it fails to be recognized by the parser.

**Comment by aldent95** [comment]
Looks like all it took was a .toLowerCase() on the end of prop.input.command when it gets passed to the Parser.
