### ISSUE TITLE
Various issues and thoughts

### ISSUE THREAD

**Issue by darssy** [zlsa/atc#627]
I've been using that game for some time and I have some thoughts I would like to share:
1. **Aircraft performance**: While playing at KSFO I've noticed that a departing B744 was climbing 100ft for every 6 approximately at FL100, which makes us 1000fpm. That's very low. B744 makes 2000fpm at this altitude **at worst**. It can make as much as 4500 fpm at most. Also the speeds increase very rapidly after FL100. I've seen a B739 making 460Kts at FL160 while it should make something around 350
2. **Radar Accuracy**: ATC radar screen shows ground speed not TAS or IAS. But this is a bit blurry in the game: planes seem to follow the 250 restriction IAS but this results in 250 on screen which is ground speed. Also the screen seems to be refreshed very frequently (every 500ms I think) but this is so untrue. Approach radar periods are ~4 secs, ACC radars are at 10 secs and ground radars are at 1 sec (no sure for this one though.
3. **Labels (aka data blocks)** Different color for departures and arrivals is very good. But implementation could be better. Why not make the data blocks transparent, get rid of the vertical line and make **the letters colored?** Don't know just a thought. That's what I've seen in real systems though.
4. **Clock** That actually should have been first. Having a clock showing a time (any time) is more than necessary. Time is a means of separating planes. And a means to know if a flight is on time or not ;) Speaking about times, taxi times are unrealistically small...
5. **Distance measurement**: Measuring distances is vital for an ATCO. And not being able to measure distances, means separating flights "with the eye" which is a big no-no.
6. **Route ploting**: Asking the plane to report route should be unnecessary in most cases. Modern CWPs can show the route of a selected track. Something similar could be done here?
7. **ILS interception angle** AFAIK in Europe threshold is 45 degrees. Some pilots can even intercept on steeper angles if they they think they should, but 45 is the limit not 30.

Sorry if I missed some of those, though I think that I've searched some of the issues and found nothing relevant.

Would love to hear your thoughts on these. Cheers.

**Comment by eliuuk** [comment]
1) This could be improved, as the aircraft layout hardcodes a climb rate 
for an aircraft (I believe). Maybe adding variation would be useful, but 
then this would depend on weights.
2) A command to report IAS would be nice too. The 250 IAS rule should also 
be avoidable and be open to being overwritten by ATC in my opinion, maybe 
for high speed departures?

3) Although maybe slightly unrealistic, I do prefer the current layout of 
the datablocks.
4) A clock would be useful, but timewarp will make time seem to go too 
quick, which might make seperation difficult! Taxi times do definitely need 
to be longer - the abort command would actually be useful in this case!
5) We definitely need this, something like the seperation tool on Euroscope 
would be nice!

**Comment by ghost** [comment]
Yes clock please! I'd like to know how much longer I have on a shift... I've never fully completed a shift before, I quite at 800 points with still a load of planes coming into O'hare.

**Comment by erikquinn** [comment]
The shift is infinite actually, so if anybody fully completed one, that would be quite an accomplishment! haha

There are a LOT of good points in this one. They can be moved up in the queue and dealt with soon. Particularly the clock! That's a pretty easy addition.

**Comment by erikquinn** [comment]
Item 1: covered by #682.
Item 2: This has since been added as a feature, and can be enabled in the settings menu.
Item 3: Will be dealt with in #716.
Item 4: Added #739 for this.
Item 5: Added #740 for this.
Item 6: The existing logic that draws dashed lines out along the route should be updated (pretty sure it doesn't work right if I remember). It broke somewhere along the way. Created
Item 7: The FAA standard is no more than 30 degrees provided that they establish at least 3nm out from the FAF, or 1-3nm out on a 20 angle. A 45 degree intercept is used for helicopters though. Regardless, that is the rule set we will be sticking with. Maybe one day decades from now we'll have multiple rule sets, but for now there will be no change on this item.

That should address all of them. I'll close this issue since it has now been dispersed and can actually be worked on. :smile:

**Comment by darssy** [comment]
Hello erikquinn,

That's very good to see that my comments have finally been taken seriously 😄 
But I have 2 remarks:

Regarding 2, apart from the speeds, the refresh rate is also significant. It's very important and new ATCOs are trained to have this in mind.

For 7 and since the game has lot's of airports in Europe, you should also consider 45 degrees. How am I so sure? Read below 😉  In any case since I couldn't find any _documentation_ for that, I've posted a [question](http://aviation.stackexchange.com/q/33306/878) so you might be interested in watching it :)

If you think that you need any help (besides coding since 1. I am allergic to js and 2. I've seen some code and it gave me a headache 😄  ) just drop a line, I'm the creator of [DARSSY](http://darssy.com/) and I could help you since for many things I've been where you are now.

Happy coding

**PS:** It seems that the question has already been answered, 45 degrees is the limit 😉

**Comment by jaccovanschaik** [comment]
> For 7 and since the game has lot's of airports in Europe, you should also consider 45 degrees.

I only know about Schiphol airport, but I'm sure the standard intercept angle is 30 degrees here too.

**Comment by erikquinn** [comment]
@adamstyl WOW, DARSSY looks incredible! We would love your input and be able to reach out occasionally for questions if you're willing? 

> Regarding 2, apart from the speeds, the refresh rate is also significant. It's very important and new ATCOs are trained to have this in mind.

Absolutely agreed. I've wanted this for a while, and apparently there's no issue for it. Added #741.

> For 7 and since the game has lot's of airports in Europe, you should also consider 45 degrees. How am I so sure? Read below :wink: In any case since I couldn't find any documentation for that, I've posted a question so you might be interested in watching it :)

Well I'd love to have the option to do either, but we don't have the capability to have multiple rule sets. Since we have to pick one, we will choose 30 degrees, as it is somewhat overrestrictive for airports that allow 45 degree intercepts, as opposed to the reverse, where "illegal" approaches (>30) or more would not be penalized at airports that don't allow it.

**Comment by n8rzz** [comment]
@adamstyl you must be joking about the js allergy, you have a javascript API for DARSSY.  

Have you looked at the code here recently?  We're using ES2015 now, so it looks much more like c# than it does old-school js.

**Comment by darssy** [comment]
@erikquinn  Thanks :smile: Sure but please bear in mind that I won't have answers for all questions. But yes if you stumble on something that it can't be asked (or it's not already answered) on aviation stack, drop a line. I hope I would be able to help or give some idea. :smile: 

@n8rzz No unfortunately not :disappointed: I did it (not 100% but at least it was something working), users didn't embrace it as much as I wanted and in general it created more problems than it solved. I want to promptly replace it with a DSL specifically designed for that purpose. But time doesn't allow that for now.

Last time I checked the code it was about 5 months ago, then other things consumed me. There were some things that confused me. For example I wanted to find the refresh rate of the screen to reduce it to 4 seconds and _I think_ that I saw this mixed with the aircraft model refresh rate. That made me stop since I realized that significant refactoring would be needed to decouple the two.

Then I was looking to fix the projected trajectory issue (if you notice, the turns are recalculated every now and then) and again I saw that the rendering code was entangled to the computational part and that also made me quit the effort.

I don't know maybe it's just me, I am not used to the JS mentality, but I thought that the aforementioned issues should have been more straightforward. Again IMHO.

@jaccovanschaik I don't question the standard. I question the limit. If it's 35 for example, planes refuse to intercept. That's not normal. And let's not forget that the pilots themselves want to land that thing as soon as they can, they can't refuse approaches for a couple of degrees or 5...
