### ISSUE TITLE
Radar scope circles got lost

### ISSUE THREAD

**Issue by luznicky** [zlsa/atc#628]
During designing TMA (picking, reformatting and finally adding coordinates to the list) radar scope circles got lost.
Now during loading I can see a warning `[ INFO ] Unable to parse coordinate 13.943192800` in a log. Although string 13.943192800 is nowhere in source tree. But I'm certain that during development I had this badly formatted coordinate string present.
In browser's anonymous mode the circles are present.

**Comment by Fechulo** [comment]
@luznicky That's interesting... Could you show us the code for the TMA? Without it, there's not much we can do.

**Comment by luznicky** [comment]
`
  "airspace": [
    {
      "floor": 0,
      "ceiling": 165,
      "airspace_class": "D",
      "poly":[

```
["N50d35m48.47", "E013d47m59.46"],
["N50d36m28.26", "E014d42m03.35"],
["N50.4109221", "E15.0304127"],
["N50.243794200", "E15.142918900"],
["N49.972456400", "E15.148963000"],
["N49d54m54.10", "E015d07m31.76"],
["N49d51m12.52", "E015d05m15.77"],
["N49d47m20.15", "E015d14m23.01"],
["N49.743947500", "E15.200280500"],
["N49.654260100", "E15.103083900"],
["N49.600334700", "E15.026928100"],
["N49d30m35.74", "E014d51m22.83"],
["N49d34m47.95", "E014d41m08.45"],
["N49d32m16.69", "E014d31m39.01"],
["N49.514679200", "E14.218023000"],

["N49.552341300", "E13.943192800"],

["N49.607275000", "E13.775603900"],
["N49d37m09.15", "E013d44m46.01"],
["N49d31m00.59", "E013d24m48.73"],
["N49.559065600", "E13.350744600"],
["N49.692945900", "E13.197219900"],
["N49.692945900", "E13.197219900"],
["N49.884182500", "E13.069939000"],
["N50.090025400", "E13.022715500"],
["N50d10m25.68", "E013d01m39.70"],
["N50d10m54.53", "E013d22m06.38"],
["N50.330173700", "E13.432962600"],
["N50.506361200", "E13.618002900"]
  ]
}
```

  ], 
`
You can see the waypoint in the middle. You can even remove it, but with no effect.

**Comment by Fechulo** [comment]
The coordinates look fine... Using incognito mode is usually better, as it guarantees that your changes will be visible. Chrome often saves the old code and doesn't use the new code if it isn't set to incognito. If the range rings come up on incognito, then it's probably working. just in case, make sure that the range rings radius is set to 5: 
![rr](https://cloud.githubusercontent.com/assets/13125311/17193679/14404e16-544c-11e6-99c8-e0377db50690.PNG)

**Comment by luznicky** [comment]
The range rings radius is set to 5. So in my opinion it's definitely problem with Chrome's cache.

**Comment by Fechulo** [comment]
But it works when you use incognito mode, right?

**Comment by luznicky** [comment]
Yes.

**Comment by Fechulo** [comment]
Well. then it's fixed, except for the coordinate warning. Is the TMA the only place where E13.943192800 is used?

**Comment by erikquinn** [comment]
@luznicky Is this issue resolved, or is it still giving trouble?

**Comment by luznicky** [comment]
Hi,
I'm not able to reproduce it. I think that it's somehow related to Google Chrome cache. My be a reminder in a wiki could be useful for other, as you can probably encounter this problem when developing new airport.

**Comment by erikquinn** [comment]
@luznicky understood! added some comments ref. hard refreshing and caching with chrome to the wiki new contributors page. Marking this issue as resolved.
