### ISSUE TITLE
Automatic wind updates?

### ISSUE THREAD

**Issue by willfrd** [zlsa/atc#630]
I was wondering if it could be posible to for the simulator to update the wind automatically (if metar is available for the specific airport). e.g. from one of this metar networks (which gets updated every five minutes normally):
NOAA: http://www.aviationweather.gov/static/adds/metars/stations.txt
Vatsim: http://metar.vatsim.net/metar.php?id=all
Ivao: http://wx.ivao.aero/metar.php
Note: I don´t know if the use of this is protected by copyright, restrictions etc...
This could be done by writing a script for our simulator to interpret the information and use it in the selected airport to apply the lateset wind and if it doesn´t find a metar for the airport use the wind that was originally set in the airport file. I must say I have no knowledge whatsoever to write a script of this characteristics I really think this could make the simulator considerably more realistic, but I would like to know how viable this idea would be.

**Comment by eliuuk** [comment]
Wind updates is a good idea, but it isn't always that there is wind information for an airport. For example, what would you do in the case that the METAR states "VRB03KT"? This suggests the wind is changing too much to determine, so how would this be simulated?

**Comment by willfrd** [comment]
In that case the wind that could be used is the one pre-set on the airport .json or randomize the direction?

**Comment by Alpi-no** [comment]
would it be possible to include different information for the wind penalties for arriving/departing aircraft per airport as well? To make like a big weather update to the game

**Comment by willfrd** [comment]
Nice idea but as I mentioned before I have no idea on how to code a script like this, so I don´t surely know if it can be done...

**Comment by eliuuk** [comment]
Everything is possible, pretty much, there just needs to be some thinking on this to make it work.

**Comment by willfrd** [comment]
Nice to know, thanks :-) I consider my thinking is done but will think a bit more in the ideas to see if they are improvable.

**Comment by erikquinn** [comment]
Covered by #68. Closing.
