### ISSUE TITLE
New Airport Request: TJSJ

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#637]
A request was made for Luis Muñoz Marin (San Juan, PR) by @exfil in #634. @Fechulo said he was on it! Creating this issue so it doesn't get forgotten when I merge and close #634.

**Comment by Exfil** [comment]
Thanks!

**Comment by Fechulo** [comment]
@Exfil The airport's finished! While it's being reviewed, you can test it [here](https://fechulo.github.io/). I hope you like it!

**Comment by Exfil** [comment]
Nice :) Thanks a alot man!
