### ISSUE TITLE
New Airport Request: KORD

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#646]
Issue for tracking progress on O'Hare.

@Fechulo I was able to get a hold of a *.sct2 file for you. If you know the runway configuration you'd like it to be set up for, I can send the finished `maps` section your way with the corresponding arrival corridor markings. Should be a quick and painless reformat, so just let me know! :smile:

**Comment by Fechulo** [comment]
Wow, Thanks!

I'm using westerly runway configuration (27's + 28's). I also need the coordinates for the C90 TRACON which should be in there as well. I still haven't received admin approval for the vZAU forums, so this would be very helpful.

Thank you! :smile:

**Comment by erikquinn** [comment]
@Fechulo Rogga! Done.

[Click here for C90 maps section](https://github.com/zlsa/atc/files/428085/maps.txt)  
The above file includes the following video maps:
- "C90 MASTER (28R/10L)"
- "C90 (WEST FLOW)"
- "C90 Visual Approach Boxes"
- "SIMUL CAPTURE POINTS"

You may also just get the [ZAU *.sct2 file](https://www.dropbox.com/s/4ybe5dulibzhr5d/ZAU%20Mega%20Sector%204.1.sct2?dl=0) and work with it directly if you prefer.

PS: I do not have any documentation outlining stratification or shelving, so you could maybe find that, or else just guess at an appropriate looking border for the airspace.

PPS: There are ~26k lines to be drawn on this VM (it's 99% the fault of the detailed base map), so it may be laggy... recommend having a look at performance, and if it's rough, maybe we can find a way to simplify some of the geometry to reduce the number of lines to be redrawn with each frame.

Enjoy! :smile:

**Comment by Fechulo** [comment]
Thank you so much!! I need to get some sleep now but I'll take a look at it tomorrow.

**Comment by erikquinn** [comment]
Merged O'Hare via cea5778 via PR #648. Closing.
