### ISSUE TITLE
Blocking command line

### ISSUE THREAD

**Issue by Diastro** [zlsa/atc#65]
Not sure why.... While working on issue #46 I came across this.

After making an aircraft taxi to a runway, if you type the following command **(with the typo in it)** the command line wont allow you to press enter... 

Repro (after making aircraft taxi) : BAW629 climg 7000 takeoff

**Comment by zlsa** [comment]
Ooh, that's a neat bug.

It splits the string by whitespace, then by commands; for example:

```
[["climb", "7"], ["takeoff"]]
```

However, since "climg" is an invalid command, it tries to append "climg" to the previous command, which doesn't exist. Fix in progress.

**Comment by Diastro** [comment]
Hahah sweet! Thanks @zlsa
