### ISSUE TITLE
Update old European airports?

### ISSUE THREAD

**Issue by Alpi-no** [zlsa/atc#650]
I have been going through many european airports today and I realised, most of them are pretty outdated and don't live up to our standards (stars/transitions, terrain,...). I currently don't have time to work on them but if anyone has, I think EGLL, EDDF and EHAM should be updated first. 
Maybe we should start a checklist or something similar to rework some airports.

**Comment by eliuuk** [comment]
EBBR needs to be finished too.

**Comment by Alpi-no** [comment]
It's not just EBBR, I think it's basically all the European airports but Vienna

**Comment by eliuuk** [comment]
EBBR still has NORTH, SOUTH, EAST, WEST SIDs though :p

**Comment by eliuuk** [comment]
I'll start with EHAM now

**Comment by Alpi-no** [comment]
I think we should do this in 3-4 stages being 1: sids and stars currently in use (depending on the wind) 2. transitions 3. FIR zone & terrain 4. whatever is left 
I think only 1 and 2 should be done at the moment because they cover the basics and as the wind doesn't change, we don't technically have the need for all transitions

**Comment by Fechulo** [comment]
Here's a list of the changes that have to be made to European airports:

**EBBR**:
- Update SID's + STAR's (SID's are not RNAV which makes it difficult to recreate in the game)
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EBBR)
- Reallistic airspace
- Charts can be found [here](https://www.belgocontrol.be/opersite/eaip/eAIP_Main/html/index-en-GB.html)

~~**EDDF**:~~
~~\- Update STAR's~~
~~\- Terrain~~
~~\- Charts can be found [here](http://nav.vatsim-germany.org/files/edgg/charts/eddf/public/EDDF_AIO.pdf)~~

~~**EDDH**:~~
~~\- Update STAR's~~
~~\- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EDDH)~~
~~\- Charts can be found [here](http://nav.vatsim-germany.org/files/edww/charts/eddh/public/EDDH_AIO.pdf)~~

**EDDM**:
- Update STAR's
- Terrain (Close to the Alps, should be interesting)
- Charts can be found [here](http://nav.vatsim-germany.org/files/edmm/charts/eddm/public/EDDM_AIO.pdf)

**EDDT**:
- Update STAR's
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EDDT)
- Charts can be found [here](http://nav.vatsim-germany.org/files/edww/charts/eddt/public/EDDT_AIO.pdf)

**EGCC**:
- Update STAR's
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EGCC)
- Reallistic airspace
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=99&Itemid=148.html)

**EGGW**:
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EGGW)
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=95&Itemid=144.html)

**EGKK**:
- Update SID's + STAR's (All procedures were recently changed)
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EGKK)
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=93&Itemid=142.html)

**EGLC**:
- Update STAR's
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EGLC)
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=92&Itemid=141.html)

**EGLL**:
- Update STAR's
- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EGLL)
- Improve traffic
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=94&Itemid=143.html)

**EGNM**:
- Add Terrain!
- Charts can be found [here](http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=88&Itemid=137.html)

~~**EHAM**:~~
~~\- Update SID's + STAR's (There's 80 SID's!!!!!!)~~
~~\- Terrain? (I don't think there's any terrain higher than 1000ft in the area surrounding EHAM)~~
~~\- Reallistic airspace~~
~~\- Charts can be found [here](http://www.ais-netherlands.nl/aim/2016-07-07-AIRAC/eAIP/html/eAIP/EH-AD-2.EHAM-en-GB.html#eham-ad-2.24)~~

**EIDW**:
- Update STAR's
- Terrain
- Charts can be found [here](http://iaip.iaa.ie/iaip/aip_eidw_charts.htm)

**EINN**:
- Update STAR's
- Terrain
- Charts can be found [here](http://iaip.iaa.ie/iaip/aip_einn_charts.htm)

**ENGM**:
- Update STAR's
- Terrain
- Charts can be found [here](https://www.ippc.no/norway_aip/current/aip/ad/engm/engm_en.html)

**ESPA**:
- Update STAR's
- Charts can be found [here](https://www.aro.lfv.se/Editorial/View/IAIP?folderId=46)

**LKPR**:
- Terrain
- Charts can be found [here](http://lis.rlp.cz/ais_data/www_main_control/frm_en_aip.htm)

**LTBA**:
- Update (Add) SID's + STAR's
- Terrain
- Reallistic airspace
- Charts can be found [here](http://vau.aero/navdb/chart/LTBA.pdf) (charts from 2015)

I'm definitely willing to help with the terrain on some of these airports, but it's gonna take a while. Additionally, these are only the European airport, there's still many other airports not on this list which also require updating.

**Comment by eliuuk** [comment]
@Fechulo Some of the Scandinavian airports may have interesting terrain. For EGCC, there are the Pennines. I can't contribute much to terrain contribution as the natural neighbour part just freezes up my PC ;c

**Comment by Fechulo** [comment]
@indianbhaji That's no problem, I'm willing to help out with the terrain. :smile:

**Comment by Alpi-no** [comment]
Thank you for doing that! @Fechulo In case of EDDM, terrain isn't that much of problem because I don't think it affects the airport. The alps are rather far way. And adding transitions will be a lot of work as well!
@indianbhaji one of the most interesting airports for terrain is LOWI! We should add that :D

**Comment by eliuuk** [comment]
Definitely LOWI! Missed that out :p

**Comment by Alpi-no** [comment]
I love LOWI :D such a beautiful and complicated airport

**Comment by eliuuk** [comment]
EGNM is also European @Fechulo

**Comment by Fechulo** [comment]
@indianbhaji I don't think it needs any updating. SID's are up to date, there's no STAR's in real life either and I don't think terrain is needed.

**Comment by eliuuk** [comment]
@Fechulo EGNM is the highest airport in the UK at around 600ft, if anything
we could just try using the EGCC terrain as it's not that far out.

**Comment by Fechulo** [comment]
@indianbhaji You're right, there is terrain, my bad. I'll update the list.

**Comment by eliuuk** [comment]
I'll start Heathrow.

**Comment by Fechulo** [comment]
I'll take Hamburg (EDDH). Updated with #662

**Comment by eliuuk** [comment]
I'll start München (EDDM). If someone could assist with terrain, it'll be greatly appreciated!

**Comment by scott-j-smith** [comment]
Hi All,

Don't know if this thread is still active, but I wonder if anyone still plans to review EGKK (Gatwick)?  I think there is something wrong with the LAM SID, because when I clear those departures (caf cvs) they just keep circling & climbing forever (maybe around KKN43?).  See screen shot:
![image](https://cloud.githubusercontent.com/assets/22403776/19217790/e723ac44-8db1-11e6-93cb-cf515842379f.png)

I looked through the EGKK JSON file without really knowing what I'm doing, and here is what I found for the SID:

 "sids": {
    "LAM": {
      "icao": "LAM",
      "name": "Lambourne",
      "suffix": {"08R":"1Z", "26L":"1X"},
      "rwy": {
        "08R": [["KKE02", "A20+|K250"], ["KKE12", "A30+"]],
        "26L": [["KKW04", "A25+|K220"], ["KKN06", "A30+|K220"], ["KKE14", "A40-|K250"]]
      },
      "body": [["SUNAV", "A5000"], ["KKE35", "A5000"], ["KKN43", "A5000"], ["KKN48", "A6000"], ["LAM", "A6000"]],
      "draw": [["KKE02", "KKE12"], ["KKW04", "KKN06", "KKE14", "SUNAV", "KKE35", "KKN43", "KKN48", "LAM"]]
    },

It appears they should climb from FL50 at KKN43 to FL60 at KKN48 and continue to LAM and depart, but they aren't doing that?  Not sure if I'm reading it correctly though.

Thanks,
Scott

**Comment by eliuuk** [comment]
Most of us are still waiting for V3 to come out. Gatwick seems to have the circling bug, @erikquinn?

**Comment by Fechulo** [comment]
@scott-j-smith @indianbhaji the circling bug at EGKK is due to my stupidity. The restrictions aren't written correctly. They're correct but the way I wrote them isn't. Instead of K250 it should be S250 and instead of A6000 it should be A60. As @indianbhaji said we're all waiting for v3 but I'll fix it as soon as it's out.

**Comment by scott-j-smith** [comment]
Thank you for the responses and explanations.  Happy to hear that
development and improvements are still ongoing to this sim.

Scott

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
