### ISSUE TITLE
Add Capability for holds & vectors in procedures

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#651]
European STARs need to end in a hold, and many vector SIDs are just proceeding direct rather than flying a heading like the chart shows. There should be a way added to make these possible as an inherent part of the SID/STAR.

**Comment by Alpi-no** [comment]
I completely agree! Do you think we could add go around procedures the same way?

**Comment by erikquinn** [comment]
Yeah. The idea is to make SIDs/STARs/Transitions/IAPs the exact same structure.

Also as a NOTAM to all you airport creators, please begin using "entryPoint" and "exitPoint" inside the procedures, instead of "transitions", due to a recent change meant to maintain clarity when "transition" procedures are added.

**Comment by eliuuk** [comment]
@erikquinn Oops, just accidently started using transitions in the latest update of Schiphol xD

**Comment by erikquinn** [comment]
Duplicate of #439. Closing.
