### ISSUE TITLE
Add IAPs

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#653]
Instrument approach procedures

**Comment by Alpi-no** [comment]
what is there still to do, for them being officially added in?

**Comment by eliuuk** [comment]
@jakobeng1303 I don't think @erikquinn has started on this yet?

**Comment by erikquinn** [comment]
Negative. It's just an issue to show that I want to soon. I might have some time when I get off work today. Transitions are the next addition, then VNAV improvements, then maybe this (?) or something like that. Sorry for the delay!

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
