### ISSUE TITLE
Include SID suffixes

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#655]
Include the `suffix` property in SID drawing and pronunciation.

**Comment by erikquinn** [comment]
@Fechulo @indianbhaji @jakobeng1303 @lachsschinken124

Anybody--

Can I count on SID/STAR/transition suffixes _always_ being 2 characters? For example "CPT" plus "2F" --> "CPT2F", or can they sometimes be not two characters? I haven't come across this yet, but would like to avoid some messy and unnecessary work if I can just remove the last two digits from "CPT2F" for the simulation logic to find the "CPT" sid. If not, I'll have to have it do some more complicated searching stuff that is best avoided if possible.

**Comment by eliuuk** [comment]
There's only one instance that I've found (which was coincidently an hour
ago) with a SID in Schiphol that had 3 characters on the end.

**Comment by eliuuk** [comment]
I can remove that one instance if you wish, it's a useless SID anyways.

**Comment by erikquinn** [comment]
Okay, as long as its SUPER rare, I can move ahead this way. Thanks for the quick response.

**Comment by eliuuk** [comment]
@erikquinn Oh no, no no! ZSPD has 3 characters.

**Comment by eliuuk** [comment]
@erikquinn A lot of them!

**Comment by erikquinn** [comment]
@indianbhaji UGGGHHHH alright, I'll figure something out. :sob: lol

**Comment by erikquinn** [comment]
@Fechulo @indianbhaji @jakobeng1303 @lachsschinken124

One more thing: When you assign a SID manually, would you prefer to specify just the fix name, or would you actually specify the full name _WITH_ suffix? Eg:
- `sid CPT`
- `sid CPT4K`

**Comment by eliuuk** [comment]
@erikquinn With suffix. CPT3K would be an older revision, and they increase with each new revision.

**Comment by eliuuk** [comment]
@erikquinn Do you intend on "collapsing" the SIDs in ZSPD into one SID? ie. all the ANDs come together? If not, it'll probably save you on a job of having to create something extra, since all the SIDs in ZSPD are already separate procedures.

**Comment by erikquinn** [comment]
Eventually, everything should be collapsed. It will work to leave them separate, but for readability, they should eventually be shrunk to a single "AND" procedure, with the appropriate suffix and rwy sections, and the sim should be able to make it all work properly. Should make it easier to create and maintain airports this way.

**Comment by eliuuk** [comment]
Thanks, but the thing with ZSPD is that there are a load of AND SIDs, and I 
believe there are more SIDs than runways.

**Comment by luznicky** [comment]
Hi,
do you also know, that you can have more suffixes for one RWY. Like ARTUP2A and ARTUP2M which both are valid. (See http://lis.rlp.cz/ais_data/aip/data/valid/a2-pr-sid24n.pdf). It's not big deal as you can choose the one which suits your defined departures.

**Comment by eliuuk** [comment]
@luznicky Yep, and that's the problem. If we were to collapse all the SIDs with different suffixes into one SID, how would you tell the game which set of fixes are for this particular suffix? If you look at ZSPD, the AND SID comes with many different variations and suffixes.

**Comment by eliuuk** [comment]
@erikquinn How's the progress on this?

**Comment by erikquinn** [comment]
@indianbhaji No change, but lots of things in this realm are being improved, so it's only a matter of time. But no work has been done on this directly.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
