### ISSUE TITLE
Negative elevations cannot be interpreted

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#657]
EHAM is (correct me if I am wrong) the only **major** airport that is under sea level, and during testing EHAM, the console states that it is unable to parse these negative elevations. http://prntscr.com/c8ymel

**Comment by n8rzz** [comment]
In `v3` this now lives in `.parseElevation()` inside the `utilities/unitConverters.js` file.  

This error is a result of how the elevations are being parsed with a regex.  The Regex currently doesn't allow for negative numbers, thus, it fails an presents the error.  `/^(Infinity|(\d+(\.\d+)?)(m|ft))$/`

We could move (or duplicate) this issue on the `v3` [issues board](https://github.com/n8rzz/atc/issues)?  Fixing this would be rather trivial, not to mention it provides a good excuse to refactor that function anyway.

**Comment by n8rzz** [comment]
See below issues for more information:
- https://github.com/n8rzz/atc/issues/5
- https://github.com/n8rzz/atc/issues/6

**Comment by n8rzz** [comment]
This issue is fixed by #702

**Comment by erikquinn** [comment]
Resolved by #702.
