### ISSUE TITLE
Runway configuration selection

### ISSUE THREAD

**Issue by luznicky** [zlsa/atc#658]
Currently the runway for landing/take-offs is selected automatically based on wind direction. This is not ideal for airports with parallel runways (where it can be fixed easily). But it's worse on airports with almost parallel runways.

Furthermore when player selects a configuration only relevant fixes, and SIDs can be shown on radar screen, making the screen more readable.

I just tried to make an example, so you can try it get an idea whether it would be worth to have it: https://luznicky.github.io/atc/

May be it's useless, as it's possible to "assign" landing runway by using STARs (like on LOWW, star MIKOV.MABOD5M.LOWW), when STARS are not grouped for multiple runways. 
But this doesn't work (at least for me) with STARs defined for multiple runways. (Using VLM.VLM3S.LKPR nor VLM000.VLM3S.LKPR don't work (on LKPR)).

Note: the example code is messy and I know it.

**Comment by eliuuk** [comment]
I'm not getting your point. If you have parralel runways, you can do 'taxi 
<rwy>'.

**Comment by erikquinn** [comment]
@luznicky I agree, it would be nice to have different set configurations depending on how the airport flows. Helps keep the realism. For example, at Dulles, they typically depart 1R/30 or 19L/30, unless the wind is strong from the east (I'm told this is rare), and land 1C/1R or 19L/19C with 19R-1L used only in periods of heavy traffic. 

Being able to define the parameters that determine which configuration is to be implemented could go a long way to improving realism. For the Dulles example, the implemented wind is 350@7, which is almost exactly the wind we had today, and guess what-- we departed 30 pretty much all day long. Getting the game to emulate this without necessitating a user's specification of the appropriate runway would be something I would enjoy having.

**Comment by luznicky** [comment]
@indianbhaji there are two main points: 
1. to reduce number of displayed fixes to these which are only used in sid/stars on active rwy.
2. to be able to use "unoptimal" runway as default. Which is not big deal with departures (as you pointed), but it's nice to have arrivals with STARs you want.

@erikquinn Replacing default rwy with user specified arr/dep rwy in airport description file is a few line fix. Even with maintaining backward compatibility. Updating airport configurations is another job.

**Comment by Alpi-no** [comment]
if we are going to reduce fixes, we could sort them into different categories like arriving, departing or runways. As soon as that would work, something else could be implemented, that changes the visibility of the fixes depending on the aircraft you click on eg. all star fixes for arriving aircraft vice versa for departing ones.

**Comment by nielsvdweide** [comment]
This needs to be implemented ASAP! Great idea and will have a positive impact on playability.

**Comment by nielsvdweide** [comment]
Is anyone going to work on this? @erikquinn @Maverick283 @zlsa

**Comment by eliuuk** [comment]
@nielsvdweide I think this would be one of the things after zlsa/atc V3 happens (#679)

**Comment by erikquinn** [comment]
As for me, all of my work is on hold until completion of #679

**Comment by nielsvdweide** [comment]
Should have thought about this... Thanks guys! @indianbhaji @erikquinn

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
