### ISSUE TITLE
Beginner looking for help

### ISSUE THREAD

**Issue by Vikchill** [zlsa/atc#663]
Hello guys, and greetings from France.

I know his post looks garbage compared to what's usual here, and I apologize for that, but I was not able to find the answers to my questions. 

I am totally new to the ATC world, but I love the game. I am able to take aircrafts airborne and to the ground (mostly) safely, but I have trouble with SIDs and STARs.

SIDs first. I usually taxi the plane and caf them. Playing in KJFK, when they don't have an SID filed, I wish I could give them an accurate SID instead of just telling them to follow JFK3, which is all over the place... is there a way o do that?

Now, the big problem... STARs. I just don't know how to use it. I just use the rr command with a long pattern of fixes. Could anyone just give me an example of how to type the command for JFK, and tell me how can how know the STARs for a given airport? Or perhaps this STAR thing is only for already educated people, and I should keep workin the rr command?

Thanks for the help, and excuse my english.

**Comment by eliuuk** [comment]
Hello!

It's nice to see someone requesting clarification on here, so don't worry! The tutorial is somewhat 'outdated' so I'll try to answer some of your questions.

First of all, the wiki might help you (https://github.com/zlsa/atc/wiki), if you require any clarification on the commands. It's regularly updated and is (in my opinion) much more helpful than the tutorial in game.

**SIDs**

SIDs have 2 parts to them. There is the initial departure, which takes an aircraft to a specific point. After that, there is a transition, which basically leads them up to another branch or waypoint where they start their actual route towards their destination.

Think of it like a tree. The log is the initial departure, and the branches are the transitions. The apples then grow on the branches, which is their actual route to success.

Unfortunately, the JFK3 departure has a load of these transitions. Specifying their exit point is a pain, but it is possible if you wish! The commands for this are ['route'](https://github.com/zlsa/atc/wiki#route),  ['rr/reroute'](https://github.com/zlsa/atc/wiki#reroute) or [SID](https://github.com/zlsa/atc/wiki#sid). The route and reroute commands have a parameter that is split into 3 sections with dots in between. An example for JFK would be: 'KJFK.JFK3.WHITE'. 

The SID command is for departures that do not have a transition, like the SONIN departure in ESPA.

The 3 sections for the reroute/route command go as follows: airport.sid.exitPoint.

exitPoint in the case of JFK is the last waypoint, in other words the transition.

Using route will add on what you have told the aircraft to do on the end of what they are currently doing, whereas reroute will clear all that and make the aircraft do what you have requested for it to do, immediately.  You can always check what they are going to do by using the command 'sr'.

**STARs**
JFK doesn't have any STARs that can be executed by the player in-game, so apologies for that.

But, for many of the recent airports, STARs do exist.

Effectively, the player does not need to do anything about STARs. Aircraft will follow the STAR and descend on the STAR if it has altitude restrictions. You do not need to do anything about a STAR if it is already implemented in the airport, as STARs should start outside your airspace. You cannot issue STARs to aircraft outside your airspace, so they will enter your airspace whilst following a STAR.

If a STAR does fall inside your airspace, then you can attempt to assign that STAR to an aircraft using the ['STAR'](https://github.com/zlsa/atc/wiki#star) command. The format is like the route and reroute commands, but reversed. This time, they are in this order: entryPoint.star.airport.

entryPoint is the waypoint the STAR starts at.

STARs are not currently drawn on the screen. The only way to actually know what STARs there are in an airport is to check them in the individual coding of the airport on here. I'll take [Changi](https://github.com/zlsa/atc/blob/gh-pages/assets/airports/wsss.json) for example.

Scroll down to the 'stars' section. Every STAR is listed on here. The name of the STAR is given in the 'name' section.

For KJFK, what I suggest you do is use the command 'sr' to see where the aircraft are going. In the case of KJFK, the arrivals are coded in a fashion that they will follow a number of fixes. If you look at where they are going, you can give reroute commands as required, and descend them when applicable. Not all airports are like this, as most airports use STARs instead.

I hope I've answered a few of your questions. If you've got any more questions, feel free to ask!

**Comment by Alpi-no** [comment]
In some European airports, stars and transitions might exist! Generally a plane is cleared a STAR and you will have to re-clear it again onto it's transition or "second STAR". If you check out LOWW/Vienna, you will find planes arrive into BALAD, NERDU, MABOD, PESAT. These mark the clearance limit + local ATC has to clear a plane (theoretically out of the hold but this is not implemented yet) and assign it a transition to the runway (vectoring is possible too but that depends on the amount of traffic). 

I highly recommend you looking at Fr24 and the routes planes take to land and check out airport files. VATSIM provides quite a few of them!

**Comment by eliuuk** [comment]
Correct, the 'second STAR' is known as the IAP, instrument approach procedure, which takes the aircraft onto the ILS or glidepath from a clearance point (IAF). This is being addressed in #653.

**Comment by Vikchill** [comment]
Whaouh, thanks for the replies. Unfortunately, I am not there yet.

Let's do it from scrap. I am on JFK. A plane is "apron" for "JFK3". There a a lot of exit points for JFK3, how can I now which one he wants to go?

Let's assume I would like this plane to go to "JFK3.WHITE", to stay with the one you mentioned, what's the command I need to type? I found out I can assign him to DEEZZ4, to JFK3 or to SKORR3 by typing "sid deezz4 / jfk3 / skorr3" but I wish I could assign a direct route.

I think I got it for STARs. Basically, when a plane enters my airspace, it already has a STAR, and most of times I don't have to care about that, I just need to route or rr them to the ground safely, correct? But then... isn't the STAR command useless? And if I play an airport that have STARs I can control, the only way to find them out is to open the code file.

Thanks for the help. Basically, I just wanted to know how to do it reallistically. I assumed the best way for planes taking off was "sid xxx" and then "cvs", so I wanted to use the "dvs" command for planes to land, but now my undesrtanding is that the good way to to it is with "route" or "rr".

Am I right? Merci beaucoup!

**Comment by Alpi-no** [comment]
Planes will file a SID, you have to clear them on this SID with `caf` command (cleared as filed). After that you would use the `CVS.` This is not something you should worry to much about. It'll go where it's supposed to!
The STARS are, what you should be "worried" about! You think about routing them and where the STAR is heading! In some US airports a star might go to the opposite end of your airport, not where you would need it and in some European airports you have to assign new ones. 

I know reading Wiki's sucks but it helps a lot! https://github.com/zlsa/atc/wiki 

PS if you are not using the STAR command, you would typically vector with headings, not waypoints.

**Comment by Vikchill** [comment]
Can I create an SID/STAR by command? Like in KSFO something like "faith..divec..ponke..wetor..rokme..heman..nepic" to an SID? Would be helpful :p

**Comment by Alpi-no** [comment]
From the wiki:"  sid

Information - This command tells the specified plane a standard instrument departure route (SID) it should follow. Each SID is a list of fixes to be flown in sequence. Having a standardized route often helps organize departing traffic, and maintain separation from arriving aircraft.

Syntax - AAL123 sid [SID name]"

I would not worry about them. clear them via the CAF command and don't worry about changing them. It#s fine how the plane filed it

**Comment by Alpi-no** [comment]
@indianbhaji actually the IAP is the ILS, so this would be the third STAR! The transitions (when existing) would be nr. 2.

**Comment by Vikchill** [comment]
OK, so let's say I would like to create a standard path to 28L on KSFO following route "faith..divec..ponke..wetor..rokme..heman..nepic", can I create it as a personalized STAR route?

**Comment by Alpi-no** [comment]
that would only work with the rr command but why would you do that? clear them to land and they will automatically land! No need to route them on/along the localiser!

**Comment by Vikchill** [comment]
Before clearing them to land, shouldn't I route them to the runways?

**Comment by Alpi-no** [comment]
OK: this is the transition chart for LOWW http://charts.vacc-austria.org/LOWW/LOWW_Arrival_RNAV%20Transition%2034_26052016.pdf

Let's say, I cleared a plane from the BALAD holding for the BALAD3N transition (aka STAR in game) and told it to descent via the SID. As there is no traffic, I told it to direct to WW972 and clear it to land on runway 34. The direct command gave it a heading that crosses the localiser and the cleared to land command told it, that it should catch the localiser and land as soon as close to the lcoaliser.

Alternatively, I could have given the plane a command like fly heading 070 and when within short range of the localiser tell the plane to fly a heading that is **exactly** in-between 10-30 ° +- of the localiser. So in this case anything between 350-010. If the plane would arrive via any of the transitions and I would vector it, the final heading would be 310-330. 

I hope this helps!

**Comment by eliuuk** [comment]
> Let's do it from scrap. I am on JFK. A plane is "apron" for "JFK3". There a a lot of exit points for JFK3, how can I now which one he wants to go?
> 
> Let's assume I would like this plane to go to "JFK3.WHITE"

You don't know which exit point it wants to go. Either you 'caf' it, or you make your mind up as to which exit point you want it to go to.

To get it to go to JFK3.WHITE, the command would be `<aircraft> rr KJFK.JFK3.WHITE`

**Comment by eliuuk** [comment]
> Before clearing them to land, shouldn't I route them to the runways?

On European airports, you should vector it with headings to the runway. Routing them to the runway is another option, but is only typically done in American airports.

**Comment by Alpi-no** [comment]
> only typically done in American airports. 

I'm sorry @indianbhaji but thats actually absolutely not the case! Europe has transitions that are routes that are far more advanced, than American STARS+vectoring onto final. I can control an european airport without vectoring at all!

**Comment by eliuuk** [comment]
> > only typically done in American airports.
> > I'm sorry @indianbhaji but thats actually absolutely not the case! Europe has transitions that are routes that are far more advanced, than American STARS+vectoring onto final. I can control an european airport without vectoring at all!

You are absolutely correct. You can route aircraft onto the ILS, but vectoring is how you do it in the UK, The Netherlands and Belgium, as far as I know of.

**Comment by eliuuk** [comment]
> I think I got it for STARs. Basically, when a plane enters my airspace, it already has a STAR, and most of times I don't have to care about that, I just need to route or rr them to the ground safely, correct? But then... isn't the STAR command useless? And if I play an airport that have STARs I can control, the only way to find them out is to open the code file.

The STAR command is helpful, as the current situation is that the game is based off America. As such, the definition of a 'transition' defers from country to country. Essentially, the STAR command is useless at the current moment, as you have pointed out, as you'd have to check the code to know about what the different STARs are.

> Thanks for the help. Basically, I just wanted to know how to do it reallistically. I assumed the best way for planes taking off was "sid xxx" and then "cvs", so I wanted to use the "dvs" command for planes to land, but now my undesrtanding is that the good way to to it is with "route" or "rr".

'caf', 'cvs' then 'to' is the way to do it the easy way, if you don't mind where the aircraft goes. But, if you are concerned about where it goes, 'route' or 'rr' it is the way for you! It's up to you whether you use 'dvs' or not, but the aircraft will descend itself if it has a STAR already.

**Comment by Vikchill** [comment]
> Let's say, I cleared a plane from the BALAD holding for the BALAD3N transition (aka STAR in game) and told it to descent via the SID. As there is no traffic, I told it to direct to WW972 and clear it to land on runway 34. The direct command gave it a heading that crosses the localiser and the cleared to land command told it, that it should catch the localiser and land as soon as close to the lcoaliser.

OK, but how would that translate in the game, command wise?

**Comment by Alpi-no** [comment]
@indianbhaji I think that vectoring is very situational! It depends on traffic, weather, runways in use and what ATC prefers! I have to admit to not have listened to any of the countries' atc but speaking for LOWW, vectoring is only used when there is only few traffic and to get planes faster onto the localiser when flying on the transitions parallel to the localiser.

**Comment by Alpi-no** [comment]
@Vikchill balad.balad3n.loww dct ww972 dvs c 34
or h 070 c 50 after a while h 000 l 34
(Just tested both and they work perfectly fine)

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
