### ISSUE TITLE
Help needed with Atlanta Intl.

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#668]
I'm currently working on Atlanta-Hartsfield International Airport and as always, getting the sector files for the TARCON is very difficult. I haven't finished the airport yet, and there's still a lot to do, but I'd like to have the sector files by the time I need them.  If anyone has them or knows how to get them easily, let me know!

**Comment by willfrd** [comment]
I have a sector file from ivao (a online simulator network) which may be of any help, screenshot:
https://gyazo.com/eb096a71561527caa923a2ff35db678f

**Comment by Fechulo** [comment]
@willfrd I hadn't even thought of IVAO, I think it might work. In that case, I can get the sector files for myself. Thank you for reminding me that IVAO exists.
I'll close this for now and re-open it if I need anything else.

**Comment by willfrd** [comment]
ok you are welcome you need to look for them on the USA division sector files the name for the KATL sector is ZTL_1502. you are always welcome :-)
