### ISSUE TITLE
KORD Runways closed and renamed

### ISSUE THREAD

**Issue by doofus** [zlsa/atc#684]
As of 15 Sep 2016 runway 14R/32L is renamed 15/33 after the recent closure of runway 14L/32R.
http://www.flychicago.com/OHare/EN/AboutUs/PilotAwareness/Pages/Pilot-Awareness.aspx
http://www.flychicago.com/SiteCollectionDocuments/OHare/AboutUs/Pilot%20Awareness/OMP-PilotAwareness_9.15.2016.pdf

I was able to remove 14L/32R and rename 14R/32L to 15/33 in my own fork.  However, the geometries for the base video markers are...something else entriely.  The dashed approach markers and runway separation dots are still there and there are hundreds of coordinates to try to match up with what's on the screen and remove in the KORD.json file.

Is there an easy editor that you use for the video maps?  Or is there an easy way to report cursor position (in lat/long) in the simulator?  Or is there a need for a new tool here?

Cheers!

**Comment by doofus** [comment]
OK, here's some screen shots of KORD with updated runways.
- 14R/32L has been renamed to 15/33.
- 14L/32R has been removed.
- The runway centerline markers for 14L/32R have been removed.
- The lateral separation dots between 15/33 and 14L/32R have been removed.

Before: 
![kord-old](https://cloud.githubusercontent.com/assets/1654444/19109471/81bfe474-8aed-11e6-9064-2ae500d116e2.png)

KORD with 15/33 and 14L/32R removed:
![kord-new](https://cloud.githubusercontent.com/assets/1654444/19109503/a4c11ea2-8aed-11e6-89cd-199e565174e5.png)

Let me know what you think and I'll submit the Pull Request if there are no objections.

**Comment by erikquinn** [comment]
Looks good to me!

**Comment by erikquinn** [comment]
This has been resolved by @doofus's pull request, #687, which was merged via e47e3415277b7498a94ba5d8f0ba4b62d1319f19.

Closing.
