### ISSUE TITLE
Temporary prohibited airspace question

### ISSUE THREAD

**Issue by willfrd** [zlsa/atc#692]
Hello guys I´m currently working on Gran Canaria (GCLP), and I had a small question, there are a series of prohibited military areas within the arispace that are sometimes open through an anouncement via notam, the question is, shall I include it in the code so that its permanently there or not include it? because as far as I know I can´t put it so that it activates randomly.
Thanks,
willfrd

**Comment by erikquinn** [comment]
@willfrd Right, there are no provisions for activating/deactivating restricted airspace. And I would have to say it is very far down the list of priorities as well, so it most likely won't be implemented in the near future. Sorry! You'll have to choose whether or not you want them (or some of them) permanently active or permanently inactive.

**Comment by willfrd** [comment]
Ok, thanks for that @erikquinn :-)
