### ISSUE TITLE
[Airport Request] Toronto Pearson International Airport

### ISSUE THREAD

**Issue by mchlp** [zlsa/atc#693]
Hi,

It would be great to see this airport added to the game!

Lester B. Pearson Toronto International Airport (IATA: YYZ, ICAO: CYYZ)

https://en.wikipedia.org/wiki/Toronto_Pearson_International_Airport

Here is a map of the runways: 
http://wynlok.com/wordpress/wp-content/uploads/2012/06/Map-of-Runways-YYZ.jpg

Thanks!

**Comment by eliuuk** [comment]
This is now added onto my planned list, which also consists of 2 other Canadian airports!
