### ISSUE TITLE
Data blocs

### ISSUE THREAD

**Issue by Shirtail** [zlsa/atc#698]
Anyone having problems re-positioning data blocs besides me?

**Comment by Fechulo** [comment]
I'm not having any problems myself, what kind of problems are you encountering?

**Comment by Shirtail** [comment]
Can't re-position any. All I get is a projected route of flight out from the a/C.

**Comment by eliuuk** [comment]
Read the documentation! It says clearly that you need to click the
aircraft, then type ` and a number between 1-9.
https://github.com/zlsa/atc/wiki#move-data-block

**Comment by Shirtail** [comment]
Solved, thanks for the input. Got to punch the right key if you want it to work.
,
