### ISSUE TITLE
Deleted aircraft still in runway queue

### ISSUE THREAD

**Issue by jpeterson1346** [zlsa/atc#706]
Using del for an aircraft waiting on the runway successfully removes it from the screen; however, any subsequent aircraft wanting to takeoff on that same runway will throw back a "cleared for takeoff, number [#]...behind the [deleted aircraft]...," thus rendering the game unusable.

Ex at JFK: AA1, BA2, DL3, VS4 on the apron looking for taxi to a runway. Meanwhile CX10, EK11, and AF12 on approach for runway 31L.
- CX10 ILS 31L // _followed by a valid intercept; 10 mi final_
- EK11 ILS 31L // _also successful intercept; 14 mi final_
- AF12 ILS 31L // _successful intercept; 18 mi final_
_[then, ]_
- AA1 W 31L
- BA2 W 31L
- DL3 W 31L
- VS4 W 31L
_[all my departures are headed to 31L and have valid SIDS and climbs]
[by this time, CX10 is on a 2 mi final, EK11 on a 6 mi final, and AF12 on a 10 mi final. AA1 is waiting on the runway and to avoid an incursion, I issue]_
- AA1 DEL // _Aircraft then disappears, flight strip gone._
_[That's good and all. So, let's say the Emirates and Air France land successfully on 31R after I clear them for the parallel; the Cathay lands successfully on 31L. Now I can roll out my departures]_
- BA2 CAF CVS TO // _(on 31L)_
_[and here's what I get back]_
- "Speedbird two, cleared as filed, climb via the SID, runway 31L cleared for takeoff, number 2 behind the AA1."

Since AA1 is no longer on the field nor in my flight strip bay, there's nothing I can do and BA2 will just sit, waiting for AA1 to depart (i.e., forever).

Anybody else have this issue?

**Comment by jpeterson1346** [comment]
Here's an example in practice:
1. 

![1](https://cloud.githubusercontent.com/assets/9057104/20032168/fb6b6884-a352-11e6-8999-9d2d9c1328f0.png)

2.

![2](https://cloud.githubusercontent.com/assets/9057104/20032179/0b7a7364-a353-11e6-9c06-b33669eb1b2f.png)

3.

![3](https://cloud.githubusercontent.com/assets/9057104/20032182/1afb6e92-a353-11e6-9ac0-6f219bf8de11.png)

4.

![4](https://cloud.githubusercontent.com/assets/9057104/20032183/1f9580f0-a353-11e6-8981-798fd92f8837.png)

5.

![5](https://cloud.githubusercontent.com/assets/9057104/20032184/25594de6-a353-11e6-9a75-4c382f4039ac.png)

6.

![6](https://cloud.githubusercontent.com/assets/9057104/20032186/28da3d86-a353-11e6-8a3e-3e5cb32fa39e.png)

The American flight says the following:
"_AAL241, number 1 behind JetBlue six thirty eight_"

7.

![7](https://cloud.githubusercontent.com/assets/9057104/20032190/2ccd798a-a353-11e6-8656-f896c6593b8a.png)

The Delta flight on 4L (DAL2972) says:
"_DAL2972, number 2 behind American two forty one_"

**Comment by erikquinn** [comment]
Resolved by #755. Closing.
