### ISSUE TITLE
Reroute causing screen to freeze

### ISSUE THREAD

**Issue by jamesbraithwaitesa** [zlsa/atc#709]
I have not been able to successfully reroute an aircraft on a route containing more than one fix without the gui crashing.
`EIN714 rr RUBAR` works but `EIN714 rr RUBAR.DUNLO` makes the screen freeze.
While the screen is frozen it appears that the game is still running as the strips of aircraft landing still disappear, however, I can see no movement on the screen and can't zoom in or out or pan.

**Comment by Fechulo** [comment]
@jamesbraithwaitesa This is because it should be EIN714 rr RUBAR..DUNLO (two dots instead of one). If it's  a route between various fixes you should use 2 dots. If it's a procedure, like a SID or STAR, you should use 1 dot.

**Comment by erikquinn** [comment]
@Fechulo is correct. However, the game should throw all the errors it likes, and notify the user it was improperly formatted, but it _freezing_ definitely needs to be fixed.

**Comment by jamesbraithwaitesa** [comment]
@erikquinn My apologies, this seems to be resolved in V3.

**Comment by erikquinn** [comment]
Resolved by #702.
