### ISSUE TITLE
[v3.0.0 minor bug] right heading "ruler" not there

### ISSUE THREAD

**Issue by willfrd** [zlsa/atc#710]
Hi guys, I was testing the 3.0.0 version and found a minor bug:
![bug 3 0 0](https://cloud.githubusercontent.com/assets/20045335/20075788/9d19f458-a52d-11e6-9346-b9bf4e29cfab.jpg)
As you can see the right heading "ruler" is not there...

**Comment by willfrd** [comment]
Can I close this isssue then? Has this been fixed with n8rzz/atc#68 or n8rzz/atc#61?

**Comment by n8rzz** [comment]
no, not yet.  I will push out a new build once the PR has been approved and I'll have you re-test it.  Then, once you can verify that the defect has been fixed, we can close this.

as a note, my issues will close once they are merged into my `release/3.0.0` branch.

**Comment by willfrd** [comment]
Thanks @n8rzz, will do :-)

**Comment by n8rzz** [comment]
@willfrd you will see we've merged in a bugfix for the issue you reported and am pushing out a new build now.  When you have a chance, could you take a look and verify that the ones that are marked as fixed are in fact fixed?

**Comment by willfrd** [comment]
Thanks for the fix, closing issue, bug fixed, no more bugs found for now :-)
