### ISSUE TITLE
[3.0.0] Double readback (minor)

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#713]
Double readbacks happen when an aircraft is:

- On the apron, and a takeoff command is issued
- Inbound, and a takeoff command is issued
- Takeoff, without an assigned altitude

eg. QTR2360 is inbound for OTHH
> QTR2630 to
< QTR2630, inbound, inbound

**Comment by n8rzz** [comment]
These will all be fixed by https://github.com/n8rzz/atc/pull/70 / https://github.com/zlsa/atc/issues/711

Essentially the deferred command `takeoff` was getting run twice.

**Comment by n8rzz** [comment]
n8rzz#70 is now merged into `gh-pages`

**Comment by erikquinn** [comment]
Resolved by #702.
