### ISSUE TITLE
Scope Display Settings

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#716]
The user should have access to a UI that allows them to adjust various basic things about the way the markings on the scope are displayed. This would include adjustments to:

 - brightness of aircraft targets, data blocks, control symbols
 - brightness of background color
 - brightness and radius of range rings
 - brightness of video map markings
 - center of range rings
 - default direction of data block leader lines
 - default length of data block leader lines
 - default length of PTLs (see [#715](https://github.com/zlsa/atc/issues/715))

The UI should ideally not be hardcoded either, but rather controlled by some sort of configuration file that describes how to draw the buttons, so different ATC systems can be emulated as needed. For example, many newer facilities in the US use the STARS radar system, from which we should emulate the DCB. But for EGLL, it might make sense to develop a UI that looks and feels more like... whatever software it is that they use. Then we can include a property in the airport file that determines what style of scope should be loaded.

**Comment by n8rzz** [comment]
I would encourage you to split this into two separate issues; one for the list and one for the scope themes.

The list looks very doable.  The way I see that working in my head will take a new class and a refactor of the `CanvasController` that would interface with this class.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
