### ISSUE TITLE
Scoring Bug for GCRR in 3.0.0

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#725]
I'm playing GCRR on 3.0.0.  There seems to be a scoring bug because none of my successful arrivals are being counted in the score.   As you can see from the screen shot showing the game and the console view,  I've had 11 arrivals spawned, and only 6 are still flying, while the other 5 have all landed successfully (with no errors regarding ILS lock either). I've also had 24 spawned departures, with 8 still flying in my control, and the other 12 successfully flying out and transferring to center, with no errors.

My score should be 170 (5 arrivals + 12 departures), but it's only 120 since only the departures are getting counted.

![image](https://cloud.githubusercontent.com/assets/22403776/20277873/76b08f82-aa70-11e6-9874-878a541e5602.png)

**Comment by erikquinn** [comment]
Yeah, it's got some issues... haha added #726 to track the work on it.

**Comment by erikquinn** [comment]
Resolved by #731. Closing.
