### ISSUE TITLE
Using STAR command to change aircraft's assigned STAR throws errors

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#730]
![image](https://cloud.githubusercontent.com/assets/5103735/20334048/2ccef32a-ab85-11e6-98b8-bd889f2b6261.png)

Reproducible by taking any aircraft on a star and assigning them a new one with `star entryPoint.starName`. Note that using the reroute function does not seem to have the same problem: `rr entryPoint.starName.airportICAO`.

For example, at KSFO:
`star QUINN.BDEGA2` (no good, intended use)
`star QUINN.BDEGA2.KSFO` (no good, not intended use)
`rr QUINN.BDEGA2.KSFO` (works)
`rr YOSEM.YOSEM3.KSFO` *THEN* `star QUINN.BDEGA2` (works)

There seem to be problems with initializing the properties of the waypoints under certain conditions. For example, running the last example will "*work*", but the aircraft will have `null` as its assigned altitude and speed, which causes an unscheduled descent and other issues.

**Comment by n8rzz** [comment]
Hey, I left that breadcrumb.  The second argument that is getting passed to `clamp()` is not a number.  I've added this to my fork and will investigate further.  I may have this fixed already with v3.1.0 but maybe not.  

Thanks for the use cases!

**Comment by n8rzz** [comment]
actually, let me ask you, what is _supposed_ to happen with those two commands `star` and `rr`?  

What happens (or what is supposed to happen) to any previous Legs/Waypoints?  What happens with this new route and where does it go within the existing group of Legs/Waypoints.

**Comment by erikquinn** [comment]
The `star` command should:
- if no STAR yet assigned, append a new `Leg` at the end of `fms.legs`, containing the specified STAR
- if the last `Leg` in the `fms` that has a `type` of `"star"`, replace it with a new `Leg` of the specified STAR

The `reroute` command should:
- Wipe all waypoints out of the `fms` and re-generate them according to the provided route

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
