### ISSUE TITLE
Collisions outside airspace are penalized

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#736]
Hi all,

I was playing KSEA and everything was going fine, and then I got a notice about a collision between two flights (sorry I didn't get the flight call signs before the msg faded).  Looking at the map, the collision happened well outside my control area.  

First, shouldn't the game automatically prevent these collisions because the SIDS should be designed so it is impossible?

Second, I got a 40 point penalty for the crash (presumably 20 points per airplane?)  I don't think I should be penalized for collisions that occur outside my control area, no?

Thanks,
Scott

![image](https://cloud.githubusercontent.com/assets/22403776/20402678/a3fcedc0-accb-11e6-8b67-8e7988ec53f0.png)

**Comment by scott-j-smith** [comment]
Hi all,

Just a quick update on this issue.  It just happened to me again on airport TJSJ (and well outside the control airspace.   I also seem to have been penalized by -1000 points (!?)  because my score was 530 just prior, and as you can see in the screenshot it went to -470.    I was playing for at least 20 min. on timewarp 5.

Thanks,
Scott

![image](https://cloud.githubusercontent.com/assets/22403776/20726769/f1f24dd6-b644-11e6-84fd-7b19aac41875.png)

**Comment by erikquinn** [comment]
That's the new (and more appropriate) value for creating a fireball in the sky. However, you definitely shouldn't be penalized when this happens outside of your airspace.

**Comment by scott-j-smith** [comment]
"Fireball in the sky" -- I like it!   I agree it is appropriate - just
checking it wasn't another bug.  :-)

Sorry I didn't get the call signs of the two planes that crashed so we
could check the SID's they were following.

**Comment by Fechulo** [comment]
@scott-j-smith Judging by the position of the crash, I can deduce that both aircraft were following the JOSHE 3 Arrival.

**Comment by erikquinn** [comment]
Good info as far as preventing the collision in the airport file setup... Either way though, I think we should just disable the penalty if they are outside the airspace. It's a pretty easy change. :)

**Comment by erikquinn** [comment]
Resolved by #755. Closing.
