### ISSUE TITLE
Setting for rate of aircraft generation

### ISSUE THREAD

**Issue by robbarry** [zlsa/atc#74]
It'd be great to have a setting that allows users to vary the rate at which new aircraft are generated.

**Comment by iphoting** [comment]
I like this possibility. It allows the user to increase the difficulty.

**Comment by Diastro** [comment]
@zlsa Anyway you could try to think about some UI update for this? I don't mind doing the code behind it.

**Comment by zlsa** [comment]
At first, we can just use a command such as "rate 2" or something similar. The timewarp button cycling didn't turn out too good from a UI point of view.

**Comment by sixeyeco** [comment]
@zsla: ty for great code. there's no time warp IRL. i prefer "increase traffic" setting. skills will develop to eliminate the need for TW.
