### ISSUE TITLE
ENGM cannot DIRECT TOR

### ISSUE THREAD

**Issue by fredrikhr** [zlsa/atc#742]
At the ENGM airport, there is a SID for the TOR (Torp) VOR station. When running
```
DLH944 DIRECT TOR
```
The game responds with `Command not found`. There seems to be a bug in how the TOR VOR station is not recognized as a valid Fix?

```
> DLH944 sr
DLH944, route: engm TOR.TOR
```

**Comment by doofus** [comment]
I believe this is covered in #700.  If so, then should this be closed or merged with #700?

**Comment by fredrikhr** [comment]
totally agree, sorry for the duplicate

**Comment by erikquinn** [comment]
Resolved by #755. Closing.
