### ISSUE TITLE
Problem with rr/reroute

### ISSUE THREAD

**Issue by mischeaux** [zlsa/atc#747]
Hi,
I'm new to zlsa/atc an having problems with the rr command.
Let's say I want to reroute an arrival in eddm for rwy 26r I type in
THY3034 rr RATGI..DM438..GUDEG
After pressing Enter nothing happens. Am I doing something wrong?
I saw this possibility at ATC Tuturial Part 3-Video...

btw:
After pressing Enter Java throws following exception:
AircraftFlightManagementSystem.js:491Uncaught TypeError: fixOK is not a function(…)
+ fixOK = undefined at this moment (?!?)

But the most important: You've done such a great job!!! It's real fun to play this one ;)

Thanks
Michael

**Comment by n8rzz** [comment]
Good news, that command seems to work without error in the upcoming v3.2.0 release.

In fact, I know exactly the line of code you are talking about and it is not lying to you; `fixOk` was in fact undefined.  The end of v3.2 development is scheduled for 12/19.  It's just a few weeks away!

**Comment by georgeenciu** [comment]
Hello, 

Could this be the source to the following error: 
`Uncaught TypeError: Invalid parameter. Expected `valueToClamp` to be a number(…) `
in core.js line 122

I get the fixOK error on issuing a "fix waypoint" command to an aircraft in LOWW, but in other airports seems to work just fine

thanks!

**Comment by n8rzz** [comment]
That is probably a different issue.  The error your seeing here is likely a result of undefined being passed as the second argument to that function. 

Which airport and command did you use to get this error?

**Comment by bradmccormick** [comment]
I agree that rr is broken, at multiple airports.  Trying to string together a couple of waypoints with 'rr waypoint1..waypoint2' and I can't even press enter.  (Amazing game, by the way --- great to hear a fix is coming.)

**Comment by georgeenciu** [comment]
After looking more carefully this is what happens on LOWW airport:
- load the airport
- issue takeoffs (all good)
- at some point a 404 for a javascript pops-up: 
`GET https://zlsa.github.io/atc/assets/airlines/msr.json 404 (Not Found)`
- first arrival enters the radar
- i give the command CALLSING STAR mabod.mabod4k.loww
- the "Invalid parameter. ExpectedvalueToClampto be a number" error appears and it keeps appearing (in the print screen about 566 times)
- this error stops appearing only when i issue the "descend via star" command
- issuing "fix waypoint" or "route waypoint..waipoint" commands will result in a "fixOK" error
![clipboard02](https://cloud.githubusercontent.com/assets/1264087/20724931/e2981daa-b678-11e6-8e0a-7cebf2c6b1c8.jpg)

**Comment by n8rzz** [comment]
@georgeenciu thank you for the additional information!  That will really help in tracking this down.  

Off the top of my head, this looks like it may be an undefined speed or altitude setting in with a `Waypoint` in the fms.  By issuing the `dvs` command those waypoints get updated and then, probably, speed and altitude get set correctly.  The errors that are showing up in the console are a side effect of the actual problem.  Again, I'm guessing here.

I would expect `fixOk` to fail because it is actually undefined in that method.  Not desired, but presently expected (and fixed in v3.2.0).

I'll take a look at this tonight on v3.2.0 and see what I can track down.  Once I do, I will probably add an issue on my fork for this.  At which point I will link back here for visibility.

**Comment by n8rzz** [comment]
also, the `msr.json` 404 is concerning.  That is likely a missing file.

**Comment by n8rzz** [comment]
#### good news
`CALLSIGN STAR mabod.mabod4k.loww` _does_ work without error on v3.2.0.
`CALLSIGN rr balad..ww172` _does_ work without error on v3.2.0
`CALLSIGN fix balad` _does_ work without error on v3.2.0

#### bad news
`THY6421 rr ww172..balad` _does not_ work on v3.2.0
`THY6421 fix ww172` _does not_ work on v3.2.0

@erikquinn I am fairly certain that the non-working commands are related to #700.

**Comment by mischeaux** [comment]
Thanks @n8rzz for your info! Then it's not me ;)

**Comment by n8rzz** [comment]
@mischeaux good news, the new `CommandParser` successfully parses the two commands above that were failing.  This will be released as part of v3.3.0 a little later this month.

**Comment by n8rzz** [comment]
adding https://github.com/n8rzz/atc/pull/179 and #755 for tracking purposes

**Comment by erikquinn** [comment]
Resolved by #755. Closing.
