### ISSUE TITLE
Airlines that specify "alpha: false" are treated like "alpha: true"

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#748]
Example file that is shown with alphanumeric flight numbers, and shouldn't have them (bad):
```
{
  "icao": "JBU",
  "name": "JetBlue",
  "callsign": {
    "name": "JetBlue",
    "length": 3,
    "alpha": false
  },
  "fleets": {
    "default": [
       ["A320", 130],
       ["A321", 27 ],
       ["E190", 60 ]
    ]
  }
}
```

Example of one that doesn't have alphanumeric flight numbers, and shouldn't have them (good):
```
{
  "name": "FedEx Express",
  "callsign": {
    "name": "Fedex",
    "length": 4
  },
  "fleets": {
    "default": [
      ["A306", 68 ],
      ["A310", 8  ],
      ["B752", 119],
      ["B763", 32 ],
      ["B77L", 32 ],
      ["DC10", 49 ], 
      ["MD11", 58 ]
    ],
    "feeder": [
      ["C208", 241],
      ["AT43", 26 ],
      ["AT72", 21 ]
    ]
  }
}
```

**Comment by n8rzz** [comment]
@erikquinn likely due to this line in the `AirlineModel`: `this.flightNumberGeneration.alpha = _has(data, 'callsign.alpha');`

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
