### ISSUE TITLE
KSFO

### ISSUE THREAD

**Issue by MemphisDon** [zlsa/atc#753]
Often times (happened twice in less than 10 minutes today) two aircraft will conflict before entering KSFO airspace to the west-northwest of the Airport.  One aircraft is usually inbound to PYE at FL240 and the other inbound to BGGLO at FL240 crossing each other path.

**Comment by erikquinn** [comment]
Same as described in #736.

Will be resolved by #755 (more specifically n8rzz#209).

**Comment by erikquinn** [comment]
Resolved by #755. Closing.
