### ISSUE TITLE
"Expedite" (x) not documented

### ISSUE THREAD

**Issue by panther2** [zlsa/atc#764]
I just realised that it is possible to enter for example

`ID a 30 expedite`
or
`ID a 30 x`

though the commands 'expedite' and 'x' are not documented in the index.md or wiki.

Has this been missed or has it been left out on purpose?

**Comment by n8rzz** [comment]
@panther2 `expedite` is currently only available for the `altitude` command (and aliases).  In the future it may become available for more commands, but as of now (and v3.2.0 #755 ) it is only available for altitude.

The wiki will be updated with the expedite command and the other changes once v3.2.0 is merged

**Comment by panther2** [comment]
Thanks.

**Comment by n8rzz** [comment]
no problem and thanks for the callout.  if you see anything more, please let us know!

**Comment by panther2** [comment]
Will do with pleasure. I'm enjoying the simulation as well as following the repos very much.
