### ISSUE TITLE
LOWW issuing star command freezes the game

### ISSUE THREAD

**Issue by georgeenciu** [zlsa/atc#768]
Hello, 

I have the following situation that happened twice already: 

- on LOWW chart AUA241 enters the radar from PESAT with heading 360
- after issuing the command `star ww665.balad3k.loww` the game freezes, i can not click on anything, i can not issue any command
![screenshot 2016-12-22 18 00 16](https://cloud.githubusercontent.com/assets/1264087/21431742/30d27326-c871-11e6-8fa4-e2207447a29c.png)
![screenshot 2016-12-22 18 00 22](https://cloud.githubusercontent.com/assets/1264087/21431750/376f1662-c871-11e6-87a2-a7fe772c2c54.png)
- the error keeps appearing

**Comment by n8rzz** [comment]
@georgeenciu @erikquinn quick first pass, the `star` command is erroring here:
<img width="814" alt="screen shot 2016-12-22 at 1 28 25 pm" src="https://cloud.githubusercontent.com/assets/3325985/21437634/99eb2e7e-c84a-11e6-98d4-7f3bad20e5b7.png">

which seems odd because _there is_ and entry segment.  There _is not_ an exit segment, though.  When this fails, the current leg doesn't reset and when it tries to get the waypoints for what it thinks is the current leg, it fails because it doesn't exist.

Will continue investigating...

**Comment by n8rzz** [comment]
the other thing is that, as its written now, the command you included is actually invalid.  The correct command should be: `star balad.balad3k.loww`.  here is the definition for that route:
```javascript
"BALAD3K": {
     "icao": "BALAD3K",
     "name": "Balad three kilo",
     "entryPoints": {
          "BALAD": ["BALAD"]
      },
     "body": [["BALAD", "A100|S250-"], ["WW669", "A60+|S250-"], ["WW665", "A60|S250-"], ["WW663", "A50|S250"], ["WW661", "A50|S250-"], ["WW659", "A50-|S250-"], ["WW657", "A50-|S250-"], ["WW655", "A50-|S250-"], ["WW653", "A50-|S250-"], ["WW652", "A50-|S250-"], ["WW651", "A50-|S250-"], ["WW650", "A50-|S250-"], ["RW11", "A50-|S250-"]],
     "draw": [["BALAD", "WW669", "WW665", "WW663", "WW661", "WW659", "WW657", "WW655", "WW653", "WW652", "WW651", "WW650"]]
},
```

**Comment by n8rzz** [comment]
even with the corrected command, it will still fail.  so there is a legit problem here.

**Comment by n8rzz** [comment]
ultimately this fails because the currentWaypoint has a speed that is null.  how that waypoint does not have a speed is a bit of a mystery.

this issue seems to logged already as #730 (https://github.com/n8rzz/atc/issues/138)

**Comment by georgeenciu** [comment]
This is odd. I had the same freeze issue, but I could issue commands. I issued the `dvs` command to a plane I just issued `star nerdu.nerdu4k.loww` and it unfreeze

**Comment by georgeenciu** [comment]
I've retested it and here is what I've got:
- SXD4026 enters the radar. issuing the `sr` command it replies `XANUT.XANUT1W.LOWW`
![atc-1](https://cloud.githubusercontent.com/assets/1264087/21450155/f59bd72a-c8fc-11e6-98fc-efec604f05a4.jpg)
- I want to change that to the BALAD3K transition, so I issue: `star balad.balad3k.loww`
- the game freezes and the speed and altitude of SXD4026 disappear from the strip
![atc-2](https://cloud.githubusercontent.com/assets/1264087/21450181/241fe410-c8fd-11e6-9b53-9801f766d72a.jpg)
- the console fills up with the `Expected `valueToClamp` to be a number` error
- issuing `dvs` will resume the game 
![atc-3](https://cloud.githubusercontent.com/assets/1264087/21450208/44447bde-c8fd-11e6-8d5f-403dc65db5e2.jpg)

**Comment by ghost** [comment]
When you enter CAF to an already airborn plane it also freezes, I only played LOWW so far..

**Comment by georgeenciu** [comment]
didn't happened to me on `cvs`

**Comment by ghost** [comment]
I meant CAF (cleared as filed) 
dvs doesnt resume the game, LOWW running on Chrome 

EDIT:
It was a mistake that i entered this command to an already airborn plane, i was confused and choose the wrong one
