### ISSUE TITLE
Arrivals' landings cause "waiting" departures to be deleted

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#770]
>@scott-j-smith in #767:
>I had an issue on LKPR where I had a departing aircraft waiting to take off, while another one was landing. When the arriving aircraft switched to ground and was removed from the screen, the game also removed the departing one waiting to take off! The flight strip was still on the right side, but the white dot and the box were gone -- and I could not issue it any commands (like the command line was frozen -- I didn't even get the "command not understood" read back). I could still work with other planes though, and the rest of it seemed to still work. Sorry, but I closed the window by mistake when I mean to resize it to take a screenshot, so I don't have a console view or anything else for you to help explain it. If I see this again I'll let you know more details.
>
>Thanks,
>Scott

Additional details of this report can be found in #767.

Will be addressed as part of v.3.2.1, scheduled for push on 12/24.

**Comment by ghost** [comment]
Good, i also encountered this!
