### ISSUE TITLE
Spawned Arrival not Activated

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#773]
Hey all,

Playing EDDH and an arriving flight on the RIBSO arrival, call sign GWI9WY never got activated in my airspace.   Went all the way through the arrival route and along the runway heading to its final fix, then headed north because of the other bug.

Another one coming in on the BOGMU (?) arrival almost did the same thing, but became active just as it was lining up with the runway heading.  I forget which call sign it had.

Scott

![image](https://cloud.githubusercontent.com/assets/22403776/21554246/e5d1e166-cddb-11e6-86dc-5a4d8a2d6f70.png)

**Comment by scott-j-smith** [comment]
It's happening again with SXD6677 and EWG6760 on the RARUP arrival, and almost happened to EWG3713 on the RIBSO arrival too, but it came into control at the TOPRA fix.  Weird behaviors.

![image](https://cloud.githubusercontent.com/assets/22403776/21554420/5ea06bc0-cddd-11e6-8231-b1d355e614a6.png)

**Comment by erikquinn** [comment]
I'm having trouble reproducing this. Just sped through about 100 arrivals, and all of them appeared active on the scope at the appropriate time. There must be something I'm missing here. :confused:

**Comment by Fechulo** [comment]
I've seen this happen in other airports as well, though very rarely. It might be a bug in the code instead of the airport file, or maybe both? You can see an example of this happening in KATL (only available on my fork atm) in [this video](https://youtu.be/_FTyXnlZAuk?t=40) with AAL509 inbound from the Southwest. I checked the console after I finished recording and there were no errors. I don't think this helps in any way, but I wanted to let you know that it doesn't just happen at EDDH.

**Comment by scott-j-smith** [comment]
Hi,

Could it be browser related?  I'm running on Chrome currently.  I haven't
tried on others.

Scott

**Comment by erikquinn** [comment]
Thanks @fechulo, that is helpful to know it's not necessarily airport specific. If anybody is able to reproduce it again, and you are able to pause and leave the tab open, please do so and reach out here. There are a couple of things I'd like to check in the game via the console to see where it went wrong. And I'll continue trying to break it myself as well :)

**Comment by Fechulo** [comment]
@erikquinn I have an open tab with the error right now 😆 what do you need?

**Comment by n8rzz** [comment]
@Fechulo scroll to the top of the error list and take a screenshot of the first few errors.  Then, with the first error, open it up and take a screenshot of the entire stack trace (if possible).

Was there anything specific you did to get this to happen?  Or was it just through the course of running a simulation?

**Comment by Fechulo** [comment]
@n8rzz @erikquinn The only errors in the console don't have anything to do with any aircraft, they're just warnings regarding the SID's:
![errors](https://cloud.githubusercontent.com/assets/13125311/21594188/89d49d24-d117-11e6-9bc4-3330dec3eec3.PNG)
All I did was open up the game and use timewarp to wait until the bug occurred, no commands were issued to any aircraft.

**Comment by n8rzz** [comment]
@Fechulo And, yeah, those errors are a result of airport.json formatting and have nothing to do with the present simulation.  I only have a few minutes, but I'm going to reach out on slack right now and try to walk you through a thing quick.

**Comment by Fechulo** [comment]
@n8rzz upon further investigation, we have discovered that the altitude of the offending aircraft is exactly 10000.00011920929ft which is about 36 microns higher than FL100 (the airspace ceiling at EDDH), so the airplane is technically above the airspace. We now know why the aircraft couldn't be controlled and to fix this issue we need to see how the game is calculating the altitude of the aircraft and why it stopped its descent just before reaching 10,000ft.

![36 microns](https://cloud.githubusercontent.com/assets/13125311/21594507/413c90a4-d11b-11e6-9687-4d5045a4d116.PNG)

**Comment by erikquinn** [comment]
@Fechulo That's actually all I was planning to look at, good work. :wink:

I can create a new issue now for the actual problem, and link back here to the symptom. Thanks for the assistance. :+1:

**Comment by erikquinn** [comment]
Moved to new issue following discovery of the core problem. Closing.

**Comment by Fechulo** [comment]
@erikquinn It was actually @n8rzz who told me what to look for, I just followed his instructions :smile:

**Comment by erikquinn** [comment]
@Fechulo Good advice for all of us... he's a smart dude. :wink:

**Comment by erikquinn** [comment]
@Fechulo And if able, check slack pm's. I had a follow up question.
