### ISSUE TITLE
Ghost flight approach at EDDH

### ISSUE THREAD

**Issue by panther2** [zlsa/atc#775]
The arriving aircraft has neither been announced, commanded nor seen as a stripe:
![2](https://cloud.githubusercontent.com/assets/20812775/21568856/291b7518-ceb8-11e6-8adb-8446ae60021a.gif)

Corresponding console error:
![chrome_2016-12-30_17-26-41](https://cloud.githubusercontent.com/assets/20812775/21568861/33862ea8-ceb8-11e6-8075-919f12a06242.png)

**Comment by scott-j-smith** [comment]
I reported the same thing in #773 yesterday, though my console view didn't show all the same errors as yours.

**Comment by panther2** [comment]
Yes, it appears to be similar but the different console notes made me open a new issue for it.

**Comment by erikquinn** [comment]
Interesting. The console error seems to indicate that one of the fixes you used with the fix command does not exist (perhaps a typo or something). But if this was the case I would have hoped that it would be smart enough to reject the command some time before it got to the point of this error...

**Comment by panther2** [comment]
I did not do anything to that plane, except clicking on it to see it's route.

But of course... maybe the console notification did not address the above mentioned issue but something different... I can't remember what happened around that situation, though.

**Comment by erikquinn** [comment]
The console error is definitely from using the `fix` command. It might actually be completely separate from the aircraft not becoming active. The console error could just be from another aircraft that had the fix command used on it.

**Comment by panther2** [comment]
OK then, I will be back to the sim at EDDH soon... maybe a similar situation will occur then. I'll report back in that case.

**Comment by panther2** [comment]
I'm closing this issue as it has turned out to be redundant, obviously.
Well covered in #773
