### ISSUE TITLE
Game Hangs after 5 mins for Changi Airport (WSSS)

### ISSUE THREAD

**Issue by kelai3316** [zlsa/atc#787]
The game hangs after 5mins of play. Seems to be an issue only to this particular airport.

**Comment by eliuuk** [comment]
@kelai3316 Could you try playing at WSSS on http://www.openscope.co? I played for 15 minutes and I don't see any issues.

**Comment by erikquinn** [comment]
@kelai3316 Also, if it does hang, please open up the console and share a screenshot of any errors you may be seeing. (In most browsers, this is accessible by pressing the F12 key).

**Comment by kelai3316** [comment]
Plays smoothly on openscope.co. Thanks!

**Comment by novinsh** [comment]
Have a similar issue on chrome browser when the number of elements (such as the number of planes) increases.

**Comment by eliuuk** [comment]
@novinsh Do you have an error for this?

**Comment by novinsh** [comment]
@indianbhaji Gotta reproduce the situation and inspect for the errors!
