### ISSUE TITLE
South Africa

### ISSUE THREAD

**Issue by hawkeyesfc** [zlsa/atc#789]
Hi guys love the OPEN SCOPE act Sim you guys rock Im still learning code so its taking forever please can you guys consider adding southafrican airspaces swell like OR Tambo into in johannesburg and capetown, turbans King Shaka, port elizabeth, East-london, Bloemfontein, Lanseria, and the list goes on and on there are amazing destinations in south africa   hope to see these soon       thanks guys

**Comment by panther2** [comment]
Better ask here:
https://github.com/openscope/openscope/issues

as 

```
**This repository has a new home.**

The 'ATC' repository has moved and been rebranded as openScope. 
The simulator can be accessed at www.openscope.co.

```

:smiley:

**Comment by erikquinn** [comment]
And if you'd like to join our slack team (a desktop/web/mobile app where we all message each other and post announcements and stuff like that, just visit [http://slack.openscope.co](http://slack.openscope.co). :smile: 

Closing this issue.
