### ISSUE TITLE
Please add the airport of Santo Domingo Dominican Republic las Americas Int. MDSD

### ISSUE THREAD

**Issue by pedriglieri** [zlsa/atc#790]
Im a big fan of the simulator. i would love to play Las Americas the ICAO code is MDSD all information about charts and waypoints and specification are in 

http://aip.idac.gov.do/

**Comment by panther2** [comment]
Better ask here:
https://github.com/openscope/openscope/issues

as 

```
**This repository has a new home.**

The 'ATC' repository has moved and been rebranded as openScope. 
The simulator can be accessed at www.openscope.co.

```

:smiley:
