### ISSUE TITLE
help With aircraft delivery

### ISSUE THREAD

**Issue by jean1689** [zlsa/atc#792]
I have problems with the delivery of the airplanes, when the aircraft leave the approach zone, they notify me that the plane left the air space controlled, so I lower points

Which would be the correct way to deliver them, and which command to use

**Comment by n8rzz** [comment]
@jean1689 you should head on over to http://openscope.co

This repo has moved and this one is no longer maintained.  You can view the new repo at https://github.com/openscope/openscope

**Comment by erikquinn** [comment]
@jean1689 And feel free to hit us up on slack if you need help with anything! :smiley:

[http://slack.openscope.co](http://slack.openscope.co)

Closing this issue.
