### ISSUE TITLE
Heading & runway assignment given (and read back). Only runway assignment taken.

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#84]
When issued consecutively, the commands ("BAW660 TURN 45" then "BAW660 LAND 30L") work as expected. Yet, combining a fix (vector or waypoint) with a runway assignment results in only the runway being assigned. If this is as intended then the reported issue is that a full and correct read back occurs yet the instructions are not carried out. Repro: "[callsign] TURN 45 LAND 30L"

**Comment by sixeyeco** [comment]
Here's a link to a [video that fully describes the issue.](https://drive.google.com/file/d/0B64kk35ARmnTbkFOR1VYbW1BWTA/view?usp=sharing) 

This one issue impacts my game play the most. When I identify the final turn that will put a plane on to ILS I am forced to issue two, separate commands (e.g. T 300, then L 30L). This occurs at a time when I am likely to have multiple craft in close proximity requiring close monitoring and commands.

Is it possible to allow a commands such as "fix narco land 30r" and "t 300 land 30r"?

**Comment by sixeyeco** [comment]
I'd be happy to close this issue if it's not considered an actual issue. But I would champion for the ability to issue a heading and a runway assignment in the same command.

**Comment by zlsa** [comment]
Hm, that should work properly. I'll investigate.

**Comment by zlsa** [comment]
In its current state, running the 'land' command clears all previous navigation and keeps flying the current heading until ILS is locked. @Diastro, does this sound "realistic"? i.e. if you were flying heading 090 and the tower said "turn heading 180 you are cleared to land on runway 180", would you be expected to turn 180 and then try landing?
