### ISSUE TITLE
Freeze (F [WAYPOINT] [ANY #])

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#85]
This "incorrect" command freezes the game.
repro: F[space][valid waypoint][space][any #]

I also froze after issuing a command with a syntax error [N249JY S200]. 
![image](https://cloud.githubusercontent.com/assets/179496/6204843/98360c4a-b50d-11e4-8db8-69184e8bb184.png)

**Comment by oslego** [comment]
Likewise: `FIX [waypoint] [number]`

![screen shot 2015-05-26 at 7 58 44 pm](https://cloud.githubusercontent.com/assets/63899/7820668/ad7db440-03e1-11e5-900b-f0c381d5f362.jpg)
