### ISSUE TITLE
Blurry Canvas on Retina Display

### ISSUE THREAD

**Issue by suhaildawood** [zlsa/atc#86]
I noticed the canvas is blurry when I use my retina macbook. Any idea why? 

![screen shot 2015-02-15 at 12 05 31 am](https://cloud.githubusercontent.com/assets/1642260/6202166/186f6710-b4a7-11e4-8b5a-21a112f8c70c.png)

**Comment by zlsa** [comment]
HiDPI displays aren't handled properly yet. It has to check `devicePixelRatio` and scale the canvas up by that.

**Comment by glangford** [comment]
I have an experimental change to address this almost ready for review.
