### ISSUE TITLE
Turn radius discrepancy (two craft, same speed, same alt)  

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#88]
It's not as obvious in this picture but it is glaring during game play. 
![turn-radius-discrepancy](https://cloud.githubusercontent.com/assets/179496/6276524/6599c06a-b83c-11e4-9ef8-cb92770c1759.png)

Repro: Line up two craft on the same heading in close proximity to each other. Put the first craft into a holding pattern, quickly put the second one in to the same holding pattern.

Thanks again for this great code. Super fun game!

**Comment by tedrek** [comment]
The turn rate for aircraft is based on the exact model so if there are two aircraft but they are different models (ie a B744 vs an A320) they will turn at significantly different rates.  In this case 0.8 degrees/second vs 1.3 degrees/second.

I can't find any reason why two aircraft of the same model wouldn't turn at the same rate.

In reality turn rates (especially in a circle) are a function of speed vs. bank angle as opposed to aircraft model.

This will calculate the turn rate as the lesser of 3 degree/s or turn rate with 25 degrees bank at current speed, and is what I've been playing with recently.
var turn_rate = clamp(0, 1 / (this.speed / 8.883031), 0.0523598776);

I can create a pull request if this sounds like a good solution

**Comment by sixeyeco** [comment]
Thank you. I was mistaken. I did not compare two craft of same model, Just the same speed, heading and altitude.

I've been trying to get a feel for when to put a plane into 140 degree turn at full speed and have it line up for a perfect approach every time. This would explain my difficulty.     

If it jives with the way it is IRL then I would love turn rates dictated by speed and bank angle.
