### ISSUE TITLE
No more aeroplanes.

### ISSUE THREAD

**Issue by popey456963** [zlsa/atc#9]
Am I missing something, or after a certain period (less than 15 minutes), do no more planes come?

http://i.imgur.com/MUW6K3c.png (just, ignore the score.)

Running chrome, windows 7.

**Comment by zlsa** [comment]
Is there anything printed out in the console after it loads (and about 10 aircraft are created)? The updated version is 2.1.1, upper-right corner while loading.

**Comment by popey456963** [comment]
I get this message:

http://pastebin.com/WX7CdHr2

Which seems that creating aeroplanes is definitely working.  I will land/fly all planes and see if more are generated.

**Comment by jvt** [comment]
Just like to add in my log output here, maybe it'll help: http://pastebin.com/0Yy45gcJ

It seems like the plane generation is working until it reaches a certain number at which point it will stop generating any more.

**Comment by popey456963** [comment]
It seems as if it isn't a problem generating the aeroplanes, it's actually a problem calling the function which generates the aeroplanes.  
Where is the "aircraft_new()" function called?

**Comment by psycho202** [comment]
Popey: the aircraft_new function is being called in airport.js. 
At lines 256 to 260 for departures and at lines 296 to 303 for arrivals.

Both of these are being called in addAircraft, at line 227 in airport.js.

**Comment by joallard** [comment]
+1 on Firefox Aurora 36

**Comment by joallard** [comment]
I'm debugging around a little. As I understand it: game initally adds some departure, and that function will set up timeouts to add some more departure, based on the `timeout` parameter it receives. That parameter would be based on the big timeout array the game receives as options. But in the array, the timeout parameter the function will receive is set to `false`, hence no timeout. ("timeout" comes up a lot in this comment, but that is the nomenclature used in the code)

**Comment by zlsa** [comment]
Can reproduce, fix in progress.

I've never played it for more than about ten minutes so I never encountered this bug...

**Comment by joallard** [comment]
I just noticed it wasn't a big setting array, but rather just the timeouts added by the game to the queue, as async tasks. The `false` param on the call at airport.js:233 (Airport#addAircraft()) looks suspicious.

**Comment by zlsa** [comment]
For testing, you can run the command `timewarp 100` without a callsign (warning: high numbers will slow down your computer); to return to normal speed, type `timewarp 1`. This bug should be gone now.

**Comment by joallard** [comment]
Fix confirmed. However, the spawn rate is now too high. My list keeps growing and growing.

**Comment by jvt** [comment]
The spawn rate is definitely too high. It's very hard to deal with this ever-growing list of arrivals.
![screen shot 2014-12-14 at 11 28 25 pm](https://cloud.githubusercontent.com/assets/2718101/5430877/f91554e0-83e8-11e4-8e6a-1ed516ade3cf.png)

**Comment by joallard** [comment]
Maybe you could put a debug option to turn off spawn, and get a log of how fast we clear the planes, so we can estimate a natural frequency at which to make them respawn?

**Comment by joallard** [comment]
...or you could always monkeycode and play to find out that "ideal" rate instead of having to release yet another feature ;)

**Comment by zlsa** [comment]
The rate is set in each airport individually (so you can have a small airport with one arrival per hour, not that anyone would ever want that). I've raised the time for all the airports a bit but I'm pretty sure there's now an exponential amount of arrivals.

**Comment by popey456963** [comment]
Great to see this issue was resolved.
