### ISSUE TITLE
Visual ILS Lock (suggestion)

### ISSUE THREAD

**Issue by xenocide0** [zlsa/atc#93]
I have been trying to come up with a good looking / minimal visual ILS lock indicator:

Anyone else have any ideas? 

![atc_mockup](https://cloud.githubusercontent.com/assets/4967846/6401045/3e19ae9e-bdb2-11e4-944f-856d7397ca3e.jpg)

**Comment by zlsa** [comment]
That looks very good! I like the main one and alt 2; I think 1 and 3 are too complicated while 4 has a square which IMO doesn't fit with the theme. Do you have a branch with this written?

**Comment by xenocide0** [comment]
no, was just trying out ideas in photoshop.

Yea, I liked those the best also, leaning towards alt #2 as it seams the cleanest.

And here is another one:

![ils_lock](https://cloud.githubusercontent.com/assets/4967846/6401312/651cf17a-bdb4-11e4-9ce8-b4779c0f19b8.jpg)

**Comment by zlsa** [comment]
I can pretty easily implement this if we can pick one style. Do you prefer the main one or alt 2?

**Comment by xenocide0** [comment]
main one.    ( Looking at alt#2 now, its sort of looking like a mag glass... )

**Comment by zlsa** [comment]
I'm refactoring the infobox drawing code at the same time so this may take a day or two.

**Comment by zlsa** [comment]
... or longer. Sorry about the huge delay, but real life got in the way (as it often does).

**Comment by Diastro** [comment]
"Real life" is there such a thing! :P

On Tue, May 12, 2015 at 1:30 PM, Jon Ross notifications@github.com wrote:

> ... or longer. Sorry about the huge delay, but real life got in the way
> (as it often does).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zlsa/atc/issues/93#issuecomment-101411308.

## 

_David Albertson_

**Comment by xenocide0** [comment]
Damn you real life!

Seriously though, no worries.

**Comment by xenocide0** [comment]
I got the graphics portion working for it, just haven't dug through the code to find where to see if a plane has ILS enabled or locked.

**Comment by zlsa** [comment]
If the aircraft's `mode == "landing"`, then ILS is locked. Thanks for working on it.

**Comment by xenocide0** [comment]
Got a working local branch of it, but not sure how to get it pushed up to GetHub.

**Comment by avdg** [comment]
@xenocide0 Does this help? https://help.github.com/articles/set-up-git/

**Comment by Maverick283** [comment]
Can this issue be closed @zlsa?

**Comment by zlsa** [comment]
Yes, thanks @Maverick283.
